### ISSUE TITLE
Ajout d'equipement en vert !?

### ISSUE THREAD

**Issue by cokecorp** [NextDom/nextdom-core#1]
Je ne sais pas si c'est voulu ou non, mais je trouve que laisser le "plus" en vert comme sur Jeedom dénotte un peu avec le bleu.
oublie ou choix esthétique?
![image](https://user-images.githubusercontent.com/9156515/49646413-3aaac380-fa1f-11e8-8675-331f52750293.png)

**Comment by byackee** [comment]
Salut,

La couleur est défini par le plugin, donc on a pas trop la main.
Je vais regarder pour ecraser la class et du coup changer la couleur

Merci
