### ISSUE TITLE
pb plugin agenda

### ISSUE THREAD

**Issue by Esso1-jeedom** [NextDom/nextdom-core#100]
le plugins agenda ne fonctionne pas . 
on peut accéder au plugins, mais on ne peut pas éditer ou créer .
![bugg125](https://user-images.githubusercontent.com/40739563/45765501-752d6d00-bc35-11e8-9db7-75f53b39a5fb.JPG)
![bugg124](https://user-images.githubusercontent.com/40739563/45765505-76f73080-bc35-11e8-9548-41849df94504.JPG)
![capture - calend](https://user-images.githubusercontent.com/40739563/45765512-79598a80-bc35-11e8-95df-626e19dc2863.JPG)

**Comment by Sylvaner** [comment]
Normalement corrigé, à rééssayer après je n'ai pas le plugin pour essayer

**Comment by Esso1-jeedom** [comment]
ok j'ai accés je test le lpugins plus tard
