### ISSUE TITLE
Bug graphique thème Dark

### ISSUE THREAD

**Issue by Astral0** [NextDom/nextdom-core#1009]
Page Réseau de zwave en thème "Dark" : 

![image](https://user-images.githubusercontent.com/39194968/55356255-9fa49080-54ca-11e9-8501-146974336d57.png)

En thème "Mix" c'est mieux : 

![image](https://user-images.githubusercontent.com/39194968/55356281-b0550680-54ca-11e9-8d9d-0eadafd01055.png)

**Comment by Gis70** [comment]
+1 même soucis chez moi mais j'avais pas pris le temps de le dire :)

**Comment by psycofdj** [comment]
+1

**Comment by cyrilphoenix71** [comment]
@psycofdj @Gis70 est ce tjs présent sur PR Gui ?

**Comment by Gis70** [comment]
@cyrilphoenix71 oui c'est tj là

**Comment by Gis70** [comment]
corrigé sur 44e2bbc
