### ISSUE TITLE
plugin widget ne fonctionne pas

### ISSUE THREAD

**Issue by byackee** [NextDom/nextdom-core#101]
![image](https://user-images.githubusercontent.com/4707496/45779703-09122f80-bc5c-11e8-947e-e5a96032ab24.png)

**Comment by byackee** [comment]
Lors d'une sauvegarde de widget
![image](https://user-images.githubusercontent.com/4707496/45993220-1ed58980-c08e-11e8-8fe1-bd8ab388a35d.png)

**Comment by Sylvaner** [comment]
@astral0 t'as bloqué les droits sur le core ? :)

**Comment by Esso1-jeedom** [comment]
le plugins widget plante beaucoup.. voir la modification d'un widget créer etc...
