### ISSUE TITLE
Zwave bug log dependance

### ISSUE THREAD

**Issue by Esso1-jeedom** [NextDom/nextdom-core#1011]
pb Zwave
"
Could Not Open OZW Log File.
"
alors que ca marcher en 0.1.3.

**Information matérielles**
 - OS : : Debian 9.5
 - Navigateur :  chrome,  firefox
 - Version NextDom : ex : 0.1.4
 
 - Installé via : paquet deb,
je n'ai pas reussi a installer le MAJ du plugins ..

**Comment by slobberbone** [comment]
Tu l'as toujours celui là @Esso1-jeedom ? Si non je te laisse clore !

**Comment by Gis70** [comment]
Pour moi ce n'est plus d'actu ça fonctionne depuis qu'il y a eu des choses faite sur tmp/jeedom
Tu réouviras si jamais
