### ISSUE TITLE
recuperer le menu type F$B33

### ISSUE THREAD

**Issue by Esso1-jeedom** [NextDom/nextdom-core#1012]
le menu est simple

il y a des CSS
des icones
dans le répertoire /montheme sous nextdom

cela va servir pour des menu et cadre en HTML

.
voir comment faire
[montheme.zip](https://github.com/NextDom/nextdom-core/files/3035649/montheme.zip)

le plus simple et de copier coller le répertoire si il existe.

**Comment by slobberbone** [comment]
Fixed in #960
