### ISSUE TITLE
Mauvais intitulé icone clé API 

### ISSUE THREAD

**Issue by Gis70** [NextDom/nextdom-core#1015]
![image](https://user-images.githubusercontent.com/16589132/55437243-bb796680-559e-11e9-9f1a-da4cdda50dd5.png)

Ce n'est pas rafraîchir mais réinitialiser ou regénérer plutôt.

Et d'ailleurs si on réinitialise, la clé api n'est pas rafraîchie, obligé de faire un f5

**Comment by cyrilphoenix71** [comment]
Corrigé avec l'issue #1016

**Comment by Gis70** [comment]
OK validé pr le texte, mais pas de refresh auto
