### ISSUE TITLE
Bug selection de date dans page Historique

### ISSUE THREAD

**Issue by Astral0** [NextDom/nextdom-core#1018]
Voilà : 

![image](https://user-images.githubusercontent.com/39194968/55506607-29349980-5656-11e9-8648-52a352223b1e.png)

On ne peut pas sélectionner une plage : 

![image](https://user-images.githubusercontent.com/39194968/55506723-731d7f80-5656-11e9-8bff-aeb5e8cf33b1.png)

Et là ca marche : 

![image](https://user-images.githubusercontent.com/39194968/55506838-b841b180-5656-11e9-84ea-6317600a1600.png)

A noter, le format de date qui est différent ;)

**Comment by cyrilphoenix71** [comment]
doublons avec #1030
