### ISSUE TITLE
Bouton enregistrer ne fonctionne pas dans configuration commande

### ISSUE THREAD

**Issue by Gis70** [NextDom/nextdom-core#1020]
Les cases à cocher ne reste pas cochées ou décochées quand on sauvegarde dans config / commande (bouton engrenage d'une commande)

![image](https://user-images.githubusercontent.com/16589132/55645452-e9e28600-57d8-11e9-836a-bed0bfa6f191.png)

Idem dans Fixes

**Comment by Esso1-jeedom** [comment]
je me rappelle plus mais ce bugg, je me demande si  faut pas modifier le nom de l'objet, valider et sortir
reéditer et retirer le afficher le nom dans un 2eme temps..
ou bien y a une diff entre le menu ici , et l'edition de la commande direct dans son module, . soit tu edit le module dans l dash ou dans le design , soit dans l'interface du plugins . direct dans la commande ...

**Comment by Salvialf** [comment]
Je pense que c'est en lien:
Dans l'onglet 'code' des paramètres d'une commande, une fois cochée la case 'Activer' le reste malgré l'avoir décochée et enregistrer commande + équipement.

Les modifications du code ne sont pas enregistrées.

Voir PJ (Pour info: Les pop-ups de sauvegarde apparaissent bien en bas de la fenêtre)
![20190408_010328](https://user-images.githubusercontent.com/48010158/55691338-89e90c80-599d-11e9-8137-112b9e3329ad.gif)

**Comment by Gis70** [comment]
> Je pense que c'est en lien:
> Dans l'onglet 'code' des paramètres d'une commande, une fois cochée la case 'Activer' le reste malgré l'avoir décochée et enregistrer commande + équipement.
> 
> Les modifications du code ne sont pas enregistrées.
> 
> Voir PJ (Pour info: Les pop-ups de sauvegarde apparaissent bien en bas de la fenêtre)
> ![20190408_010328](https://user-images.githubusercontent.com/48010158/55691338-89e90c80-599d-11e9-8137-112b9e3329ad.gif)

HS, mais comment tu fais le gif ?

**Comment by Salvialf** [comment]
> HS, mais comment tu fais le gif ?

J'utilise un logiciel de capture d'écran et je transforme le mp4 en gif

**Comment by slobberbone** [comment]
Toujours d'actualité en 0.3.0

**Comment by Gis70** [comment]
Oui faut fixer ça me fait bien ***

Le mer. 3 juil. 2019 à 22:43, Slobberbone <notifications@github.com> a
écrit :

**Comment by Gis70** [comment]
C'est toujours là est pas difficile à tester... pas plus tard qu'avant hier sur UI...

**Comment by slobberbone** [comment]
Testé et Validé  1/3
