### ISSUE TITLE
[Page de mise à jour]Ajout de lien direct vers catégories (ancres ou onglets)

### ISSUE THREAD

**Issue by noodom** [NextDom/nextdom-core#1022]
Dans la page des mises à jour, une amélioration possible serait de proposer des liens vers les différentes catégories (core/plugins/widgets/scripts/autres) pour un accès direct (éviter de scroller sur une page potentiellement très longue.

- Possibilité de le gérer par des ancres (ancres devant toujours être accessibles une fois qu'on a sélectionné une catégorie => pouvoir revenir en haut de page ou pouvoir aller directement vers une autre catégorie)

- Ou possibilité de le gérer par onglets (un onglet par catégorie), avec en option un badge indiquant le nombre d'updates disponibles pour chacune des catégories

**Comment by Gis70** [comment]
OK Validé mais pas d'icône sur les plugins, widegets...:
![image](https://user-images.githubusercontent.com/16589132/56092722-b7fbae80-5ebf-11e9-8e08-14dc11e8463e.png)

**Comment by Gis70** [comment]
il y a les icones depuis le merge dans develop.
