### ISSUE TITLE
[Page Réseau] Message d'information incomplet (il manque 'Nextdom' à la fin)

### ISSUE THREAD

**Issue by noodom** [NextDom/nextdom-core#1024]
Dans la page réseau, la phrase d'information en haut de page est incomplète : il manque 'Nextdom' à la fin

Attention : cette configuration n'est là que pour informer de sa configuration réseau et n'a aucun impact sur les ports ou l'IP réellement utilisés pour joindre **Nextdom**

**Comment by cyrilphoenix71** [comment]
Ce n'est pas un bug, la phrase reprend le nom produit configurer dans la page "General" :
![image](https://user-images.githubusercontent.com/18350629/55711242-9ba5d080-59ec-11e9-8837-73025b1e6e14.png)

**Comment by noodom** [comment]
Bizarre, j'ai bien un nom de renseigné et je ne le vois pas dans la page réseau.
