### ISSUE TITLE
Gestion des chemins d'upload pour plan3d

### ISSUE THREAD

**Issue by psycofdj** [NextDom/nextdom-core#1027]
**Décrivez le bug**

J'ai des doutes sur https://github.com/NextDom/nextdom-core/blob/develop/core/ajax/plan3d.ajax.php#L180-L184
```php
        if ($plan3dHeader->getConfiguration('path') == '') {
            $plan3dHeader->setConfiguration('path', NEXTDOM_DATA . '/data/3d/' . config::genKey() . '/');
        }
        $file = $uploaddir . '/' . $_FILES['file']['name'];
        $cibDir = __DIR__ . '/../../' . $plan3dHeader->getConfiguration('path');
```
n'y a-t-il pas ici un problème ? on pose `/var/lib/nextdom/data/3d/$key/` dans le header path (si vide)
et juste derrière, ça construit le répertoire de décompression à base de `$(pwd)/../..//var/lib/nextdom/data/3d/<key>/`

je ne vois rien dans `Plan3dHeader::{setConfiguration,getConfiguration}` qui transformerai les chemins absolus en chemins relatifs

**Information matérielles**
 - Branche NextDom : develop (3f3aa0b)

**Comment by slobberbone** [comment]
A voir après intégration : https://github.com/NextDom/nextdom-core/tree/feature/UpdateThemeFolder

**Comment by cyrilphoenix71** [comment]
@slobberbone c fait non ?

**Comment by byackee** [comment]
oui c'est corrigé
