### ISSUE TITLE
Erreur lors de la sauvegarde en SMB

### ISSUE THREAD

**Issue by daodevinc** [NextDom/nextdom-core#1035]
**Décrivez le bug**
Lorsque l'on fait une seauvegarde en SMB (qui fonctionne !), une message d'erreur est retourné dans les logs :

`[2019-04-21 01:59:07][ERROR] : Erreur dans l'exécution du terminal, la valeur retournée est : 1. Détails : Domain=[WORKGROUP] OS=[Windows 6.1] Server=[Samba 4.4.16] NT_STATUS_NO_SUCH_FILE listing \SAUVEGARDE\Nextdom\Core\..`

**Information matérielles**
 - OS : Debian 9.5
 - Navigateur : Firefox
 - Version NextDom : 0.1.4
 - Branche NextDom : master
 - Installé via : paquet deb

**Comment by psycofdj** [comment]
je n'ai pas ce message d'erreur, par contre le backup ne fonctionne tout simplement pas sur la branch develop (03c2b2b79bf677224a5b7239c76dde86b2c3e1e9)

**Comment by Gis70** [comment]
OK validé, les sauvegardes refonctionnent. @Sigri44 le message vient du fait qu'il va y avoir une fonction dépréciée. Mais c'est réglé dans la branche develop.
