### ISSUE TITLE
Impossible de se connecter sous IExplorer

### ISSUE THREAD

**Issue by cyrilphoenix71** [NextDom/nextdom-core#1041]
A la connexion j'ai cette erreur sous IExplorer : 
![image](https://user-images.githubusercontent.com/18350629/56687674-21a56500-66d7-11e9-88d5-5f8d6e142b30.png)
Tout est ok sous chrome, firefox et edge

**Comment by slobberbone** [comment]
IE n'est plus maintenu par Microsoft. Nous non plus.
