### ISSUE TITLE
OK dans log restore backup mal écrit ==> oK

### ISSUE THREAD

**Issue by Gis70** [NextDom/nextdom-core#1047]
![image](https://user-images.githubusercontent.com/16589132/56833870-189bcb80-6870-11e9-9cbc-75c2ac6cee32.png)
 
En develop du 26/04

**Comment by psycofdj** [comment]
C'est fait *exprès*, afin de mieux différencier le `oK` du `Ko`. Ce n'est à mon sens pas un bug.

Ceci étant dit, cela peut se changer :)
