### ISSUE TITLE
Tous les dossiers ne sont pas sauvegardé lors d'un backup

### ISSUE THREAD

**Issue by Gis70** [NextDom/nextdom-core#1048]
Lors de la backup, tous les dossiers perso ne sont pas sauvegardés : 

ex : gsg (gestion des pellets)
un dossier avec des backup de JPI
 
les themes dans montheme 

Il faudrait sinon prévenir que rien n'est sauvegardé

**Comment by slobberbone** [comment]
Sera corrigé dans : https://github.com/NextDom/nextdom-core/tree/feature/UpdateThemeFolder

**Comment by cyrilphoenix71** [comment]
@slobberbone on clos ?

**Comment by slobberbone** [comment]
Fixé en 0.3.0
