### ISSUE TITLE
[develop] Résumé domotique en erreur si présence d'un ancien équipement

### ISSUE THREAD

**Issue by Gis70** [NextDom/nextdom-core#1050]
![image](https://user-images.githubusercontent.com/16589132/56854653-7bf23000-693a-11e9-8f87-aa99fbf2a018.png)

J'ai dû supprimé la ligne de l'équipement dans edLogic

Le plugin previsionmeteo s'appelait avant previsionpluie peut être...

**Comment by byackee** [comment]
@Gis70 ce message n'est pas lié au résumé domotique. nextdom cherche un plugin qui n'existe pas dans le repertoire plugin.
J'ai reproduis ton erreur et elle apparait a différents endroits lorsque nextdom veut afficher un eqlogic lié au plugin manquant
![image](https://user-images.githubusercontent.com/4707496/61798760-2ee30480-ae2a-11e9-926d-ed14093489cb.png)

**Comment by byackee** [comment]
je clos cette issue a j'en crée une issue #1197 pour trouver une solution plus globale

**Comment by Gis70** [comment]
Ok 😀

Le mer. 24 juil. 2019 à 15:49, Fresnel Vincent <notifications@github.com> a
écrit :
