### ISSUE TITLE
Jquery bootstrap >> NPM

### ISSUE THREAD

**Issue by cyrilphoenix71** [NextDom/nextdom-core#1064]
Proposition issue de la PR https://github.com/NextDom/nextdom-core/pull/1059
![image](https://user-images.githubusercontent.com/18350629/57074318-d2b58c00-6ce3-11e9-94d6-bd60c7934986.png)

**Comment by psycofdj** [comment]
plusieurs choses:
- cette lib n'existe en fait pas sur npm
  - jeedom utilise http://addyosmani.github.io/jquery-ui-bootstrap/
  - la version sur npm est https://github.com/gustavohenke/jquery-ui-bootstrap/
  - sur les repository github, on apprend que la premiere est marquée *deprecated* par son auteur, qui recommande d'utiliser la seconde
  - de ce que j'ai pu lire dans les fichiers, il semble y avoir une équivalence fonctionnelle entre les deux (mêmes classes css définies) et on pourrait donc remplacer la première par la seconde

- la seule trace d'utilisation de cette lib que je trouve est dans le plugin **widget** dans son modal `desktop/modal/widget.result.php`
  - or je ne vois aucun appel a ce modal, j'ai la conviction qu'il s'agit de code mort
  - @Sylvaner @Gis70 pouvez vous cherchez dans vos plugins si vous trouvez d'autres traces d'appel a cette lib ? `rgrep -R jquery-ui-bootstrap plugins/` ?
  - si on ne trouve pas d'utilisation, on pourra tout simplement la supprimer

**Comment by psycofdj** [comment]
Prière de valider les markets plugin (jeedom/nextdom) et le market widget
