### ISSUE TITLE
Soucis migration 

### ISSUE THREAD

**Issue by dcjona** [NextDom/nextdom-core#1066]
**Décrivez le bug**
[ START RESTORE / MIGRATION ]
*************** Starting procedure at 2019-05-02 16:22:56 ***************
Sends the start event of the restore/migration...  OK
File used for restoration : /usr/share/nextdom/backup/backup-dcjona-3.3.22-2019-05-02-10h27.tar.gz
Checking rights...
OK
Désactiver toutes les tâches cron... OK
Désactiver tous les scénarios... OK
Extract the backup...
OK
Delete the backup database...
Disables backup constraints...  OK
Delete the table : cmd...
OK
Delete the table : config...  OK
Delete the table : cron...  OK
Delete the table : dataStore...  OK
Delete the table : eqLogic...  OK
Delete the table : eqReal...  OK
Delete the table : history...  OK
Delete the table : historyArch...  OK
Delete the table : interactDef...  OK
Delete the table : interactQuery...  OK
Delete the table : listener...  OK
Delete the table : message...  OK
Delete the table : note...  OK
Delete the table : object...  OK
Delete the table : plan...  OK
Delete the table : plan3d...  OK
Delete the table : plan3dHeader...  OK
Delete the table : planHeader...  OK
Delete the table : scenario...  OK
Delete the table : scenarioElement...  OK
Delete the table : scenarioExpression...  OK
Delete the table : scenarioSubElement...  OK
Delete the table : update...  OK
Delete the table : user...  OK
Delete the table : view...  OK
Delete the table : viewData...  OK
Delete the table : viewZone...  OK
Restoring database...
OK
Updating database...
[ END RESTORE / MIGRATION ]
>>> ERROR : [MySQL] Error code : 42S02 (1146). Table 'nextdom.interactDef' doesn't exist  : SELECT `name`, `enable`, `query`, `reply`, `person`, `options`, `filtres`, `group`, `actions`, `id`
FROM `interactDef`
ORDER BY name, query
Details : Array
(
[0] => Array
(
[file] => /usr/share/nextdom/src/Managers/InteractDefManager.php
[line] => 82
[function] => Prepare
[class] => DB
[type] => ::
[args] => Array
(
[0] => SELECT `name`, `enable`, `query`, `reply`, `person`, `options`, `filtres`, `group`, `actions`, `id`
FROM `interactDef`
ORDER BY name, query
[1] => Array
(
)
[2] => 1
[3] => 8
[4] => NextDom\Model\Entity\InteractDef
)
)
[1] => Array
(
[file] => /usr/share/nextdom/install/restore.php
[line] => 129
[function] => all
[class] => NextDom\Managers\InteractDefManager
[type] => ::
[args] => Array
(
)
)
[2] => Array
(
[file] => /usr/share/nextdom/install/restore.php
[line] => 276
[function] => migrateDb
[args] => Array
(
)
)
)
Activer tous les scénarios... OK
Activer toutes les tâches cron... OK
Closing with error
PHP Fatal error:  Uncaught Exception: [MySQL] Error code : 42S02 (1146). Table 'nextdom.interactDef' doesn't exist  : SELECT `name`, `enable`, `query`, `reply`, `person`, `options`, `filtres`, `group`, `actions`, `id`
FROM `interactDef`
ORDER BY name, query in /usr/share/nextdom/core/class/DB.class.php:101
Stack trace:
#0 /usr/share/nextdom/src/Managers/InteractDefManager.php(82): DB::Prepare('SELECT `name`, ...', Array, 1, 8, 'NextDom\Model\E...')
#1 /usr/share/nextdom/install/restore.php(129): NextDom\Managers\InteractDefManager::all()
#2 /usr/share/nextdom/install/restore.php(276): migrateDb()
#3 {main}
thrown in /usr/share/nextdom/core/class/DB.class.php on line 101

**Information matérielles**
 - OS : Debian 9.5
 - Navigateur : chrome
 - Version NextDom : 0.1.4

**Comment by dcjona** [comment]
après retour et actualisation :
[MySQL] Error code : 42S02 (1146). Table 'nextdom.update' doesn't exist : SELECT count(*) FROM `update` WHERE `status`="update"

**Comment by slobberbone** [comment]
Ne devrait plus être présente dans la prochaine version, une fois cette PR validée: https://github.com/NextDom/nextdom-core/tree/feature/UpdateThemeFolder

**Comment by slobberbone** [comment]
Fixed in https://github.com/NextDom/nextdom-core/issues/960
