### ISSUE TITLE
Autres problème avec JeeXplorer : ouverture d'un fichier

### ISSUE THREAD

**Issue by Gis70** [NextDom/nextdom-core#1067]
Quand on souhaite ouvrir un fichier ça ne fonctionne pas :

![image](https://user-images.githubusercontent.com/16589132/57096807-6acc6900-6d16-11e9-8dde-0304a4874a2f.png)

![image](https://user-images.githubusercontent.com/16589132/57096815-71f37700-6d16-11e9-833d-d76611278da7.png)

Les erreurs s'accumulent...

**Comment by psycofdj** [comment]
je ne constate le problème que sur l'action "ouvrir" des fichiers

le mode *edit* fonctionne, il faut pour cela aller sur un fichier sur lequel on a les droits d'écriture (pas le core, donc)

et il se trouve qu'il se passe la même chose sur la page de démonstration de la bibliothèque sous-jacente au plugin: https://studio-42.github.io/elFinder/#elf_l1_TUlNRS10eXBlcw
