### ISSUE TITLE
Filtre année / tous... graphique dépendant de la plage renseignée

### ISSUE THREAD

**Issue by Gis70** [NextDom/nextdom-core#1068]
Les boutons de filtre de date sont dépendant de la plage renseignée plus haut.

Comme c'est par défaut un mois, année et tous ne marche pas.

![image](https://user-images.githubusercontent.com/16589132/57104113-d3701180-6d27-11e9-9026-c67b71f1d65c.png)

**Comment by cyrilphoenix71** [comment]
je clos car les graphs sont en train d'etre revus
