### ISSUE TITLE
[GUI] Vue mobile pas de thème chargé

### ISSUE THREAD

**Issue by Gis70** [NextDom/nextdom-core#1069]
Les thèmes choisis pr vue mobile ne sont pas chargés :

![image](https://user-images.githubusercontent.com/16589132/57105271-a40ed400-6d2a-11e9-8367-f2830268fbbc.png)

**Comment by psycofdj** [comment]
je n'ai pas cette erreur sur develop (d869022073ecab90efcd0014b1bcad740012bf73)
