### ISSUE TITLE
Mettre les icônes des plugins dans la page màj 

### ISSUE THREAD

**Issue by Gis70** [NextDom/nextdom-core#1070]
Page maj  : 
![image](https://user-images.githubusercontent.com/16589132/57161366-b56be500-6deb-11e9-9d4f-d67404e6974a.png)

Page gestion des plugins : 

![image](https://user-images.githubusercontent.com/16589132/57161392-c4eb2e00-6deb-11e9-9e26-0a3dfc6b3078.png)

c'est quand même plus joli :)

**Comment by cyrilphoenix71** [comment]
traitée dans PR Fixes May
