### ISSUE TITLE
bug flèche remontée rapide

### ISSUE THREAD

**Issue by Gis70** [NextDom/nextdom-core#1072]
La flèche pour revenir en haut ne marche plus :)

![image](https://user-images.githubusercontent.com/16589132/57166305-04b91200-6dfa-11e9-9729-fad360b877f6.png)

**Comment by psycofdj** [comment]
sur le commit d869022073ecab90efcd0014b1bcad740012bf73

**Comment by Gis70** [comment]
ok validé

**Comment by Sylvaner** [comment]
validé
