### ISSUE TITLE
CSS Perso non sauvegardée pour le mobile

### ISSUE THREAD

**Issue by Gis70** [NextDom/nextdom-core#1079]
La CSS perso n'est pas sauvegardée pr le mobile, elle l'est pr le dashboard PC
branche : 740fc05b

**Comment by themaluxis** [comment]
Après test, dans mon cas, la modification est bien effective dans "/var/www/html/var/custom/mobile/custom.css" mais n'est pas retournée dans l'interface de modification du CSS Perso.
Donc le CSS custom est bien pris en compte, mais Nextdom n'affiche juste pas le contenu actuel du fichier apparement.

**Comment by cyrilphoenix71** [comment]
n'a pu lieu d'etre
