### ISSUE TITLE
Barre blanche sur les design mobile

### ISSUE THREAD

**Issue by themaluxis** [NextDom/nextdom-core#1087]
Lorsque l'on utilise un design sur un smartphone, celui ci apparaît avec un barre blanche de 50px en haut, ça décale toute la page vers le bas. Très génant lorsque l'on fait un design à la taille de son écran ^^

Étapes pour reproduire le problème :
Sur PC on peut reproduire le problème avec l'outils de dev Google Chrome
- Pour cela aller dans un design, passer en mode simulation de mobile avec les outils de développement. Théoriquement tout va bien, la navbar est responsive et cela fonctionne bien.
- Faites un petit coup de F5, le design va se reload, et la div du design n'est plus affectée uniquement pas class="wrapper" mais par class="wrapper fullscreen"

- Sur Téléphone, il suffit d'ouvrir un design en désactivant bien "Afficher en mode ordinateur"

**Screenshots**
http://prntscr.com/nms18z
http://prntscr.com/nms1el

**Information matérielles**
 - OS : Debian 9.5
 - Chrome (Mobile et Win)
 - Version NextDom : Last
 - Branche NextDom : master
 - Installé via : apt-get

Component_CORE

**Comment by Sylvaner** [comment]
Bonjour,
Actuellement je travaille sur une nouvelle version mobile qui devrait intégralement remplacer l'ancienne.
Je vais bientot mettre en place une explication pour pouvoir la tester.

**Comment by themaluxis** [comment]
Cela permettra tout de même d'utiliser des design customs ?
