### ISSUE TITLE
bouton Activer desactiver tout les scénarios ne marche pas 

### ISSUE THREAD

**Issue by Esso1-jeedom** [NextDom/nextdom-core#1097]
**Décrivez le bug**
lors de l'appui sur le bouton pour activer ou désactiver les scénarios, rien ne ce passe. 

rien ne marche , ( n'active pas, ou ne désactive pas , tout les scénarios)

![active T](https://user-images.githubusercontent.com/40739563/57966343-cae72000-7950-11e9-8d56-ec0a886ec24b.JPG)
![activer T](https://user-images.githubusercontent.com/40739563/57966344-cd497a00-7950-11e9-8a6b-bc193fa29f7b.JPG)

**Comment by cyrilphoenix71** [comment]
le bug n'en est pas un, "desactiver tous" desactive en fait la gestion globale des scenarios, j'ajoute un test et un message

**Comment by Gis70** [comment]
ok validé

**Comment by Sylvaner** [comment]
Validé
