### ISSUE TITLE
Problème de l'affichage des message si on a scrollé

### ISSUE THREAD

**Issue by themaluxis** [NextDom/nextdom-core#1098]
**Décrivez le bug**
Lors de l'ouverture de la popup des messages, si la page a été scrollé vers le bas, la popup message s'ouvre mais autoscroll en TOP, du coup on ne voit pas les messages et ça casse le scroll, obligé de faire F5 pour récupérer la main sur la page

**Comment reproduire ?**
Étapes pour reproduire le problème :
1. Aller sur le dashboard et scrollé en milieu / bas de page
2. Cliquez sur l'icone des messages / notifications

**Information matérielles**
 - OS : Debian Stretch
 - Navigateur : Chrome
 - Version NextDom : last
 - Branche NextDom : master
 - Installé via : paquet

**Comment by Gis70** [comment]
ok validé, mais on a droit à un go on top quand même avant
