### ISSUE TITLE
Installation impossible sur Ubuntu 16.04

### ISSUE THREAD

**Issue by doudz** [NextDom/nextdom-core#11]
Bonjour,

Je tente d'installer Nextdom dans une VM afin de faire des tests. J'ai donc installer un Ubuntu server 16.04 avec juste openssh et j'ai lancé
`wget -O- https://raw.githubusercontent.com/NextDom/NextDom-DebInstaller/master/deb-install.sh | sudo bash`
Le processus est très long mais j'obtiens toujours le même résultat :

```
Préparation du dépaquetage de .../archives/nextdom_0.1.2_all.deb ...
 
>>>>> Directory /var/www/html is empty.. Deleting it ... <<<<<
 
Dépaquetage de nextdom (0.1.2) ...
Paramétrage de nextdom (0.1.2) ...
>>>> Error : can\'t connect to database <<<<
dpkg: erreur de traitement du paquet nextdom (--configure) :
 le sous-processus script post-installation installé a retourné une erreur de sortie d'état 1
Des erreurs ont été rencontrées pendant l'exécution :
 nextdom
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by slobberbone** [comment]
Bonjour @doudz , en effet nous ne sommes pas compatible Ubuntu. Pour le moment c'est uniquement Debian 9.

**Comment by doudz** [comment]
ah ok
il faudrait mettre à jour la page https://www.nextdom.org/elementor-230/installation-de-nextdom/ dans ce cas ;)

**Comment by slobberbone** [comment]
Ah en effet ! Désolé, grosse boulette de notre part !
