### ISSUE TITLE
Bug theme jquery introduit par mise a jour du vendor

### ISSUE THREAD

**Issue by cyrilphoenix71** [NextDom/nextdom-core#1101]
les modales sont bugguées graphiquement depuis que jquery est passé par npm

**Comment by Gis70** [comment]
ok validé si tu confirmes que ça c'est conforme (bord arrondi et plus de blanc)
![image](https://user-images.githubusercontent.com/16589132/58125728-83db8200-7c11-11e9-8890-9289c4ae301c.png)
