### ISSUE TITLE
Les icônes des boutons inclusions de certains plugins ne sont pas présents

### ISSUE THREAD

**Issue by Gis70** [NextDom/nextdom-core#1117]
Sur la 2.0.0 (et avant) les icônes des plugins suivants n'ont pas l'icônes des boutons inclusions.

- ESPEASY
![image](https://user-images.githubusercontent.com/16589132/58655709-030c3c80-831b-11e9-820c-6c43364a75d1.png)
- MySensor
- Xiaomi 
-Zwave..
![image](https://user-images.githubusercontent.com/16589132/58655828-5088a980-831b-11e9-9a4b-aa8b9c937e5b.png)

**Comment by Esso1-jeedom** [comment]
![image](https://user-images.githubusercontent.com/40739563/58701968-c2f19c00-83a4-11e9-9ae2-0f0edda97f8a.png)
pb

**Comment by Esso1-jeedom** [comment]
c la class fa fa-sign-in qui du coup est fas fa-sign-in
j'ai modifier et 'icone reviens si tu mets fa fa-sign-in
