### ISSUE TITLE
Page de configuration de certains plugin complètement KO

### ISSUE THREAD

**Issue by Gis70** [NextDom/nextdom-core#1118]
Certains plugins ayant reçu une màj pour une compatibilité avec les dernières versions de jeedom ont leurs pages de configuration complètement KO.

Zwave :

![image](https://user-images.githubusercontent.com/16589132/58655888-80d04800-831b-11e9-93d9-65a8e7f10a23.png)

JMQTT

![image](https://user-images.githubusercontent.com/16589132/58655910-8cbc0a00-831b-11e9-8fb3-16e7f1e59c82.png)

RFXCOM

![image](https://user-images.githubusercontent.com/16589132/58655937-9c3b5300-831b-11e9-8bd4-8be7d88cdb30.png)

AppMobile 

![image](https://user-images.githubusercontent.com/16589132/58655964-ab220580-831b-11e9-88b5-2393a6c759f8.png)

.... liste non exhaustive

**Comment by Esso1-jeedom** [comment]
![image](https://user-images.githubusercontent.com/40739563/58700881-ab64e400-83a1-11e9-8b9b-fcb705c8e97e.png)

**Comment by Esso1-jeedom** [comment]
attention le plugins ZWAVE n'as pas de pb sur la stable. 

plugins virtuelle..
plugins camera . 
plugins Agenda

**Comment by Gis70** [comment]
corrigé sur  44e2bbc
