### ISSUE TITLE
Mouse-over ne fonction plus depuis la 0.2.0

### ISSUE THREAD

**Issue by homefefeld** [NextDom/nextdom-core#1120]
**Décrivez le bug**
Le mouse-over sur l'ecran general de fonctione plus depuis la release 0.2.0

**Comment reproduire ?**
les 'bulles'  mouse over ne fonctionnent plus:

**Screenshots**
voici la version 0.1.4
![image](https://user-images.githubusercontent.com/3512839/58735405-936d7e80-83fa-11e9-9983-8e677ed79c2f.png)

**Comment by homefefeld** [comment]
cyrilphoenix71,
Si je ne me trompe pas, cette regression est apparue avec le commit : 
commit  **e2290aa9b1e656b231dc1cec121d2df69b062b31**  

cela avait l'air de fonctionner avec le commit precedent : 
commit  e0faf07c98f5e162eb3e4aaa76fb5b566d10c9c5

**Comment by byackee** [comment]
Ça fonctionne après un refresh de la page. Lors du 1er chargement les tooltips ne fonctionnent pas.

**Comment by byackee** [comment]
Fix sur la branche UI, elle sera merge sous peu sur develop
