### ISSUE TITLE
Ajout de timestamp dans les logs

### ISSUE THREAD

**Issue by themaluxis** [NextDom/nextdom-core#1124]
Salut, je trouve qu'il serait fort agréable d'ajouter un timestamp dans les logs Nextdom en effet, je ne regarde pas souvent les logs, mais lorsque j'y vois une erreur, j'aimerais bien savoir quand celle ci c'est produite, afin de pouvoir mettre en relation erreurs et divers déclencheurs :)

**Comment by byackee** [comment]
Salut,

Je n'ai pas compris ta demande, on a bien un timestamp dans les logs

![image](https://user-images.githubusercontent.com/4707496/59276586-e5b26900-8c5e-11e9-919d-283e94ce2e31.png)

Peux tu m'éclairer stp
