### ISSUE TITLE
Couleur bouton camera sur panel ou dash

### ISSUE THREAD

**Issue by Gis70** [NextDom/nextdom-core#1128]
En dark, les boutons sont illisibles : 

![image](https://user-images.githubusercontent.com/16589132/59164444-fce14180-8b0c-11e9-8222-a47591be372e.png)

![image](https://user-images.githubusercontent.com/16589132/59164448-08346d00-8b0d-11e9-890c-b53b4dd7444b.png)

**Comment by Gis70** [comment]
toujours d'actu sur 0.5.0 en rc1.

**Comment by Gis70** [comment]
![image](https://user-images.githubusercontent.com/16589132/71936454-bc809980-31a9-11ea-9ae1-792b31a4e5e3.png)

**Comment by lucguinchard** [comment]
Fix to https://github.com/NextDom/nextdom-core/commit/3085338a4b488b8094dd07396bddd740b17f6d89
