### ISSUE TITLE
creation d'une "Note" ne fonctionne plus ('Expert=>Administration&Reglage=>Notes)

### ISSUE THREAD

**Issue by homefefeld** [NextDom/nextdom-core#1131]
**Décrivez le bug**
Quand on veut creer une note (Expert->admin->notes) , une erreur apparait à l'écran 👍  

**Comment reproduire ?**
Étapes pour reproduire le problème :
1. Aller 'Expert=>Administration&Reglage=>Notes (dans la section Outils)'
2. Cliquez sur 'creer une note'
-> 

**Screenshots**
![image](https://user-images.githubusercontent.com/3512839/59258458-4ed2b600-8c38-11e9-80b9-84ae6b61e42e.png)

 - Version NextDom : : 0.2.0
 - Branche NextDom : master

**Comment by homefefeld** [comment]
enfin, la note est crée.. mais avec l'erreur...

**Comment by byackee** [comment]
corrigé avec la version 0.2 branche develop
