### ISSUE TITLE
Amélioration de la version mobile "full" (celle en AdminLTE)

### ISSUE THREAD

**Issue by Astral0** [NextDom/nextdom-core#1136]
J'utilise depuis plusieurs mois Nextdom sur mon smartphone pour faire diverses actions (surveillance des indicateurs, lancer des actions : clic sur des boutons virtuels, surveillance webcam "rapide").

il ne s'agit pas d'utiliser toutes les fonctionnalités offertes par AdminLTE, donc pas de paramétrage, pas de création de scénarios, etc. Mais en consultation ou en dépannage ponctionel (relance d'un scénario, etc.), cette version est très bien.

Deux petites demandes d'évolutions seraient souhaitables : 

1/ une regression suite à la dernière version : avant on pouvait scroller le dashboard en touchant n'importe où, y compris sur un objet/widget/tuile. Maintenant, il faut cliquer exactement à un endroit où il n'y a rien, ou bien sur la fine bordure de gauche (mais pas facile à chopper).

2/ un bug visuel : les tuiles sont automatiquement retaillées en largeur et adaptées à la largeur de l'écran. Ca c'est bien, mais ce qui l'est moins c'est qu'elles ne sont pas adaptées en hauteur, ce qui fait qu'en pratique les informations contenues dans une tuiles ne sont pas lisibles. 
Il faudrait que lorsqu'un tuile est redimensionnées en largeur à la largeur de l'écran, elle soit ajustée en hauteur en fonction de son contenu.

Thanks :)

AA

**Comment by slobberbone** [comment]
Plus d'actualité en 0.6.0
