### ISSUE TITLE
Page mise à jour plugins KO 

### ISSUE THREAD

**Issue by Gis70** [NextDom/nextdom-core#1141]
La recherche de maj de plugin n'a pas l'air fonctionnelle, en 2semaines je n'ai eu aucune proposition de maj
De plus j'ai 4 plugins en orange que j'ai mis à jour mais ils restent en orange.

C'est comme si cette page était figée.

Develop neuve  1bf04f6

**Comment by slobberbone** [comment]
En 0.2.0 ? Des fixs ont été fait là dessus pour la prochaine version

**Comment by cyrilphoenix71** [comment]
On clos alors ?

**Comment by Gis70** [comment]
c'est toujours KO sur UI

**Comment by slobberbone** [comment]
(le nombre de maj s'affiche convenablement et une fois un plugin maj, l'alerte se décrémente)

Validé et testé 1/3
