### ISSUE TITLE
Valeurs stockée en cache ou autre non restaurée après un restore

### ISSUE THREAD

**Issue by Gis70** [NextDom/nextdom-core#1142]
Après un restore, toutes les valeurs sont à 0, ce qu'il y avait dans le cache ? du moins ce qui était présent durant le backup n'est pas restauré, il faut attendre la maj des valeurs.7
7
Branche develop  1bf04f6

**Comment by slobberbone** [comment]
Après un restore il faut que toute les commandes soient executée une première fois. Ce n'est pas une histoire de cache. Je te laisse rouvrir l'issue si je réponds à coté ;)
