### ISSUE TITLE
La sélection revient sur 'White' dans le choix des themes

### ISSUE THREAD

**Issue by vinceg77** [NextDom/nextdom-core#1143]
**Décrivez le bug**
Lors du changement de thème, la selection (le point bleu en dessous de chaque thème) revient systématiquement sur White, meme si l'on vient de choisir Dark ou Mix. Au moment d'appuyer sur 'sauvegarder' le choix du thème  Mix ou Dark la sélection est sur 'White' ce qui n'est pas logique, voire confusant.

**Comment reproduire ?**
Étapes pour reproduire le problème :
1. Aller 'Administration/Customisation'
2. Cliquez sur un theme différent de celui en cours par exemple 'Mix.'
3. Le changement de thème s'effectue, mais la sélection est revenue sur White
4. Appuyer sur 'Sauvegarder' pour sauvegarder le passage en thème 'Mix'
    ----> on a le sentiment d'être en train de sauvegarder le thème White !

**Screenshots**
![Pb affichage selection du theme](https://user-images.githubusercontent.com/51484329/60426509-1437ba00-9bf5-11e9-9232-de33c70fc26e.gif)

**Information matérielles**
 - OS : [Debian 9.9]
 - Navigateur : [chrome]
 - Version NextDom : [0.2.0]
 - Branche NextDom : [master]
 - Installé via : [wget]

**Comment by cyrilphoenix71** [comment]
Traitée en UI
