### ISSUE TITLE
Bandeau des plugins replié dans la page Mise à Jour

### ISSUE THREAD

**Issue by vinceg77** [NextDom/nextdom-core#1144]
**Décrivez le bug**
Dans la page de MAJ le bandeau du Core dans l'onglet Core est OK et déplié par défaut. Dans l'onglet Plugin par contre le bandeau plugin est lui replié par défaut, jusqu'au prochain refresh de la page.

**Comment reproduire ?**

Étapes pour reproduire le problème :
_Si (et seulement si ?) une mise à  jour de plugin est disponible :_ 
1. Aller dans 'Mise(s) à jours'
2. Cliquez sur l'onglet 'Plugins'
Le bandeau est replié, et un ascenseur de defilement apparaît, impossible de lire quoi que ce soit.

**Screenshots**
![Pb affichage MAJ plugin](https://user-images.githubusercontent.com/51484329/60428733-d1c4ac00-9bf9-11e9-86c3-ad3621609654.gif)

**Information matérielles**
 - OS : [Debian 9.9]
 - Navigateur : [chrome]
 - Version NextDom : [0.2.0]
 - Branche NextDom : [master]
 - Installé via : [wget]

**Comment by cyrilphoenix71** [comment]
traitée en develop
