### ISSUE TITLE
Bug pour lancer la mise à jour d'un plugin

### ISSUE THREAD

**Issue by vinceg77** [NextDom/nextdom-core#1145]
**Décrivez le bug**
Alors qu'un plugin demande une MAJ et s'affiche bien comme tel, un click sur le plugin en question ne provoque pas le lancement de la MAJ jusqu'au prochain refresh de la page;

**Comment reproduire ?**
Étapes pour reproduire le problème :
_Si et seulement si une mise à jour de plugin est disponible :_
1. Aller dans 'Mise(s) à jours'
2. Cliquez sur l'onglet 'Plugins'
3. Cliquer sur le plugin qui nécessite une MAJ
  -----> Dans certains cas, rien ne se passe !

**Screenshots**
![MAJ plugin non clickable](https://user-images.githubusercontent.com/51484329/60429255-01c07f00-9bfb-11e9-940b-992309204f43.gif)

**Information matérielles**
 - OS : [Debian 9.9]
 - Navigateur : [chrome]
 - Version NextDom : [0.2.0]
 - Branche NextDom : [master]
 - Installé via : [wget]

**Labels**
Type_Bug

**Comment by cyrilphoenix71** [comment]
traitée en develop
