### ISSUE TITLE
Choisir un fichier distant comme avatar

### ISSUE THREAD

**Issue by vinceg77** [NextDom/nextdom-core#1146]
**Décrivez le bug**
Lors du choix d'un avatar il est possible de choisir soit un icone déjà présente dans la liste (fichiers locaux sur l'hôte) soit de cliquer sur 'Choisir un fichier' ce qui laisse entendre que l'on pourrait sélectionner n'importe quel image qui sera logiquement uploadée sur la machine hôte du NexDom. Lorsque l'on opte pour cette dernière option et que l'on clique sur choisir un fichier et que l'on sélectionne un fichier distant (enfin un fichier sur le client) on obtient un message d'erreur.
C'est moche et frustrant !!

**Comment reproduire ?**
Étapes pour reproduire le problème :
1. Aller 'Profil' (1er icone du menu)
2. Cliquez sur le profil/avatar
3. Dans la page qui s'ouvre cliquez sur 'Choisir un fichier'
4. Sélectionnez un fichier sur la machine client
 ----> On obtient une erreur Core / token d'accès invalid

**Screenshots**
![Choisir un fichier distant avatar](https://user-images.githubusercontent.com/51484329/60431464-28cd7f80-9c00-11e9-9244-9d728f472656.gif)

**Information matérielles**
 - OS : [Debian 9.9]
 - Navigateur : [chrome]
 - Version NextDom : [0.2.0]
 - Branche NextDom : [master]
 - Installé via : [wget]

**Comment by vinceg77** [comment]
En fait ce n'est pas qu'au niveau du choix des avatars... C'est partout où il y a une boite de dialogue 'Choisir un fichier'

**Comment by byackee** [comment]
@vinceg77 j'ai corrigé pour avatar, il y a un autre cas? car l'uplaod dans plan fonctionne bien

**Comment by vinceg77** [comment]
Là je suis en vacances, très loin de mon Nextdom, et j'avoue que je ne me souviens pas de mémoire dans quelle autre page on a la possibilité d'uploader un fichier. Mais j'avais trouvé le même problème sur cette autre page. (Edit : pour uploader un icône personnalisé, non ?)
Je ne suis pas expert, mais j'ai l'impression que c'est juste un problème de droit...
