### ISSUE TITLE
Bug avec le plugin VigilanceMétéo

### ISSUE THREAD

**Issue by vinceg77** [NextDom/nextdom-core#1149]
**Décrivez le bug**

Les équipements du plugin VigilanceMétéo sont basés pour la plupart sur une localisation (champs "Localisation à utiliser"). Lors de la création de l'équipement il est possible de sauvegarder tout en laissant ce champs vide. Si l'équipement est de type 'Vigilance Météo France' (uniquement) et que pour une raison ou une autre la localisation se retrouve vide (oubli à la création / suppression d'une localisation Geotrav / ...) le dashboard de l'objet parent affiche une erreur 

> 'Core Call to a member function execCmd() on boolean'

L'erreur ne se produit pas si la case 'Visible' de l'équipement n'est pas cochée ou si l'équipement n'est pas activé
L'erreur ne se produit que sur les équipement VigilanceMétéo de type 'Vigilance Météo France', les types 'Pluie à 1h' / Vigicrue / Marées / Surf / Météo des plages / Seismes / 'Qualité d'air' / 'Index Pollens' semblent ne pas provoquer l'erreur, même quand la localisation n'est pas renseignée.

N.B. : Le backup provient d'une installation Jeedom

**Comment reproduire ?**

1. Aller a un Plugin VigilanceMétéo 
2. Créer un nouvel équipement de type 'Vigilance Météo France'
3. Choisir un objet parent
4. Laisser volontairement le champs "Localisation à utiliser" vide
5. Sauvegarder l'équipement
6. L'affichage du dashboard de l'objet parent provoque une erreur 'Core Call to a member function execCmd() on boolean' lorsque l'on tente d'accéder au dashboard de cet objet et le dashboard affiche 'Aucun objet n'est associé à cette pièce'

**Screenshots**
![bug jardin](https://user-images.githubusercontent.com/51484329/60604174-61638980-9db7-11e9-8a5f-34da3969ec42.gif)

**Information matérielles**
 - OS : [Debian 9.9]
 - Navigateur : [chrome]
 - Version NextDom : [0.2.0]
 - Branche NextDom : [master]
 - Installé via : [wget]

PJ : http.error
[http.error.log](https://github.com/NextDom/nextdom-core/files/3355689/http.error.log)

**Comment by byackee** [comment]
@vinceg77 cette erreur est aussi présente sur jeedom ?

**Comment by vinceg77** [comment]
> cette erreur est aussi présente sur jeedom ?

Je viens de tester. Oui et Non
1/ l'UI de Jeedom ne permet pas de laisser le champs 'Localisation à utiliser' vide lors de la création de l'équipement Vigilance Météo
2/ Si je crée un équipement Vigilance Météo basé sur la 'Localisation à utiliser' ZZZ puis que je supprime ensuite la localisation ZZZ depuis le plugin Localisation et trajets, que je refresh le tout, le dashboard apparaît bien.
Si je vais ensuite dans l'équipement Vigilance Météo le champs 'Localisation à utiliser' est devenu vide mais tant que je ne le sauvegarde pas, le dashboard fonctionne.
Si je le sauvegarde en l'état avec ce champs vide, le dashboard concerné devient vide avec erreur 500 : Internal Server Error.

**Comment by Sylvaner** [comment]
Bonjour,

Je viens de tester avec la 0.3.0 et je n'ai pas eu de problème.
Peux-tu me dire si le problème est toujours présent @vinceg77 ?

**Comment by vinceg77** [comment]
Je viens de re-tester en 0.3.0 :

Le comportment est désormais presque similaire à celui de Jeedom : 

1/ l'UI de Nextdom 0.3.0 ne permet plus de laisser le champs 'Localisation à utiliser' vide lors de la création de l'équipement Vigilance Météo

2/ Si je crée un équipement Vigilance Météo basé sur la 'Localisation à utiliser' ZZZ puis que je supprime ensuite la localisation ZZZ depuis le plugin Localisation et trajets, que je refresh le tout, le dashboard de l'objet contenant l'équipement  affiche 'Aucun objet n'est associé à cette pièce ou aucun ne correspond à la catégorie choisie' et une erreur Core s'affiche :"Call to a member function execCmd() on Boolean'  (d'après mon test précédent celui de Jeedom fonctionne encore à ce stade, mais ca change pas grand chose !) :
![Capture](https://user-images.githubusercontent.com/51484329/62256438-99370e80-b401-11e9-9878-d2d242926a85.JPG)


3/ Si je vais ensuite dans l'équipement Vigilance Météo le champs 'Localisation à utiliser' est devenu vide (comme sous Jeedom)

Je pense que cela devient acceptable, il suffit de ne pas supprimer un geotrav utilisé par un équipement existant. Mais à vous de voir !
