### ISSUE TITLE
probleme parametrage couleur 

### ISSUE THREAD

**Issue by Esso1-jeedom** [NextDom/nextdom-core#115]
impossible de voir les couleurs pour modifier 
![dash](https://user-images.githubusercontent.com/40739563/45925089-11de5c00-bf0f-11e8-892c-7e3a15cb4a75.JPG)

L’utilisation d’XMLHttpRequest de façon synchrone sur le fil d’exécution principal est obsolète à cause de son impact négatif sur la navigation de l’utilisateur final. Consulter http://xhr.spec.whatwg.org/ pour plus d’informations. jquery.min.js:2:79417
Impossible de récupérer la source d’origine : request failed with status 404
URL de la source : http://192.168.1.8/3rdparty/datetimepicker/jquery.datetimepicker.scss[En savoir plus]
Impossible de récupérer la source d’origine : request failed with status 404
URL de la source : http://192.168.1.8/assets/css/desktop/_commun.scss[En savoir plus]

**Comment by byackee** [comment]
Ça aussi ça dû être réglé avec le ./gen_assets
Peux tu essayer ?

**Comment by byackee** [comment]
pour moi c'est ok
