### ISSUE TITLE
Problème avec le plugin Click-Link

### ISSUE THREAD

**Issue by vinceg77** [NextDom/nextdom-core#1155]
**Décrivez le bug**
Le plugin click-link permet entre autre d'ouvrir une vue/design/panel/dashboard/url dans une modale/fenêtre courant/nouvel onglet

La création d'un équipement dans ce plugin ne présente apparemment aucun problème particulier, la sauvegarde s'effectue correctement et l'équipement apparaît correctement dans le dashboard de son objet

Lors du clic sur le bouton de l'équipement généré par la commande d'action précédemment créée, il ne se passe absolument rien. Pas d'erreur, pas d'action.

**Comment reproduire ?**
Rien de particulier, créer un équipement Click-Link comme d'habitude avec une commande action.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/51484329/60684938-b5966880-9ea0-11e9-85d8-723976e4f478.JPG)

**Information matérielles**
 - OS : [Debian 9.9]
 - Navigateur : [chrome]
 - Version NextDom : [0.2.0]
 - Branche NextDom : [master]
 - Installé via : [wget]

**Comment by Sylvaner** [comment]
Bonjour je viens de poster un correctif à tester : https://github.com/NextDom/nextdom-core/pull/1169
Merci pour ce retour
