### ISSUE TITLE
Les backups ne sauvegardent pas les notes

### ISSUE THREAD

**Issue by vinceg77** [NextDom/nextdom-core#1157]
Suite à une mise à jour et donc réinstallation de la version 0.2.0 puis restauration du dernier backup, les notes (Outils/Notes) ne sont pas réintégrées (/ sauvegardées ?)
Le restore fonctionne mais Outils/Notes est vide après restauration

**Information matérielles**
 - OS : [Debian 9.9]
 - Navigateur : [chrome]
 - Version NextDom : [0.2.0]
 - Branche NextDom : [master]
 - Installé via : [wget]

**Comment by nextdom-user** [comment]
En fait les ntoes sont bien sauvegardées rassures-toi mais il existe un bug en 0.2.0 sur l'affichage des notes qui échoue.

A tester en 0.3.0

**Comment by Gis70** [comment]
OK sur develop en 0.3.0
