### ISSUE TITLE
Impossible de scroller sur un design dont la taille est supérieure à la fenêtre.

### ISSUE THREAD

**Issue by Nibb31** [NextDom/nextdom-core#1160]
**Décrivez le bug**
Il est impossible de scroller (et donc d'éditer) une page de Design qui dépasse la taille de l'écran: 
- Verticalement, Nextdom limite la scroll bar à la hauteur de la fenêtre (ou la résolution de l'écran) et masque une partie de la page avec la bannière de copyright.
- Horizontalement, il n'y a pas de scroll bar du tout.
Il est utile de dépasser la taille de l'écran, par exemple, lorsqu'on utilise un frame pour accélérer le switch entre plusieurs écrans, ou si on utilise un écran plus petit que celui auquel est destiné l'affichage du design.

**Comment reproduire ?**
1) Créer un nouveau design
2) Clic-droit > Configuration du Design
3) Entrer une taille de 5000x3000 par exemple (une résolution supérieure à celle de l'écran)
4) Affichage > 10x10 (pour voir ce qu'on fait)
5) On ne peut pas scroller verticalement au delà de la hauteur de la fenêtre et il n'y a pas de scroll bar horizontal.

**Screenshots**
![image](https://user-images.githubusercontent.com/9588895/60977239-64b6c200-a32f-11e9-9a1e-f0a492628d04.png)

**Information matérielles**
 - OS : 9.9
 - Navigateur : Firefox
 - Version NextDom : 0.3.0
 - Branche NextDom : dev
 - Installé via : "méthode 2"

**Comment by byackee** [comment]
c'est corrigé
