### ISSUE TITLE
migration perte d'image du design

### ISSUE THREAD

**Issue by Esso1-jeedom** [NextDom/nextdom-core#1165]
suite  a une migration les images de fond du design sont sauvegardé . 
par contre les images incorporé dans le design sont perdu

elles sont dans /core/img/planXX
il suffit de les mettre dans publics /img/ pour les recuperer dans le design 
![image](https://user-images.githubusercontent.com/40739563/61103017-bc107b80-a470-11e9-879c-e980c517b755.png)
![image](https://user-images.githubusercontent.com/40739563/61103033-c5014d00-a470-11e9-8452-85980f02c10e.png)

et si on les remets dans /publics/img
![image](https://user-images.githubusercontent.com/40739563/61103061-e06c5800-a470-11e9-8469-827cb761ebde.png)

il faudrait donc copier tout les plan* en rep et les mettre dans /publics/img
et les supprimer avant un backup pour faire le ménage
del plan*

**Comment by slobberbone** [comment]
Fixée dans https://github.com/NextDom/nextdom-core/pull/1176

**Comment by slobberbone** [comment]
Avant : ![avant](https://user-images.githubusercontent.com/3833875/61801297-cc403780-ae2e-11e9-8360-a370bcb9349c.png)
Après : ![après](https://user-images.githubusercontent.com/3833875/61801306-cf3b2800-ae2e-11e9-8aff-0dec51193de2.png)

**Comment by slobberbone** [comment]
Testé et validé 1/3

**Comment by byackee** [comment]
a priori les images de ajouter "images/camera" ne sont pas restore
![image](https://user-images.githubusercontent.com/4707496/61802644-1d512b00-ae31-11e9-8684-fd63fb388563.png)

ces images sont sauvegrdées dans un sous repertoire
![image](https://user-images.githubusercontent.com/4707496/61802710-36f27280-ae31-11e9-8076-a7262524f963.png)

le plan est bien sauvegardé mais pas restore

**Comment by byackee** [comment]
en faite apres restore, il y a 2 repertoire plans apres restore
data/plans
data/custom/plans
![image](https://user-images.githubusercontent.com/4707496/61803319-3a3a2e00-ae32-11e9-82b7-fcfc15259975.png)

**Comment by slobberbone** [comment]
Alors j'ai pas eu ça mais j'ai trouvé un cas où je faisais un peu de zele ;)

**Comment by byackee** [comment]
on y est presque, tout est bien sauvegardé et au bon endroit masi lors de la restore on a un soucis de double repertoire custom
![image](https://user-images.githubusercontent.com/4707496/61854615-c09c5180-aebe-11e9-9d57-72520b53176b.png)

**Comment by slobberbone** [comment]
C'est un soucis déjà corrigé dans a11aa41af2ad3998b94f24f78e1c121fd6b9cb34
J'ai mergé la develop dans cette PR, je te laisse valider @byackee

**Comment by slobberbone** [comment]
J'ai mergé la develop dans cette PR, je te laisse valider

**Comment by slobberbone** [comment]
@byackee a validé
