### ISSUE TITLE
Tooltip du dashboard passent sous le menu objet

### ISSUE THREAD

**Issue by cyrilphoenix71** [NextDom/nextdom-core#1171]
Passer en mode edition sur le dashboard (crayon)
Les bouton en haut a droite des pieces (resize) ont un tooltip
Le tooltip est au dessus du bouton est passe sous le menu du haut
> fix mettre le tooltip sous les boutons

**Comment by Gis70** [comment]
on valide quoi ?

**Comment by Gis70** [comment]
ok validé

**Comment by slobberbone** [comment]
Testé et validé 2/3
