### ISSUE TITLE
Affichage des plugins

### ISSUE THREAD

**Issue by Sylvaner** [NextDom/nextdom-core#1173]
Les plugins s'affichent tous au chargement initial de la page.

![Capture d’écran 2019-07-17 à 07 41 03](https://user-images.githubusercontent.com/957104/61350081-9d422880-a866-11e9-9a1a-d10ae9a3c3ad.jpg)

**Comment by cyrilphoenix71** [comment]
tous ou ceux resté d'un précédent backup ? a verifier si c le cas sur une fresh install ?

**Comment by slobberbone** [comment]
Validé et testé
