### ISSUE TITLE
pb affichage des modals Market (icones invisibles)

### ISSUE THREAD

**Issue by byackee** [NextDom/nextdom-core#1189]
valable pour market widget notamment

**Comment by byackee** [comment]
jeedom
![jeedom](https://user-images.githubusercontent.com/4707496/61707421-c40ecc00-ad4a-11e9-83ac-3b57bdeb9da2.png)

nextdom
![nextdom](https://user-images.githubusercontent.com/4707496/61707443-cb35da00-ad4a-11e9-8a69-a2b3fed13292.png)

**Comment by slobberbone** [comment]
Testé et validé 1/3

**Comment by slobberbone** [comment]
Testé et validé 1/3
