### ISSUE TITLE
page 404

### ISSUE THREAD

**Issue by ColonelMoutarde** [NextDom/nextdom-core#119]
La page : index.php?v=d&p=blabliblazefjkzefjzl (cette page n'existe pas ) retourne une erreur dans une box.
Fichier introuvable : /usr/share/nextdom/core/php/../../desktop/php/blabliblazefjkzefjzl.php 
Elle devrait renvoyer vers la page 404 selon moi.

**Comment by Astral0** [comment]
D'autant que si ca parcoure effectivement le file system c'est très dangereux car on pourrait remonter à / et aller taper des fichiers systèmes ?!

**Comment by ColonelMoutarde** [comment]
non, je ne pense pas je te fait un screen, tu va comprendre.

**Comment by ColonelMoutarde** [comment]
![screenshot_2018-09-25 dashbo - nextdom](https://user-images.githubusercontent.com/4697568/46006414-c4512300-c0b7-11e8-9950-68657f8abc71.png)
