### ISSUE TITLE
Not possible to change order in Resume page

### ISSUE THREAD

**Issue by slobberbone** [NextDom/nextdom-core#1190]
![Sélection_178](https://user-images.githubusercontent.com/3833875/61711113-95e1ba00-ad53-11e9-9a3d-4c23f7bcb2da.png)

**Comment by byackee** [comment]
cette fonction ne marche pas uniquement vers "Aucun".
Meme erreur sous jeedom
![image](https://user-images.githubusercontent.com/4707496/61797738-47521f80-ae28-11e9-9fee-8c48b6ae2b74.png)

**Comment by byackee** [comment]
#1033
