### ISSUE TITLE
Create a Wikipedia page for NextDom

### ISSUE THREAD

**Issue by homefefeld** [NextDom/nextdom-core#1191]
Est-ce que quelqun a le courage de comencer une page wiki pour NextDom.
Merci.

**Comment by vinceg77** [comment]
Je veux bien m'y coller mais j'aurais besoin d'avoir au préalable une rapide discussion avec les devs à l'origine du projet. Notamment pour avoir qqs guidelines sur ce que vous voudriez voir (ou pas) sur cette page et d'autre part par rapport à l'historique de création du projet Nextdom. SI vous préférez que ca soit fait par un plus ancien que moi, pas de souci, je ne me vexerai pas.

**Comment by homefefeld** [comment]
Done and dusted.
