### ISSUE TITLE
Fonction suppressions des plugins ne fonctionne pas

### ISSUE THREAD

**Issue by byackee** [NextDom/nextdom-core#1194]
**Décrivez le bug**
Sur la page des plugins lorsque l'on clique sur  "supprimer" pour un plugin rien ne se passe

**Comment reproduire ?**

**Information matérielles**
 - OS : Debian 9
 - Navigateur : [ex : chrome, safari]
 - Version NextDom : 0.3.0
 - Branche NextDom : develop

**Comment by slobberbone** [comment]
@byackee tu peux retester avec la dernière develop stp ?

**Comment by byackee** [comment]
c'est ok
