### ISSUE TITLE
Checker si le plugin est présent physiquement avant d'afficher un eqlogic

### ISSUE THREAD

**Issue by byackee** [NextDom/nextdom-core#1197]
si un plugin n'est plus présent dans le répertoire plugin et que nextdom veut afficher un eqlogic lié a ce plugin ça pète tout

![image](https://user-images.githubusercontent.com/4707496/61798868-5a65ef00-ae2a-11e9-9018-fddca2c23bae.png)

**Comment by Sylvaner** [comment]
Fix pour limité l'impact, mais si le plugin redéfini la fonction "toHtml" (comme opening) et utilise d'autres modules cette erreur apparaitra

**Comment by Gis70** [comment]
ok validé
