### ISSUE TITLE
Système d'installation de logiciel tiers via APT-GET

### ISSUE THREAD

**Issue by slobberbone** [NextDom/nextdom-core#12]
Helper permettant de gérer l'installation/maj/suppression de dépendances.

+ gère les logs d'installation
+ gère l'avancement (au début toujours dans un fichier tmp, plus tard, ce système d'installation sera un thread systmAction avaec retour d'état ...)
+ gère les commandes de maj/installation/suppression

**Comment by slobberbone** [comment]
Peut-être tenter de se diriger vers ansible ?
https://packagist.org/packages/asm/php-ansible

**Comment by Turgon37** [comment]
Je suis pour un outil comme ansible,
par contre je suis contre le wrapper en php (en tout cas celui proposé ci-dessus), il n'est pas spécialement actif et ne se contente que de wrapper les arguments du binaire ansible.

Je propose plutôt un daemon python accessible via une api http (ou autre) qui tourne en tâche de fond et qui attend qu'on lui demande de lancer une commande. On peut coupler avec #13 car ansible gère aussi l'execution de commande de manière sécurisé (échapement de caractères)

Mon idée c'est de pouvoir gérer les erreurs et le dry-run.

On pourrait imaginer qu'après le téléchargement d'un plugin, toutes les étapes de dépendances/installation soient lancés en dry-run et que l'utilisateur puisse confirmer les changements qui vont être appliqués sur son serveur ?

**Comment by cyrilphoenix71** [comment]
Du nouveau les gars ? @Turgon37 @slobberbone

**Comment by slobberbone** [comment]
Fait
