### ISSUE TITLE
le footer de nextdom sort de la page quand le menu de gauche est ouvert et trop grand

### ISSUE THREAD

**Issue by cyrilphoenix71** [NextDom/nextdom-core#1211]
la c ok :
![image](https://user-images.githubusercontent.com/18350629/61833349-4fd04780-ae74-11e9-8785-3bf1033fdf94.png)

la non :
![image](https://user-images.githubusercontent.com/18350629/61833465-ac336700-ae74-11e9-8e9d-2595cc77add5.png)

**Comment by slobberbone** [comment]
Non présent en 0.5.5
