### ISSUE TITLE
mise à jour

### ISSUE THREAD

**Issue by ColonelMoutarde** [NextDom/nextdom-core#122]
Le lancement des mise à jours (même si il n'y en pas de disponible). faite remonter plusieurs messages d'erreur dans la box alerte.
Si il n'y a pas de mise à jours disponibles, on ne devrais pas pouvoir lancer le script selon moi.

**Comment by ColonelMoutarde** [comment]
à l'issue de la tentative de mise à jour, j'ai un message "Token d'accès invalide"

**Comment by Sylvaner** [comment]
Comment t'as fait pour faire une mise à jour ?

**Comment by ColonelMoutarde** [comment]
j'ai cliqué sur mise à jour forcé

**Comment by Sylvaner** [comment]
Ce bug pourra être réglé quand nous passerons en version public
 - Soit on enlève nextdom de la liste et les updates se font avec le .deb
 - Soit on passe le type d'update en GitHub et c'est pareil, c'est dans la table update

**Comment by ColonelMoutarde** [comment]
le .deb me semble la meilleure solution

**Comment by Esso1-jeedom** [comment]
perso j'avais testé les maj pas eu de pb.. .
sauf une fois ou je me suis retrouvé sous jeedom

**Comment by Sylvaner** [comment]
C'est bon maintenant ?

**Comment by ColonelMoutarde** [comment]
je test dans 5 mins

**Comment by ColonelMoutarde** [comment]
![sans titre-1](https://user-images.githubusercontent.com/4697568/46620695-b70b4e00-cb25-11e8-8e30-ec6d40e1a76b.jpg)
je me suis retrouvé sous jeedom ! Suite à la mise à jours

**Comment by Sylvaner** [comment]
C'est bon là ? on peut cloturer ? :)

**Comment by ColonelMoutarde** [comment]
👍
