### ISSUE TITLE
nouveau type de Cmd au noyau: "File Uploader".

### ISSUE THREAD

**Issue by homefefeld** [NextDom/nextdom-core#1227]
Pourrions-nous ajouter un nouveau type de Cmd au noyau: "File Uploader". Nous pourrions ensuite créer de nouveaux plugins avec File Uloader accessible à partir de la "vue" et à partir des scénarios. J'aimerais pouvoir intégrer une telle fonction à mon plugin "SABnzbd": nous pourrions évidemment créer un widget personnalisé (à la @byackee ), mais je pense qu'il serait bien mieux de l'ajouter en tant que Cmd standard ( accessible aussi à partir de scénarios). Je voudrais ensuite utiliser cela dans d'autres plugins (Transmissions, SABnzbd). Je suis tout à fait conscient que cela voudrait dire que le plugin ne serait pas compatible avec Jeedom (mais c'est la vie...).
@byackee a commencé, mais c'etait en version "widget personnalisé"...
Merci pour votre aide.

**Comment by Sylvaner** [comment]
Si je comprends bien une dropzone en widget ou on peut caller des fichiers ?
