### ISSUE TITLE
redémarrage

### ISSUE THREAD

**Issue by ColonelMoutarde** [NextDom/nextdom-core#123]
Un clic sur le bouton redémarrage affiche cette page. On a un jeetruc qui traine encore et le thème admin lte a sauté.

![screenshot_2018-09-25 dashboard - jeedom](https://user-images.githubusercontent.com/4697568/46005540-bf8b6f80-c0b5-11e8-82e8-2836f6dc24de.png)

**Comment by byackee** [comment]
bug sur ancienne version de nextom
