### ISSUE TITLE
class utils::o2a et utils::a2o ne fonctionnent pas

### ISSUE THREAD

**Issue by byackee** [NextDom/nextdom-core#1238]
**Décrivez le bug**
Le plugin tv samsung utilise les class utils::o2a et utils::a2o, celles ci sont bien présente dans le core mais le plugin n'y accede pas

exrait du code du plugin
		ajax::success(Utils::o2a($communicationStatus));

```
[29-Jul-2019 09:23:12 Europe/Berlin] PHP Fatal error:  Uncaught Error: Class 'Utils' not found in /var/www/nextdomdev/plugins/TvDomSamsung/core/ajax/TvDomSamsung.ajax.php:286
Stack trace:
#0 {main}
thrown in /var/www/nextdomdev/plugins/TvDomSamsung/core/ajax/TvDomSamsung.ajax.php on line 286
```

**Comment by slobberbone** [comment]
Pour moi c'est le plugin qui n'est pas bien codé ...
exrait du code du plugin : 
ajax::success(Utils::o2a($communicationStatus));
doit devenir : 
ajax::success(utils::o2a($communicationStatus));

**Comment by Sylvaner** [comment]
En efet, c'est un problème avec la classe Utils qui ne correspond pas.
Le PHP 5.6 est peut être plus permissif.
