### ISSUE TITLE
PHP notice avec plugin HUE

### ISSUE THREAD

**Issue by byackee** [NextDom/nextdom-core#1245]
**Décrivez le bug**

Le plugin HUE balance 4 PHP notice toutes les secondes, sous jeedom rien. A priori ca n'empeche pas le fonctionnement mais en 1h j'ai un log de 4mo

```
PHP Notice:  Undefined property: stdClass::$effect in /var/www/nextdomdev/plugins/philipsHue/vendor/sqmk/phue/library/Phue/Light.php on line 210

```

**Comment by Sylvaner** [comment]
https://www.jeedom.com/forum/viewtopic.php?t=256&start=1620
