### ISSUE TITLE
problème d'affichage sur le market NextDom.

### ISSUE THREAD

**Issue by homefefeld** [NextDom/nextdom-core#1254]
apres avoir selectioné un plugin en bas de l'ecran,  l'ecran ne remonte pas automatiquement en haut.

**Comment reproduire ?**
Étapes pour reproduire le problème :
1. Aller sur plugin->Gestion&Markets
2. Cliquez sur 'Market Nextom"
3. Faites défiler jusqu'en bas
4. selectionner "Pulse Audio"
-> l'ecran de configuration n'apparait que si on click sur la double fleche en bas a gauche.

**Comment by homefefeld** [comment]
Ceci est aussi un bug 0.3.0.

**Comment by cyrilphoenix71** [comment]
moi l'ecran remonte bien en 0.3.0
