### ISSUE TITLE
BUG : Resultat recherche Market Vide

### ISSUE THREAD

**Issue by Sliver91** [NextDom/nextdom-core#1255]
**Décrivez le bug**
La recherche sur le market Jeedom pour les widget/scenario/script ne fonctionne pas "resultat vide".

**Comment reproduire ?**
Plugin
Gestion & Markets
Jeedom Market
"Sélectionné : Plugin/widget/script/scénario"
Choisir : Widget
Resultat : VIDE

**Screenshots**
https://i.ibb.co/bdT745X/script.png

**Information matérielles**
 - OS : [ex : Debian 9.5]
 - Navigateur : [ex : chrome, safari]
 - Version NextDom : 0.3.0 et oui !!
 - Branche NextDom : master

**Comment by Gis70** [comment]
Salut, 

Ca fonctionne chez moi en 0.3.0,tu as bien renseigné les login et mdp ?

Tu recherches quoi ?

**Comment by Sliver91** [comment]
plusieurs widget 
ah oui tu peu me montrer un imprime ecran de ta recherche de widget dans le market jeedom via Nextdom ? merci

**Comment by Gis70** [comment]
en recherchant alarme 
![image](https://user-images.githubusercontent.com/16589132/62159945-3109ff00-b313-11e9-9b64-b76021362374.png)

**Comment by Gis70** [comment]
Essaie un ctrl + f5

**Comment by Sliver91** [comment]
je reboot nextdom la :o etrange j'ai clear mes cookies..

**Comment by Sliver91** [comment]
et bien oui tu a raison la 0.3.0 corrige ce probleme !

**Comment by therealcorwin** [comment]
Je ferme ton issue @Garry91 vue que ton souci est résolu apparemment.
