### ISSUE TITLE
Bug lors de la création de template de scénario

### ISSUE THREAD

**Issue by vinceg77** [NextDom/nextdom-core#1265]
Lors de la création d'un template de scenario lorsque l'on clique sur le "+" après avoir donné un nom au template une erreur est générée, 

**Comment reproduire ?**
1. Aller dans un scénario
2. 'template'
3. Donner un nom au template dans la textbox
4. cliquer sur l'icone '+'

**Screenshots**
![Capture](https://user-images.githubusercontent.com/51484329/62255172-5fafd480-b3fc-11e9-833c-962343785165.JPG)

**Information matérielles**
 - OS : Debian 9.9
 - Navigateur : chrome
 - Version NextDom : 0.3.0
 - Branche NextDom : master
 - Installé via : paquet deb

error log (chercher : Programmation Volets Bureau.json dans le log pour trouver la ligne concernée)
[http.error.txt](https://github.com/NextDom/nextdom-core/files/3454266/http.error.txt)

**Comment by Gis70** [comment]
ok validé
