### ISSUE TITLE
Restauration via Samba

### ISSUE THREAD

**Issue by vinceg77** [NextDom/nextdom-core#1266]
Lors de la restauration d'un backup distant via Samba le backup distant est bien vu par Nextdom dans les sauvegardes disponibles mais lorsque l'on clique sur 'Restaurer la sélection' en ayant choisi la liste le backup à restaurer un message d'erreur apparaît 'le fichier est introuvable sur le serveur Samba: nomdubackup.tar.gz'

PS : ce n'est pas un problème de droits sur le serveur samba
PS2 : la sauvegarde en samba (sur le même serveur) fonctionne parfaitement

Étapes pour reproduire le problème :
1. Aller dans 'Sauvegardes
2. Sélectionner un backup dans la liste de la partie 'Sauvegardes Samba'
3. Cliquer sur 'Restaurer la sélection'

**Screenshots**
![Restore Samba](https://user-images.githubusercontent.com/51484329/62255591-26786400-b3fe-11e9-8e81-c8b6f6693cb5.gif)

**Information matérielles**
- OS : Debian 9.9
- Navigateur : chrome
- Version NextDom : 0.3.0
- Branche NextDom : master
- Installé via : paquet deb

**Comment by Gis70** [comment]
Toujours présent en 0.5.0 RC1
