### ISSUE TITLE
bug avec "apt install" pour une installation initial (sans backup) 

### ISSUE THREAD

**Issue by homefefeld** [NextDom/nextdom-core#1269]
the script apt d'install se plante si on n'a pas de backup dans /var/lib/nextdom/backup/

Setting up nextdom (0.3.0) ...
ls: cannot access '/tmp/nextdom-backup/backup*': **No such file or directory**
**mv: missing destination file operand after '/var/lib/nextdom/backup/'**

**Comment by Gis70** [comment]
Je clos, je n'ai pas reproduit sur une fresh install debian en 0.5.0 RC1
