### ISSUE TITLE
Plugin Widget : résultat de recherche KO / pas d'image

### ISSUE THREAD

**Issue by Gis70** [NextDom/nextdom-core#1275]
Sur NextDom 0.3.0, dans le plugin widget, les icônes ne sont pas affichés, et la recherche et KO.

Ca marche si on passe par le market et que l'on va dans la rubrique widget

**Comment by vinceg77** [comment]
Chez moi ca semble fonctionner : 
![Capture](https://user-images.githubusercontent.com/51484329/62410444-b4fb0a00-b5e5-11e9-99f7-13badf5fe760.JPG)

**Comment by Gis70** [comment]
Sur le market ? J'ai pas précisé ...

**Comment by vinceg77** [comment]
Ah pardon, j'ai cru que c'était dans le plugin lui même. Effectivement dans le market je n'ai qu'une icone sur 15 qui apparaît correctement !

**Comment by cyrilphoenix71** [comment]
tous fonctionne sous develop, pouvez vous tester ? @Gis70 @vinceg77

**Comment by vinceg77** [comment]
test sous master : 
![Capture](https://user-images.githubusercontent.com/51484329/62413760-e938ef80-b612-11e9-9725-270c94a569e1.JPG)

**Comment by vinceg77** [comment]
![Capture](https://user-images.githubusercontent.com/51484329/62413774-2f8e4e80-b613-11e9-893a-42554826d36e.JPG)

**Comment by Gis70** [comment]
Alors sous develop @cyrilphoenix71 ça marche, j'ai les icônes seulement si j'ai cliqué sur un widget et que la modale du widget s'affiche. Ensuite les images sont chargées, sinon, pas d'icônes. La recherche fonctionne. Par contre le nom de la catégorie n'est pas en adéquation lorsque l'on arrive sur la page d'accueil. Mais ça doit être du ressort du plugin et pas de NextDom ?
