### ISSUE TITLE
Bug Le contenu des commandes disparait

### ISSUE THREAD

**Issue by vinceg77** [NextDom/nextdom-core#1276]
**Décrivez le bug**
Lorsque l'on clique sur une commande existante puis que l'on clique juste après sur le contenu de la textbox/listbox correspondant à cette commande, ce contenu disparaît !

Cela concerne toutes les commandes dans toutes les pages qui contiennent oue ou plusieurs commandes (page scénario / page configuration avancée / plugins / etc...)

Dans les mêmes circonstances dans Jeedom le contenu ne disparaît pas.

Certes il suffit de ne pas cliquer sur la commande elle même avant de cliquer sur la textbox/listbox que l'on souhaite éditer, mais dans la pratique je (suis je le seul ?) clique d'abord souvent sur la commande elle même avant. C'est notamment le cas lorsque l'on essaye de corriger une erreur dans un scénario : pour trouver l'erreur on 'parse' chaque commande en cliquant dessus...

Étapes pour reproduire le problème :
1. Ouvrir une page (scénario par exemple) contenant une ou plusieurs commandes qui contiennent une textbox (exemple une commande 'message') ou une listbox (exemple une commande d'appel de scenario) dont la textbox ou la listbox sont déjà renseignés
2. Cliquer sur la commande elle même (exemple 'message' ou 'scenario')
3. Puis, juste après, cliquer sur la listbox ou la textbox juste en dessous de la commande sur laquelle on vient de cliquer
4. ===> Le contenu de la listbox ou de la textbox disparaît !!!

**Screenshots**
Exemple simple :
![Textboxs](https://user-images.githubusercontent.com/51484329/62411736-16c46f80-b5f8-11e9-84a3-7056389a5a2c.gif)
La meme chose dans Jeedom :
![Textboxs Jeedom](https://user-images.githubusercontent.com/51484329/62411744-33f93e00-b5f8-11e9-9ef1-e0e2bd4a3608.gif)

Deuxième exemple :
![Exemple2](https://user-images.githubusercontent.com/51484329/62411737-188e3300-b5f8-11e9-9783-f5070e3664d1.gif)

Information matérielles

OS : Debian 9.9
Navigateur : chrome
Version NextDom : 0.3.0
Branche NextDom : master
Installé via : paquet deb

**Comment by Gis70** [comment]
Ok validé
