### ISSUE TITLE
Probleme avec le plugin Heliotrope

### ISSUE THREAD

**Issue by vinceg77** [NextDom/nextdom-core#1278]
**Décrivez le bug**
Les commandes des onglets 'Lever du soleil' et 'Coucher du soleil' du plugin Héliotrope ne répondent pas

Étonnamment celles de l'onglet 'Position du soleil' fonctionnent.

Comment reproduire ?
Étapes pour reproduire le problème :

1. Aller dans un équipement Héliotrope
2. Cliquez sur l'onglet onglets 'Lever du soleil' ou 'Coucher du soleil'
3. Cliquer sur le bouton 'tester' de n'importe quelle commande
4. La réponse est vide...

Screenshots
![Capture](https://user-images.githubusercontent.com/51484329/62412949-842ccc00-b609-11e9-8011-502d747726cf.JPG)

Information matérielles

OS : Debian 9.9
Navigateur : chrome
Version NextDom : 0.3.0
Branche NextDom : master
Installé via : paquet deb

[log debug heliotrope.txt](https://github.com/NextDom/nextdom-core/files/3463900/log.debug.heliotrope.txt)
[http.error.txt](https://github.com/NextDom/nextdom-core/files/3463901/http.error.txt)

**Comment by Gis70** [comment]
Salut ça fonctionne chez moi, en 0.3.0 master 
![image](https://user-images.githubusercontent.com/16589132/62415327-3c696d00-b628-11e9-88c6-98195af67961.png)

**Comment by vinceg77** [comment]
M.. c'est seulement chez moi alors.. J'ai arrêté / redémarrer le plugin, rien ...
J'ai plus qu'à désinstaller/réinstaller et reprendre toutes le commandes orphelines générées par l'opération...

Fait ch...

@cyrilphoenix71 tu peux clore dans ce cas, fausse alerte, désolé

**Comment by Gis70** [comment]
Tu as lancé les cron daily ?attend 24h au cas où

**Comment by vinceg77** [comment]
Ca fait plusieurs jours que j'avais constaté le pb, j'ai attendu exprès pour voir.

Mais chez moi les cron sont hourly !!?? (dans la config du plugin en tous cas)...

**Comment by Gis70** [comment]
chez moi aussi cest hourly, mais je crois que l'heure du levé et couché se
faisait à 3h du mat

**Comment by vinceg77** [comment]
ah ok.
Enfin, si qq'un a une idée pour réparer mon plugin sans avoir à tout refaire, je suis preneur !

**Comment by Gis70** [comment]
tu as éssayé de le réinstaller ?

**Comment by vinceg77** [comment]
Non pas encore, je redoute le nbre de commandes orphelines que ca va me faire. Je sais comment remplacer un id de commande par un autre mais faut quand meme aller voir à chaque fois à quelle commande ca correspondait. J'en ai pour 30 mns !

**Comment by Gis70** [comment]
non mais tu réinstalle via le market sans désinstaller

**Comment by vinceg77** [comment]
@Gis70 merci pour le tips
J'ai essayé mais ca marche pas... Pareil les commandes ne répondent rien..
Je vais essayer de générer une nouvelle clé API pour voir...

... non ca marche pas non plus. Je vais quand même attendre le cron au cas où...

EDIT : Mdr.. j'ai ouvert 2 issues en même temps (1 pour le plugin Dark Sky une autre - celle ci - pour héliotrope... Depuis tout à l'heure on parle d'héliotrope, et je corrigeais sur le plugin Dark Sky !!! :smile: :fearful: :sob:
Bon je retente sur le bon plugin cette fois !

... Bon idem, ca marche pas, j'ai reinstallé, vérifié le cron, redemarré, toujours que l'onglet 'position du soleil' qui fonctionne

**Comment by Sylvaner** [comment]
Peux-tu taper cette commande en ssh après avoir essayé d'activer quelques commandes : 
```
tail -n 200 /var/log/nextdom/http.error
```
?

**Comment by vinceg77** [comment]
> Peux-tu taper cette commande en ssh après avoir essayé d'activer quelques commandes :
> 
> ```
> tail -n 200 /var/log/nextdom/http.error
> ```
> 
> ?

Merci @Sylvaner pour ton aide.
Le tail n'affiche aucune erreur de la part d'heliotrope, mais juste un pb de commande espeasy dont le nom serait vide que je traîne depuis des mois sous jeedom comme sous nextdom

Par contre il m'a prit l'idée de créer un nouvel équipement héliotrope et en fait, ca fonctionne pas : lorsque je tente de sauvegarder le nouvel équipement : "Erreur : Call to a member function execCmd() on boolean".

Et dans le http.error : 
[04-Aug-2019 12:06:06 Europe/Berlin] PHP Notice:  Undefined offset: 1 in /usr/share/nextdom/plugins/heliotrope/core/class/heliotrope.class.php on line 291
[04-Aug-2019 12:06:06 Europe/Berlin] PHP Warning:  deg2rad() expects parameter 1 to be float, string given in /usr/share/nextdom/plugins/heliotrope/core/class/heliotrope.class.php on line 276
[04-Aug-2019 12:06:06 Europe/Berlin] PHP Warning:  deg2rad() expects parameter 1 to be float, string given in /usr/share/nextdom/plugins/heliotrope/core/class/heliotrope.class.php on line 276
[04-Aug-2019 12:06:06 Europe/Berlin] PHP Warning:  deg2rad() expects parameter 1 to be float, string given in /usr/share/nextdom/plugins/heliotrope/core/class/heliotrope.class.php on line 277
[04-Aug-2019 12:06:06 Europe/Berlin] PHP Warning:  deg2rad() expects parameter 1 to be float, string given in /usr/share/nextdom/plugins/heliotrope/core/class/heliotrope.class.php on line 278

Une piste ?
