### ISSUE TITLE
Bugs dans la recherche de widget

### ISSUE THREAD

**Issue by vinceg77** [NextDom/nextdom-core#1283]
**Décrivez le bug**
La recherche d'un widget n'affiche pas la même chose selon que l'on passe par plugin widget/market ou par plugin Gestion&Markets/jeedom market/widget :

1. A l’intérieur du plugin Widget, la recherche bug si après avoir saisi le nom du widget recherché dans la barre de recherche ce qui semble avoir pour effet de filtrer les résultats en fonction de la saisie mais aucun résultat n'est affiché. Il faut cliquer sur la loupe.

2. La recherche d'un widget via le plugin Gestion&Markets/jeedom market/widget semble avoir pour effet de filtrer les résultats en fonction de la saisie mais aucun résultat n'est affiché alors que le bandeau affiche '2 widgets disponibles dans cette catégorie [...]'.

3. Depuis le plugin Widget, la recherche pour un même mot clé n'affiche pas les mêmes résultats que celle effectuée depuis Jeedom.

**Comment reproduire ?**
Étapes pour reproduire le problème :
1. Aller dans plugin/widget
2. Cliquez sur ''market'
3. dans 'Rechercher' taper par exemple "ToggleSwitch_IMG"
      ===> la saisie semble agir comme un filtre, mais aucun résultat n’apparaît : 
![Recherche avec entrée Nextdom](https://user-images.githubusercontent.com/51484329/62472845-e3244980-b79f-11e9-8db5-a88528393a3a.JPG)

4. appuyer sur la loupe
      ===> le résultat apparaît bien :
![Recherche Nextdom via widget](https://user-images.githubusercontent.com/51484329/62472897-fd5e2780-b79f-11e9-9545-ebfd86feeb4b.JPG)

5. Aller dans le plugin Gestion&Markets/jeedom market/widget
6. Cliquer sur 'Un Nom ?' et saisir 'ToggleSwitch_IMG' dans la modale puis cliquer sur OK
      ===> Aucun résultat n’apparaît :
![Recherche Nextdom via market](https://user-images.githubusercontent.com/51484329/62473152-79586f80-b7a0-11e9-9b31-54765fa73be6.JPG)

Depuis Jeedom, la recherche sur du même widget "ToggleSwitch_IMG" affiche en plus sa version mobile :
![Recherche Jeedom via widget](https://user-images.githubusercontent.com/51484329/62473232-a147d300-b7a0-11e9-987a-bc692158fa1d.JPG)

**Information matérielles**
OS : Debian 9.9
Navigateur : chrome
Version NextDom : 0.3.0
Branche NextDom : master
Installé via : paquet deb

**Comment by Gis70** [comment]
#1275

**Comment by Gis70** [comment]
ok  sur e8d6b0770e60d9bd3fbb375f4b8f65f132e8a86f
