### ISSUE TITLE
Restauration sur une installation existante

### ISSUE THREAD

**Issue by Sylvaner** [NextDom/nextdom-core#1284]
**Décrivez le bug**
Lors d'une restauration sur dans un instance déjà fonctionnel, les répertoire des plugins sont souvent mal copiés car non vide.
Il faudrait sans doute remplacer le "mv" par un "cp -fr"

**Comment reproduire ?**
Restaurer 2 fois la même sauvegarde

**Comment by vinceg77** [comment]
+1

**Comment by slobberbone** [comment]
Fixé dans #1176
