### ISSUE TITLE
Erreur restauration Jeedom : error while checking system consistency

### ISSUE THREAD

**Issue by ghost** [NextDom/nextdom-core#1292]
En restaurant un Jeedom 3.1.7, j'ai l'erreur suivante :
chechking system consistency......  Failure
>> *** ERROR *** error while checking system consistency: [MySQL] Error code : 42S22 (1054). Unknown column 'el.generic_type' in 'field list'  : SELECT `el`.`name`, `el`.`generic_type`, `el`.`logicalId`, `el`.`eqType_name`, `el`.`configuration`, `el`.`isVisible`, `el`.`isEnable`, `el`.`timeout`, `el`.`category`, `el`.`display`, `el`.`order`, `el`.`comment`, `el`.`tags`, `el`.`id`, `el`.`eqReal_id`, `el`.`object_id`
FROM `eqLogic` el
LEFT JOIN object ob ON el.object_id = ob.id ORDER BY ob.name, el.name
PHP Notice:  Array to string conversion in /usr/share/nextdom/src/Helpers/Utils.php on line 412
PHP Notice:  Array to string conversion in /usr/share/nextdom/src/Helpers/Utils.php on line 412
PHP Notice:  Array to string conversion in /usr/share/nextdom/src/Helpers/ConsoleHelper.php on line 100
>> *** TRACE *** Array
starting nextdom system......  OK
*************** Closing with error ***************
[ / Restore Backup Process ]
column 'el.generic_type' in 'field list'  : SELECT `el`.`name`, `el`.`generic_type`, `el`.`logicalId`, `el`.`eqType_name`, `el`.`configuration`, `el`.`isVisible`, `el`.`isEnable`, `el`.`timeout`, `el`.`category`, `el`.`display`, `el`.`order`, `el`.`comment`, `el`.`tags`, `el`.`id`, `el`.`eqReal_id`, `el`.`object_id`                 FROM `eqLogic` el                 LEFT JOIN object ob ON el.object_id = ob.id ORDER BY ob.name, el.name

**Comment by ghost** [comment]
Ca blind de warning la base ;-)
150 000 enregistrement  en 10 jours
ce | Erreur sur ecodevice::pull() : NextDom\Exceptions\CoreException Object ( [message:protected] => [MySQL] Error code : 42S22 (1054). Unknown column 'generic_type' in 'field list' : SELECT `name`, `generic_type`, `logicalId`, `eqType_name`, `configuration`, `isVisible`, `isEnable`, `timeout`, `category`, `display`, `order`, `comment`, `tags`, `id`, `eqReal_id`, `object_id` FROM `eqLogic` WHERE eqType_name = :eqType_name AND configuration LIKE :configuration ORDER BY name [string:Exception:private] => [code:protected] => 0 [file:protected] => /usr/share/nextdom/src/Helpers/DBHelper.php [line:protected] => 217 [trace:Exception:private] => Array ( [0] => Array ( [file] => /usr/share/nextdom/src/Helpers/DBHelper.php [line] => 125 [function] => Prepare [class] => NextDom\Helpers\DBHelper [type] => :: [args] => Array ( [0] => SELECT `name`, `generic_type`, `logicalId`, `eqType_name`, `configuration`, `isVisible`, `isEnable`, `timeout`, `category`, `display`, `order`, `comment`, `tags`, `id`, `eqReal_id`, `object_id` FROM `eqLogic` WHERE eqType_name = :eqType_name AND configuration LIKE :configuration ORDER BY name [1] => Array ( [eqType_name] => ecodevice [configuration] => %"type":"carte"% ) [2] => 1 [3] => 8 [4] => NextDom\Model\Entity\EqLogic ) ) [1] => Array ( [file] => /usr/share/nextdom/src/Managers/EqLogicManager.php [line] => 240 [function] => getAllObjects [class] => NextDom\Helpers\DBHelper [type] => :: [args] => Array ( [0] => SELECT `name`, `generic_type`, `logicalId`, `eqType_name`, `configuration`, `isVisible`, `isEnable`, `timeout`, `category`, `display`, `order`, `comment`, `tags`, `id`, `eqReal_id`, `object_id` FROM `eqLogic` WHERE eqType_name = :eqType_name AND configuration LIKE :configuration ORDER BY name [1] => Array ( [eqType_name] => ecodevice [configuration] => %"type":"carte"% ) [2] => NextDom\Model\Entity\EqLogic ) ) [2] => Array ( [file] => /usr/share/nextdom/core/class/eqLogic.class.php [line] => 70 [function] => byTypeAndSearhConfiguration [class] => NextDom\Managers\EqLogicManager [type] => :: [args] => Array ( [0] => ecodevice [1] => "type":"carte" ) ) [3] => Array ( [file] => /usr/share/nextdom/plugins/ecodevice/core/class/ecodevice.class.php [line] => 79 [function] => byTypeAndSearhConfiguration [class] => eqLogic [type] => :: [args] => Array ( [0] => ecodevice [1] => "type":"carte" ) ) [4] => Array ( [file] => /usr/share/nextdom/src/Api/start_cron.php [line] => 109 [function] => pull [class] => ecodevice [type] => :: [args] => Array ( ) ) [5] => Array ( [file] => /usr/share/nextdom/src/Api/start_cron.php [line] => 219 [function] => NextDom\startCronTargetMethod [args] => Array ( [0] => NextDom\Model\Entity\Cron Object ( [enable:protected] => 1 [class:protected] => ecodevice [function:protected] => pull [schedule:protected] => * * * * * * [timeout:protected] => 60 [deamon:protected] => 0 [deamonSleepTime:protected] => 1 [option:protected] => [once:protected] => 0 [id:protected] => 1514 [_changed:protected] => ) [1] => [2] => 1566848822 ) ) [6] => Array ( [file] => /usr/share/nextdom/src/Api/start_cron.php [line] => 295 [function] => NextDom\startSingleCron [args] => Array ( [0] => 1514 ) ) ) [previous:Exception:private] => )
-- | --

**Comment by slobberbone** [comment]
La vraie question est doit-on accepter l'import d'un backup jeedom plus ancien que 3.2.X ?

**Comment by ghost** [comment]
Je pense que c'est lié à mon plugin ipx800...
Mais ta question est pertinente
