### ISSUE TITLE
Incohérance version dans la page de mise à jour

### ISSUE THREAD

**Issue by AgP42** [NextDom/nextdom-core#1293]
**Décrivez le bug**
Dans la page de mise à jour, la version indiquée est celle de Jeedom (en l'occurence ici c'est le core de la sauvegarde que j'ai installée), et non celle de NextDom

**Comment reproduire ?**
Étapes pour reproduire le problème :
1. Installer une sauvegarde Jeedom
2. Aller sur la page d'update

**Screenshots**
![update](https://nsa40.casimages.com/img/2019/08/14/190814013046451377.png)

**Information matérielles**
 - OS : Debian 9
 - Navigateur : all
 - Version NextDom : 0.3.0
 - Branche NextDom : master
 - Installé via : paquet deb

**Labels**

**Comment by Sylvaner** [comment]
ah oui, ça va être sympa à gérer ça :) Merci

**Comment by slobberbone** [comment]
Fixed in c13e824c99f017c733118561c95093a51351fad2
