### ISSUE TITLE
Ajout Plugin par zip impossible

### ISSUE THREAD

**Issue by TekiStone** [NextDom/nextdom-core#1295]
**Décrivez le bug**
Il semble impossible de rajouter un plugin depuis un ZIP situer sur le PC depuis l'interface

**Comment reproduire ?**
Prérequis :
Avoir activé le service de fichier depuis "Expert" => "Administration & Réglages" => "Services" => "Fichier"

Étapes pour reproduire le problème :
1. Aller sur "plugins" puis "Gestion & Markets"
2. Cliquez sur "Autre Source"
3. Sélectionner "Fichier" dans "Type de source"
4. Saisir un Id logique
5. Sélectionner le fichier ZIP du plugin depuis le PC
6. Valider l'ajout

Un message dit que tout c'est bien passé mais le plugin n'est pas présent dans la liste (actif/inactif) 
Il apparaît dans le "module" de mise à jour mais sans information puisque rien n'est présent sur le serveur

**Screenshots**

**Information matérielles**
 - OS : Debian 9 sur Raspberry pi 3 B+
 - Navigateur : Chrome 76
 - Version NextDom : 0.3.0
 - Branche NextDom : master
 - Installé via : paquet deb

**Labels**
Ajouter à droite de cette issue le label Component_XXX ciblant le composant lié à cette issue...

**Comment by Sylvaner** [comment]
Merci, c'est corrigé, à tester :)

**Comment by Gis70** [comment]
ok validé
