### ISSUE TITLE
Maj Fantôme Core

### ISSUE THREAD

**Issue by TekiStone** [NextDom/nextdom-core#1301]
**Décrivez le bug**
Une mise à jour est disponible pour le core mais la version est incorrecte.

**Comment reproduire ?**
Étapes pour reproduire le problème :
1. "Inconnue", NextDom m'a indiqué qu'une MaJ était présente
2. Cliquez sur 'Expert'
3. Cliquez sur 'Administration & Réglages'
3. Le core a une MaJ dispo, la version affichée dans la tuile est **404: Not Found**

**Screenshots**
![image](https://user-images.githubusercontent.com/35001669/63249917-c2adc200-c26a-11e9-96f4-7b7a7dc32c40.png)

Ma version actuelle 
![image](https://user-images.githubusercontent.com/35001669/63249938-ce00ed80-c26a-11e9-9d4f-430597da7182.png)

**Information matérielles**
 - OS : Debian 9 sur Raspberry pi 3 B+
 - Navigateur : Chrome 76
 - Version NextDom : 0.3.0
 - Branche NextDom : master
 - Installé via : paquet deb

**Labels**
Ajouter à droite de cette issue le label Component_XXX ciblant le composant lié à cette issue...

**Comment by TekiStone** [comment]
update : Ce matin j'ai retrouvé certaines informations dans les cadres : 
![image](https://user-images.githubusercontent.com/35001669/64322119-3b7a8100-cfc2-11e9-81a9-14b8feb0b7b0.png)

Mais j'ai un décalage (je ne sais pas si c'est lié)
La version en bas de l'interface web : 
![image](https://user-images.githubusercontent.com/35001669/64322194-6369e480-cfc2-11e9-9990-a737b7d6eb9a.png)

Et dans ma console :
![image](https://user-images.githubusercontent.com/35001669/64322259-88f6ee00-cfc2-11e9-8054-3293e2ad12e8.png)

(Si besoin je suis dispo pour des tests ou autre)

**Comment by Sylvaner** [comment]
Normalement c'est réglé dans la dernier develop donc en RC1 ce soir

**Comment by Esso1-jeedom** [comment]
oui
![image](https://user-images.githubusercontent.com/40739563/65631658-42e8e500-dfd8-11e9-9567-1f2089adc36b.png)
