### ISSUE TITLE
Scénario non visible dans le dashboard

### ISSUE THREAD

**Issue by Adrianos712** [NextDom/nextdom-core#1304]
**Décrivez le bug**
Les scénario n'apparaissent pas dans le dashboard

**Comment reproduire ?**
Étapes pour reproduire le problème :
1. créer un scénario avec la case "visible" activée  et appartenant à un objet
2. aller sur l'objet en question, il n'apparaît pas

**Information matérielles**
 - OS : Debian 9.9
 - Navigateur : Firefox
 - Version NextDom : 0.3.0
 - Branche NextDom : master
 - Installé via : paquet deb

**Comment by Sylvaner** [comment]
En effet, nous les avions retiré. Mais est-ce vraiment utile ? Car nous essayons d'alléger le dashboard qui est... chargé pour certains

**Comment by Gis70** [comment]
Pour ma part je m'en fiche qu'il y soient pas. Au pire on peut faire un
virtuel. Je préfère un dash allégé.

Le sam. 7 sept. 2019 à 11:12, Sylvain Dangin <notifications@github.com> a
écrit :

**Comment by Adrianos712** [comment]
Mon besoin est de pouvoir activer/désactiver le scénar depuis le dashboard, pas sur qu'un virtuel puisse faire ça.
Si on veut alléger le dashboard, il suffit juste de décocher "visible" dans le scénario, non ?

**Comment by Sylvaner** [comment]
On va organiser un vote pour ça je pense :)

**Comment by Sylvaner** [comment]
https://github.com/NextDom/nextdom-core/issues/1344
