### ISSUE TITLE
Possibilité de desactiver un scénario sur la version mobile

### ISSUE THREAD

**Issue by Adrianos712** [NextDom/nextdom-core#1305]
**Décrivez ce que vous souhaitez**
Possibilité dans l'onglet scénario de la partie mobile d'activer/desactiver les scénarii.
Attention à ne pas mettre les boutons trop proche du déclenchement :-)

**Comment by Sylvaner** [comment]
J'ai du mal à comprendre le besoin, pourquoi tu fais ça ? :)

**Comment by Adrianos712** [comment]
Sur l'UI mobile, on ne peut pas voir l'état actif/inactif des scénarii, et encore moins le modifier.

Mon besoin est le suivant :
J'ai un scénar qui ouvre mes volets les jours de semaine pour me reveiller, puis réveiller mes enfants.
Les jours fériés où quand y'a pas école des fois j'oublie de désactiver, alors quand ça s'ouvre, je dois en speed, d'un oeil sans lunette et sans trop me réveiller désactiver l'ouverture chez mes gamins pour pas ruiner ma grace mat ;-)

Alors y'a peut etre moyen de gérer ça plus intelligemment :)

**Comment by edgd1er** [comment]
Bjr, le plugin DayInfo donne le status week end, vacances, je les utilises pour décaler l ouverture des volets a 9h. Il a une dependance avec un autre plugin de lunarok de gps, mais tu peux l utiliser sans cle api google en entrant directement des coordonnées gps. Si ca peut aider

**Comment by Sylvaner** [comment]
Edgd1er, l'homme au bon plugin :)
@adrianos712, penses-tu que cette solution pourrait convenir ?

**Comment by CyrilCharlier** [comment]
@Sylvaner 

Si j'ai bien compris : Ajouter un bouton sur cette vue pour permettre de désactiver un scénario 
![image](https://user-images.githubusercontent.com/11455745/67157160-b1e00200-f328-11e9-909c-07f57bfc5eba.png)

merci !

**Comment by Sylvaner** [comment]
C'est fait
