### ISSUE TITLE
0.3.1 Page équipements KO

### ISSUE THREAD

**Issue by Gis70** [NextDom/nextdom-core#1330]
[06-Sep-2019 21:47:04 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to a member function getStatus() on null in /var/www/html/src/Controller/Diagnostic/EqAnalyzeController.php:59
Stack trace:
#0 [internal function]: NextDom\Controller\Diagnostic\EqAnalyzeController::get(Array)
#1 /var/www/html/src/Helpers/PrepareView.php(378): call_user_func_array('NextDom\Control...', Array)
#2 /var/www/html/src/Helpers/PrepareView.php(430): NextDom\Helpers\PrepareView->getContentFromControllerRouteData(Object(Symfony\Component\Routing\Route), Array)
#3 /var/www/html/src/Helpers/Router.php(145): NextDom\Helpers\PrepareView->showContentByAjax()
#4 /var/www/html/src/Helpers/Router.php(93): NextDom\Helpers\Router->desktopView()
#5 /var/www/html/index.php(71): NextDom\Helpers\Router->show()

La page est KO après un restore, erreur 500

**Comment by slobberbone** [comment]
@Gis70 peux-tu me transmettre ton backup stp ? (via discord en privé)

**Comment by Esso1-jeedom** [comment]
pour moi ca fonctionne tjrs..
meme aprés restore etc.

**Comment by Gis70** [comment]
Hello 

> rm -fr /var/lib/nextdom/cache/twig/*

 a résolu le pb

**Comment by slobberbone** [comment]
Ca veut dire qu'il faut rajouter ça après un restore backup ! Je le rouvre pour le faire ! Merci !
