### ISSUE TITLE
Sondage sur la fonctionnalité d'accès aux scénarios sur le dashboard

### ISSUE THREAD

**Issue by Sylvaner** [NextDom/nextdom-core#1344]
Jeedom a intégré il y a quelques versions la possibilité de contrôler les scénarios sur le dashboard.
Nous n'avions à l'époque pas intégré cette fonctionnalité.

Aujourd'hui @Adrianos712 lance le débat (à juste titre).

Donc êtes-vous pour intégrer la possibilité de contrôler les scénarios dans le dashboard ?
[![](https://api.gh-polls.com/poll/01DMD4YDQRNC8TMQSED61633H4/Oui%20il%20faut%20absolument)](https://api.gh-polls.com/poll/01DMD4YDQRNC8TMQSED61633H4/Oui%20il%20faut%20absolument/vote)
[![](https://api.gh-polls.com/poll/01DMD4YDQRNC8TMQSED61633H4/Oui%2C%20pourquoi%20pas)](https://api.gh-polls.com/poll/01DMD4YDQRNC8TMQSED61633H4/Oui%2C%20pourquoi%20pas/vote)
[![](https://api.gh-polls.com/poll/01DMD4YDQRNC8TMQSED61633H4/Non%2C%20j'suis%20pas%20convaincu)](https://api.gh-polls.com/poll/01DMD4YDQRNC8TMQSED61633H4/Non%2C%20j'suis%20pas%20convaincu/vote)
[![](https://api.gh-polls.com/poll/01DMD4YDQRNC8TMQSED61633H4/Non%2C%20%C3%A7a%20sert%20%C3%A0%20rien)](https://api.gh-polls.com/poll/01DMD4YDQRNC8TMQSED61633H4/Non%2C%20%C3%A7a%20sert%20%C3%A0%20rien/vote)
[![](https://api.gh-polls.com/poll/01DMD4YDQRNC8TMQSED61633H4/Oui%2C%20mais%20sous%20une%20autre%20forme%20(%C3%A0%20proposer%20en%20message))](https://api.gh-polls.com/poll/01DMD4YDQRNC8TMQSED61633H4/Oui%2C%20mais%20sous%20une%20autre%20forme%20(%C3%A0%20proposer%20en%20message)/vote)

**Comment by cyrilphoenix71** [comment]
Je vous propose un truc comme ca :
![image](https://user-images.githubusercontent.com/18350629/64603196-49fcda00-d3c0-11e9-81d2-2c71f65b7c13.png)

**Comment by Adrianos712** [comment]
Ce qui est important pour moi c'est :
- de pouvoir afficher dans une tuile l'état actif/inactif du scénar
- de pouvoir les activer / désactiver simplement et depuis l'UI mobile
Ce que tu proposes est super joli, mais si on doit naviguer, autant mettre un lien direct vers le "résumé scénario"
