### ISSUE TITLE
Remplacement de jeedom dans le SQL

### ISSUE THREAD

**Issue by Sylvaner** [NextDom/nextdom-core#1345]
A la restauration, jeedom est remplacé par nextdom.
Il faut faire quelque chose de plus ciblé car cela pose problème dans plusieurs cas.

**Comment by slobberbone** [comment]
Il faudrait lister ce qu'on veut modifier ...

- BDD (quels champs)
- Fichier de config (lesquels)
- ??

**Comment by slobberbone** [comment]
Alors j'ai regardé, dans un backup voilà ce que je trouve : 
![Sélection_198](https://user-images.githubusercontent.com/3833875/64782733-40ad7200-d566-11e9-97e2-644166ee7467.png)

Donc je vais laisser un sed avant import, juste pour le nom de la bdd et l'utilisateur (sauf si on fait djéà, ce qui devrait être le cas vu qu'on utilise nextdomdev comme user dans certains cas ...)

Ensuite en migration je vais : 
- Cmd et eqLogic
-- ne rien faire , jeedom fait parti des noms des commandes
- Config
-- modifier : `'core','jeedom::` par `'core','nextdom::`
-- modifier `icon jeedom-` par `icon nextdom-`
- Crons
-- modifier la class `jeedom` par `nextdom`
- Update
-- modifier la ligne `(7,'core','jeedom','jeedom','3.2.11','3.2.11','default','ok'` en conséquence 
- User
-- ne rien faire : il s'agit d'un nom de user : jeedom_support
