### ISSUE TITLE
maj par nextdom

### ISSUE THREAD

**Issue by Esso1-jeedom** [NextDom/nextdom-core#1353]
en passant par la MAJ de nextdom.

cela fonctionne mais le tag n'est pas le bon  
en V 0.4.0
en image

![image](https://user-images.githubusercontent.com/40739563/64804295-d6f58e00-d58e-11e9-90f5-be126edc0bbd.png)

**Comment by Sylvaner** [comment]
```
mysql -u root nextdom -e "UPDATE \`update\` SET source = 'apt' WHERE \`type\` = 'core'"
```
Sur les anciennes installations, le type de mise à jour est fixé à github et ne va donc pas mettre à jour

**Comment by slobberbone** [comment]
Est-ce que je tente de mettre ça dans une migration ? je teste au préalable si nextdom est isntallé en .deb @Sylvaner ?

**Comment by Esso1-jeedom** [comment]
cela fonctionne sur la versions deb . 5.0
![image](https://user-images.githubusercontent.com/40739563/65631591-251b8000-dfd8-11e9-9d35-f08c2075083d.png)
