### ISSUE TITLE
bug plugin WIDGET

### ISSUE THREAD

**Issue by Esso1-jeedom** [NextDom/nextdom-core#1367]
les boutons ne fonctionnent pas
![image](https://user-images.githubusercontent.com/40739563/65013397-48c93100-d91b-11e9-8f8e-c0a4bed683c9.png)

**Comment by titrax35** [comment]
Pour corriger le pb en attendant :
- Télécharger le fichier jwerty.js et le mettre dans plugins/widget/3rdparty (https://raw.githubusercontent.com/keithamus/jwerty/master/jwerty.js)

- Modifier le fichier `nano /usr/share/nextdom/plugins/widget/desktop/php/widget.php`
    et rajouter

```
<script src="/plugins/widget/3rdparty/snap.svg-min.js"></script>
<script src="/plugins/widget/3rdparty/jwerty.js"></script>
```

a l extérieur des  

`<?php ... ?>`

(au dessus de `<!--script src="3rdparty/snap.svg/snap.svg-min.js"></script-->`)

**Comment by Esso1-jeedom** [comment]
c corriger en develop

**Comment by Esso1-jeedom** [comment]
bon j'ai du dire une boulette  c pas corrigé

**Comment by Sylvaner** [comment]
Euh si c'est corrigé :),

Tu as bien fait un gen_assets ? : https://github.com/NextDom/nextdom-core/commit/2cede439a9978eca86577905fe9d46e74b6eab4a

**Comment by Esso1-jeedom** [comment]
oui
