### ISSUE TITLE
Service apache non reconfiguré lors du postinst

### ISSUE THREAD

**Issue by slobberbone** [NextDom/nextdom-core#1380]
Le postinst modifie la configuration apache mais ne recharge pas la configuration pour le service

**Comment by Astral0** [comment]
C'est devenu le bordel ce postinst :(
Il y a 3 endroits où l'on modifie la configuration Apache, alors qu'il y a une routine pour ca : step_nextdom_apache_php() 

D'autre part, on relance bien la conf à la fin de cette routine : 
```
  service apache2 restart >> ${DEBUG} 2>&1 || {
    service apache2 restart >> ${DEBUG} 2>&1 || {
      print_error "unable to restart apache2"
    }
  }
```
sauf que moi j'avais mis un temps d'attente entre ces commandes, pour laisser le temps aux filesystem lent (par ex. Docker) de terminer l'écriture des fichiers de conf.C Quelqu'un a fait sauté ce timing et a décrété que 2 c'était mieux que 3 essais :)
