### ISSUE TITLE
Log Cron_execution rempli à outrance

### ISSUE THREAD

**Issue by slobberbone** [NextDom/nextdom-core#1385]
Le ficiher de log cron_execution est rempli d'un warning concernant une fonction deprecated sans tenir compte du niveau de log.
Cette erreur à lieu 2 fois par seconde ...
`This method is deprecated. Use getEqType'`

**Comment by Gis70** [comment]
@slobberbone  tu peux pas faire qqch pr ça aussi : 
![image](https://user-images.githubusercontent.com/16589132/66005700-8944b500-e4ac-11e9-81df-13fc45b33bb8.png)

**Comment by slobberbone** [comment]
En effet ...

**Comment by slobberbone** [comment]
A priori c'est dû à un plugin SuiviConso qui essaie de se connecter sans authentification ...
