### ISSUE TITLE
Notification z-index recouverte

### ISSUE THREAD

**Issue by ColonelMoutarde** [NextDom/nextdom-core#1393]
**Décrivez le bug**
Le z-index des notification n'est pas bon. la barre d'action la recouvre.
**Comment reproduire ?**
Étapes pour reproduire le problème :
1. Aller '/index.php?v=d&p=health'
2. Sauvegarder les valeurs d'un plugin

**Screenshots**

![Screenshot_2019-10-06 Health - NextDom](https://user-images.githubusercontent.com/4697568/66271510-fc5c7b80-e85e-11e9-9f8f-e6d9d1272776.png)
**Information matérielles**
 - OS :  Debian 9.5 
 - Navigateur : firtefox
 - Version NextDom : [ex : 0.4.1]
 - Branche NextDom : [ex : master]
 - Installé via :  deb

**Comment by CyrilCharlier** [comment]
Le messages sont aussi cachés dans la configuration des plugins : 
Lors de la configuration d'un plugin, les messages d'erreurs ou d'informations des plugins sont masqués par la barre de retour à la liste des plugins
