### ISSUE TITLE
Version Mobile via Menu KO

### ISSUE THREAD

**Issue by CyrilCharlier** [NextDom/nextdom-core#1402]
**Décrivez le bug**
Sur une fresh installe, si je vais via le menu sur "Version Mobile", j'arrive sur une page 404.

**Comment reproduire ?**
Étapes pour reproduire le problème :
1. Réaliser une fresh install
2. Aller sur l'entrée de menu "Version Mobile"

**Screenshots**
![image](https://user-images.githubusercontent.com/11455745/66513360-346ff280-eadb-11e9-8307-8f3901ba5e10.png)

**Information matérielles**
 - OS : Debian 10
 - Navigateur : Chrome
 - Version NextDom : 0.5-RC3
 - Branche NextDom : develop
 - Installé via : deb

**Comment by Esso1-jeedom** [comment]
on n'est pas compatible debian 10

**Comment by perarem** [comment]
Même symptôme sous debian 9.

**Comment by Gis70** [comment]
Bonsoir. Pour l'instant je ne suis pas sûr que le paquet nextdom-mobile
soit créé. Vous pouvez trouver sur le dépôt github NextDom la version
mobile compilée. Il y a juste à faire un git clone dans un dossier nommé
mobile.

**Comment by CyrilCharlier** [comment]
@Gis70 effectivement, c'est ce que laissait supposé Slob

**Comment by Gis70** [comment]
VOilà : `cd /var/www/html
git clone https://github.com/NextDom/nextdom-mobile-dist mobile`

**Comment by Gis70** [comment]
ok, plus de menu si le paquet mobile n'est pas installé
