### ISSUE TITLE
page 404 : Retour sur mobile si on vient du desktop

### ISSUE THREAD

**Issue by CyrilCharlier** [NextDom/nextdom-core#1403]
**Décrivez le bug**
Version Desktop, si on prend "Version mobile", on arrive sur une page 404 dont le bouton retour renvoi sur la page "index" du mobile au lieu de renvoyer sur le desktop

**Comment reproduire ?**
Étapes pour reproduire le problème :
1. Depuis le desktop, cliquer sur version mobile
2. voir le lien de la page 404

**Screenshots**
lien de renvoi : http://IP_NEXTDOM/mobile/index.php?v=d&p=dashboard

**Information matérielles**
 - OS : Debian 10
 - Navigateur : Chrome
 - Version NextDom : 0.5-RC3
 - Branche NextDom :develop
 - Installé via :deb

**Comment by iWils** [comment]
Bonsoir,
Problème corrigé en faisant la commande suivante:

`git clone https://github.com/NextDom/nextdom-mobile-dist /usr/share/nextdom/mobile`
