### ISSUE TITLE
restart d'un service non installé fait planter l'installation

### ISSUE THREAD

**Issue by edgd1er** [NextDom/nextdom-core#1411]
https://github.com/NextDom/nextdom-core/blob/6a794076c112fdd4c80239e4b67f35f015abe547/install/postinst#L701

**Décrivez le bug**
arrêt de l'installation (postinst) a cause de la ligne 701: service mysql start

**Comment reproduire ?**
Étapes pour reproduire le problème :
1. installer une vm sans mysql server (parceque la bdd sera ailleurs) ou son dockerfile préféré (toujours sans bdd)
2. lancer postinst en indiquant une bdd exterieur a la VM ou pas, le script d'install s'en fout
3. attendre 3 secondes

**Logs**
mysql unrecognized service

arrêt de l'installation grâce au set -e qui stoppe l’exécution à la première erreur.

**solution**
* supprimer le set -e ( pas conseillé)
* vérifier que le service existe avant de le redémarrer, par exemple:

```
step_nextdom_mysql_configuration() && service mysql start
```
ou 

```
  service mysql status 2>&1 >>${DEBUG}
  isService=$?
  if [ -f /etc/init.d/mysql -a ${isService} -gt 0 ]; then
    print_log_ok "mysql service locally"
    blablabla truc a la con avec mysql
  fi
````

PS: pour docker, je vire tout les services/systemctl <action> nomduservice
PS2: pourquoi faire un restart d'un service qui sera modifié et redémarré par la suite ?

**Information matérielles**
 - OS : Tous
 - Navigateur :N/A
 - Version NextDom : 0.5.0-RC4
 - Branche NextDom : release
 - Installé via : git clone

**Comment by slobberbone** [comment]
Salut @edgd1er en effet mais on a eu beaucoup de soucis récemment avec toute cette partie... On a un chantier dessus en 0.6.0 je t'invite à me recontacter si tu veux bien !

**Comment by edgd1er** [comment]
Salut @slobberbone,

beaucoup de soucis, tu peux développer parce que je teste régulièrement l'install docker dans la branche master et des releases (restore d'un backup jeedom + affichages des elements + install des plugins et dépendances). Je n'ai pas "trop" eu de problèmes jusqu’à maintenant, tant que mysql est considéré comme un élément optionnel et testé avant action.

PS: les images rpi et amd64 de docker sont fonctionnelles (je ne l'utilise pas encore en prod, mais je met en place un cluster k8 et swarm pour me former à swarm et découvrir un peu plus, ce que vous mettre en place ;)

https://cloud.docker.com/u/edgd1er/repository/docker/edgd1er/nextdom-web

**Comment by Sylvaner** [comment]
Bonjour,

Le soucis vient je pense du fait qu'il n'y ai pas mysql d'installé.
Le problème est qu'aujourd'hui, nous avons en effet des soucis car le postinst doit gérer des cas complètement improbable et que forcément cela pose des problèmes.

De plus ces cas amène une compléxité à ce script qui rend son maintien... complexe.

**Comment by slobberbone** [comment]
La réécriture du postinst découpé en plusieurs scripts devrait simplifier l'installation de NextDom en .deb et permettre l'installation sans encombre en .git tout en permerttant à tous de paramettrer comme vous le souhaitez l'appli. Cf : https://github.com/NextDom/nextdom-core/issues/1459
