### ISSUE TITLE
Erreurs à la restauration

### ISSUE THREAD

**Issue by Sylvaner** [NextDom/nextdom-core#1415]
Quelques erreurs lors de la tentative de restauration. Il faut tester les répertoires.

![Capture d’écran 2019-10-14 à 23 54 13](https://user-images.githubusercontent.com/957104/66785653-2c9abe80-eede-11e9-87cf-bcf5b755629c.jpg)

**Comment by macros83** [comment]
Même problème, je viens de réinstaller mon raspberry avec Nextdom et j'ai une erreur semblable a la restauration, aurais-tu une piste de recherche STP ?

**Comment by macros83** [comment]
J'ai rajouté le répertoire plans qui manquait apparemment mais maintenant je suis planté, il reste sur la page de première connexion et refuse de passer au suivant 'utilisateur ou mot de passe incorrect' ...
Début difficile avec nextdom.

**Comment by Gis70** [comment]
Salut @macros83 as tu fait une fresh install ? Passe sur le forum discord pour qu'on t'aide.

**Comment by macros83** [comment]
Merci, j’installe discord, oui, fresh install basé sur raspian streched du 8/4/2019 updaté.

**Comment by macros83** [comment]
J'ai du mal comprendre, je ne trouve pas de nextdom sur discord

**Comment by Gis70** [comment]
non, désolé, j'aurais dû te mettre le lien
https://discordapp.com/invite/aXVQCbN
