### ISSUE TITLE
Vue update core GUI disparaît dès restore backup

### ISSUE THREAD

**Issue by Gis70** [NextDom/nextdom-core#1417]
Lors du restore de mon backup sur une fresh install NextDom, cette vue disparaît 
![image](https://user-images.githubusercontent.com/16589132/66787617-a46be780-eee4-11e9-94a7-360b0b011549.png)

je me retrouve avec ça :
![image](https://user-images.githubusercontent.com/16589132/66787627-b188d680-eee4-11e9-9d60-5609c2314ed6.png)

**Comment by Sylvaner** [comment]
Oui, en effet le check update n'est pas réalisé immédiatement, c'est ce qui posait problème car il se lancait pendant l'installation et donc plantait cette installation (debian)

**Comment by cyrilphoenix71** [comment]
@Sylvaner on fait quoi ? on clos ? une solution alternative?

**Comment by Gis70** [comment]
Pourquoi tu veux clore ? tu as solutionné le pb ? :)

**Comment by cyrilphoenix71** [comment]
@Sylvaner on fait quoi ?

**Comment by Gis70** [comment]
INSERT INTO `update` VALUES (1,'core','nextdom','nextdom','','','apt','ok','{"doNotUpdate":"1"}');

merci @Sylvaner
