### ISSUE TITLE
Bouton copier clé API KO

### ISSUE THREAD

**Issue by Gis70** [NextDom/nextdom-core#1420]
Le bouton pour copier dans le presse papier une clé API ne marche pas.

**Comment by Sylvaner** [comment]
Sur quel navigateur ?

**Comment by Gis70** [comment]
chrome, j'ai pas testé avec d'autre.

**Comment by Gis70** [comment]
Le cache n'était pas bien vidé un ctrl f5 ne suffisait pas.
