### ISSUE TITLE
Message de plugin masqué par le "Retour" sur liste plugin

### ISSUE THREAD

**Issue by CyrilCharlier** [NextDom/nextdom-core#1426]
**Décrivez le bug**
Lors de la configuration d'un plugin, les messages d'erreurs ou d'informations des plugins sont masqués par la barre de retour à la liste des plugins

**Comment reproduire ?**
Étapes pour reproduire le problème :
1. Aller sur la page de configuration d'un plugin
2. Provoquer un message de retour du plugin (activation / désactivation par exemple)
3. Constater que la barre contenant le bouton "retour" masque le message de retour du plugin

**Screenshots**
![image](https://user-images.githubusercontent.com/11455745/67149334-62f38780-f2aa-11e9-9c6d-5bc102ef584d.png)

**Information matérielles**
 - OS : Debian 9
 - Navigateur :  chrome, firefox
 - Version NextDom : 0.5
 - Branche NextDom : develop
 - Installé via : deb

**Comment by ColonelMoutarde** [comment]
Ce bug est déjà référencé ici : #1393
Peux-tu reporter ta remarque dans l'autre issue pour que nous la clôturions.

**Comment by CyrilCharlier** [comment]
Oui bien sur. Je pensais avoir bien cherché .. merci Colonel

**Comment by CyrilCharlier** [comment]
Fermeture pour cause de doublon
