### ISSUE TITLE
Postinst -D ne prend pas le fichier de de conf dev

### ISSUE THREAD

**Issue by Gis70** [NextDom/nextdom-core#1445]
le postinst -D ne prend pas le fichier de conf dev

**Comment by slobberbone** [comment]
A revoir une fois : https://github.com/NextDom/nextdom-core/issues/1459 terminée

**Comment by cyrilphoenix71** [comment]
@slobberbone tu gere ?

**Comment by cyrilphoenix71** [comment]
Option annulée avec le nouveau postinst
