### ISSUE TITLE
Dossier /tests inutile pour la prod

### ISSUE THREAD

**Issue by Gis70** [NextDom/nextdom-core#1452]
Le dossier où sont les tests unitaires ne sert à rien chez l'utilisateur.

On pourrait le supprimer sur la master si c'est juste la develop que l'on balance dans le master.

Où sinon via le postinst après install chez l'utilisateur ?

**Comment by ColonelMoutarde** [comment]
Bof ça gêne pas.

**Comment by cyrilphoenix71** [comment]
Issue cloturée car c'est deja le cas :
`cd ${WEBSERVER_HOME}/
    rm -rf docs tests composer.* .travis.yml phpunit.xml.dist .github .git .gitignore .coveralls.yml .sass-cache`
