### ISSUE TITLE
Installation de nextdom-minimal sous Debian 10

### ISSUE THREAD

**Issue by Aior** [NextDom/nextdom-core#1461]
**Décrivez le bug**
nextdom-minimal dépend de mysql-client. mysql-client n'existe plus sous Debian 10 au profit de  default-mysql-client.
default-mysql-client installera le client mysql adapté à la version de Debian.

**Comment reproduire ?**
Sur un système où nextdom n'est pas encore installé :
apt-get install nextdom-minimal nextdom-mysql 

**Erreur**
```
# apt install nextdom-minimal
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances
Lecture des informations d'état... Fait
Certains paquets ne peuvent être installés. Ceci peut signifier
que vous avez demandé l'impossible, ou bien, si vous utilisez
la distribution unstable, que certains paquets n'ont pas encore
été créés ou ne sont pas sortis d'Incoming.
L'information suivante devrait vous aider à résoudre la situation :

Les paquets suivants contiennent des dépendances non satisfaites :
 nextdom-minimal : Dépend: mysql-client mais il n'est pas installable
E: Impossible de corriger les problèmes, des paquets défectueux sont en mode « garder en l'état ».
```

**Information matérielles**
 - OS : Debian 10.1
 - Version NextDom : nextdom-minimal 1.2.0 / nextdom 0.5.1
 - Branche NextDom : master / packagé deb
 - Installé via : paquet deb

**Labels**

**Comment by Aior** [comment]
@Astral0

**Comment by Astral0** [comment]
Corrigé dans le paquet nextdom-minimal pour s'adapter au paquet générique.

**Comment by Astral0** [comment]
Corrigé dans le paquet nextdom-minimal pour s'adapter au paquet générique.
