### ISSUE TITLE
Bloc 'CODE' d'un scénario n'est pas interprété comme une action à réaliser

### ISSUE THREAD

**Issue by Aior** [NextDom/nextdom-core#1499]
**Description**
Dans un scénario, un bloc 'CODE' n'est pas interprète comme un bloc action mais comme une condition à évaluer.
En conséquence, aucun des [petits blocs PHP utiles](https://github.com/NextDom/NextDom/wiki/Blocs-PHP-utiles) ne fonctionne.

**Comment reproduire ?**
1. Aller sur un scénario, ajouter un bloc 'CODE'
2. Rédiger un petit code PHP simple
3. Executer et analyser les logs pour vérifier le résultat attendu

**Screenshots**

un echo d'une variable :
![2019-11-07_15h59_01](https://user-images.githubusercontent.com/4631692/68403444-39c56900-017d-11ea-92e1-04e6eccb7195.png)

Si on lui envoi une condition à évaluer :
![2019-11-07_16h28_26](https://user-images.githubusercontent.com/4631692/68403456-421da400-017d-11ea-89a0-242f9701c4b7.png)

**Information matérielles**
 - OS : Debian 10.1
 - Navigateur : Chrome
 - Version NextDom : 0.5.1 fresh install -> pas d'import de backup, jamais upgradé.
 - Branche NextDom : master
 - Installé via : apt deb

**Labels**

**Comment by Aior** [comment]
A voir si le bloc CODE est réellement nécessaire.
Discutez en entre devs ? 
Ce que je voulais faire a finalement pu être réalisé grâce aux variables et l'utilisation du plugin script.
Personnellement, je trouve cette fonction très sensible pour la sécurité du core et mérite d'être retirée, d'autant plus qu'il est possible de faire son propre code via le plugin script sans tout faire planter.

**Comment by ColonelMoutarde** [comment]
Salut, selon moi cette possibilité devrait être supprimé. Exécuter du code php comme ceci est une énorme faille.

**Comment by Sylvaner** [comment]
C'est un sujet assez sensible, les gens veulent cette fonctionnalité, mettent des bouts de code pour faire des trucs bizarres plutôt que de faire un plugin ou une demande de fonctionnalité.
Je pense que ça devrait être viré mais il faudrait que les cas d'usage soient couverts. Mais bon on peut aussi avoir de longues discussions sur les cas d'usages :)

**Comment by Sylvaner** [comment]
C'est résolu pour la 0.6.0 :)
