### ISSUE TITLE
Refonte des strings fixes

### ISSUE THREAD

**Issue by slobberbone** [NextDom/nextdom-core#15]
Création d'enum pour toutes les chaines de caractères fixes du core. a faire que dans les nouveaux fichiers pour le moment pour pas tout casser

**Comment by ColonelMoutarde** [comment]
http://php.net/manual/fr/class.splenum.php
voila comment faire.
en standard dans php

**Comment by slobberbone** [comment]
Merci

**Comment by Sylvaner** [comment]
Une classe Enum est maintenant disponible. SplEnum impliquait l'installation d'autres dépendances
