### ISSUE TITLE
commande Orpheline .

### ISSUE THREAD

**Issue by Esso1-jeedom** [NextDom/nextdom-core#150]
dans Analyse => equipement=> commande orpheline
il y a 3 commandes "Core" orpheline.
normalement cela doit etre vide .

![commande orpheline](https://user-images.githubusercontent.com/40739563/46124841-84f51480-c226-11e8-83f1-a2ed5c6362a4.JPG)
( nota ne pas prendre en compte les commandes de chauffage vu que j'ai supprimer l'equipement)

**Comment by byackee** [comment]
ca vient d'une nouvelle fonction de la version alpha de jeedom mais qui n'est pas fini
https://github.com/jeedom/core/commit/af34d0fcec75d988fef0ed2b4f9b60bbb909f975

**Comment by Esso1-jeedom** [comment]
ok
