### ISSUE TITLE
Annuler une confirmation d'action ne fonctionne pas

### ISSUE THREAD

**Issue by Aior** [NextDom/nextdom-core#1501]
**Déscription**
Le bouton "Cancel" et la petite croix sur le popup "Etes-vous sûr de vouloir faire cette action ?" ne fonctionne pas.

L'occasion de traduire 'Cancel' ?

**Comment reproduire ?**
Étapes pour reproduire le problème :
1. Configurer une action avec l'option "Confirmer l'action". 
2. Actionner la commande qui demande confirmation
3. Ne pas cliquer sur 'OK', mais 'Cancel' ou la petite croix en haut à droite. Ca ne fonctionne pas.

**Screenshots**
![2019-11-08_08h58_10](https://user-images.githubusercontent.com/4631692/68459784-90c35080-0206-11ea-8a33-883050819147.png)

**Information matérielles**
 - OS : Debian 10.1
 - Navigateur : Chrome
 - Version NextDom : 0.5.1
 - Branche NextDom : master
 - Installé via : apt deb

**Labels**

**Comment by Aior** [comment]
[Vidéo en complément](https://youtu.be/8PbGhrGd2fc)

**Comment by Sylvaner** [comment]
C'est corrigé, merci
