### ISSUE TITLE
Log du backup trop verbeux

### ISSUE THREAD

**Issue by Gis70** [NextDom/nextdom-core#1508]
Les logs du backup sont trop verbeux :

![image](https://user-images.githubusercontent.com/16589132/68542046-fef34900-03a7-11ea-821e-72365127153d.png)

Il faudrait se limiter aux dossiers / sous dossiers par rapport à la racine

**Comment by slobberbone** [comment]
Le soucis c'est quand un backup ne fonctionne pas, c'est une information essentielle...

**Comment by Gis70** [comment]
d'accord mais pas en master alors.
