### ISSUE TITLE
Design sans menu

### ISSUE THREAD

**Issue by metagx** [NextDom/nextdom-core#1530]
**Votre demande de fonctionnalité est-elle liée à un problème?**
non

**Décrivez ce que vous souhaitez**
avoir la possibilité d'afficher son design sans la barre de menu (utilisation tablette)

**Comment by slobberbone** [comment]
Un clic droit sur le design, action plein écran ne fonctionne pas ?

**Comment by metagx** [comment]
![60F957EC-D702-4171-B6F7-3826A7AA7488](https://user-images.githubusercontent.com/57872503/69013618-7e71b100-0982-11ea-9e1b-8ab48f796dad.png)
impossible, sur tablette IOS.
après le comportement sera peut être différents si (meme en choississant cochant "se souvenir de moi") si on pouvait se connecter directement sans la demande de login

**Comment by slobberbone** [comment]
@metagx rajoute &fullscreen=1 à ton url et ça va le faire
