### ISSUE TITLE
icone sur design

### ISSUE THREAD

**Issue by Esso1-jeedom** [NextDom/nextdom-core#1533]
pas facile a expliquer 
sur le design une commande a une taille et peut sortir du cadre. 
on n'affiche pas les lignes des commandes non visible.
sur develop

les icones ne ressortent plus du cadre. 
comme ici 
![image](https://user-images.githubusercontent.com/40739563/69173436-0fba6200-0b00-11ea-93e8-366b15efd14d.png)

sur la 0.5.4  issue du depot dev
![image](https://user-images.githubusercontent.com/40739563/69173501-32e51180-0b00-11ea-8384-e8564782aa05.png)

le soucis et la prise de ligne vide .
![image](https://user-images.githubusercontent.com/40739563/69173703-9707d580-0b00-11ea-8a8e-d527da1cf8a1.png)
elle correspondre a des lignes non afficher .
avant 
![image](https://user-images.githubusercontent.com/40739563/69173766-b69efe00-0b00-11ea-989e-bc569328c191.png)

que le cadre soit prise en compte plutot que le dépassement . pourquoi pas.
par contre les lignes masquer ne devrait pas decaler l'affichage. 
sur le dash l'affichge et normale et le debordement possible .

**Comment by cyrilphoenix71** [comment]
inclus dans https://github.com/NextDom/nextdom-core/pull/1532
