### ISSUE TITLE
Resumé scénario, le bouton Enregistrer ne fonctionne pas

### ISSUE THREAD

**Issue by slobberbone** [NextDom/nextdom-core#1535]
Dans la page scénarios, puis cliquer sur Resumé scénario. Effectuer des modifications, cliquer sur le bouton Enregistrer et rien ne se passe, et les changements disparaissent.
![Modification résumé scénario](https://user-images.githubusercontent.com/3833875/69187089-2a013980-0b1a-11ea-81b6-524174d80d5e.png)

**Comment by Gis70** [comment]
OK sur develop (future 0.7)
