### ISSUE TITLE
Bouton dupliquer/Enregistrer sur Virtuel HS

### ISSUE THREAD

**Issue by slobberbone** [NextDom/nextdom-core#1548]
**Description**
Bouton Enregistrer sur action de duplication d'un équipemenent n'a aucun effet. De même que Enregistrer le tout sur un equipement virtuel (tout était fonctionnel en 0.5.4)
**Screenshots**
![Sélection_217](https://user-images.githubusercontent.com/3833875/69476582-ff460800-0ddb-11ea-9389-e2444dbbc2dc.png)
**Information matérielles**
 - Version NextDom : 0.6.0-rc0
 - Installé via : paquet deb,

**Comment by Gis70** [comment]
Tout est OK en develop
