### ISSUE TITLE
Certains plugins ne se mettent pas à jour en 0.6.0 RC0

### ISSUE THREAD

**Issue by vinceg77** [NextDom/nextdom-core#1553]
**Décrivez le bug**
Alors que les plugins tous correctement apparaissent dans la liste des MAJ, certains ne peuvent pas être mis à jour.
Lorsque je clique sur 'Mettre à jour' puis OK la pop-up d'avancement de la MAJ apparaît correctement, et n'affiche pas d'erreur. Mais à fin du processus le plugin n'est pas mis à jour et apparaît toujours dans la liste des plugins a mettre à jour.
A noter que les plugins non mis a jour fonctionne cependant.

Plugins concernés (chez moi) : 
- ArrosageAuto
- Opening
- Proxmox
- Reveil
- Surveillancestation

Mes autres plugins se sont mise à jour correctement

**Screenshots**
![Update](https://user-images.githubusercontent.com/51484329/69530732-d906a080-0f72-11ea-9070-32a6e379c706.gif)

**Information matérielles**
 - Version NextDom : 0.6.0 RC0
 - Branche NextDom : develop
 - Installé via :  git clone

**Comment by iWils** [comment]
Pour plus de précision, nous avons constater que le souci est présent avec les plugins obtenu via GitHub.
Exemple, je rencontre le problème avec les plugins:

    Livebox
    Sigri_Linky

**Comment by vinceg77** [comment]
Ce problème ne survient plus sur les dernières releases
