### ISSUE TITLE
Bug lors du téléchargement de template de scénario en 0.6.0 RC0

### ISSUE THREAD

**Issue by vinceg77** [NextDom/nextdom-core#1554]
**Décrivez le bug**
Dans Template de scénario, lorsque l'on veut télécharger un template créé, on arrive sur une page 404

**Comment reproduire ?**

Dans un scénario cliquer sur 'template'
1. Donner un nom au template
2. Cliquer sur le nom du template
3. Cliquer sur Télécharger

**Screenshots**
![Template scenario 1](https://user-images.githubusercontent.com/51484329/69534819-d5771780-0f7a-11ea-96e9-ff5a8140a34c.png)
![image](https://user-images.githubusercontent.com/51484329/69534825-d7d97180-0f7a-11ea-9d0b-5c0dd70452ce.png)

Information matérielles

Version NextDom : 0.6.0 RC0
Branche NextDom : develop
Installé via : git clone

**Comment by iWils** [comment]
Pour plus de précision, nous avons constater que le souci est présent avec les plugins obtenu via GitHub.
Exemple, je rencontre le problème avec les plugins:
- Livebox
- Sigri_Linky
