### ISSUE TITLE
bugg BACKUP 0.6.0 RC1

### ISSUE THREAD

**Issue by Esso1-jeedom** [NextDom/nextdom-core#1557]
le backup plante .
[ Create Backup Process ]
*************** starting backup procedure at 2019-11-26 18:40:46 ***************
stopping NextDom (cron & scenario)... starting NextDom (cron & scenario)...  OK
*************** end of backup procedure at 2019-11-26 18:40:48 ***************
*************** elapsed time 2 ***************
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function NextDom\Helpers\LogHelper::addInfo(), 1 passed in /usr/share/nextdom/src/Helpers/NextDomHelper.php on line 752 and at least 2 expected in /usr/share/nextdom/src/Helpers/LogHelper.php:90
Stack trace:
#0 /usr/share/nextdom/src/Helpers/NextDomHelper.php(752): NextDom\Helpers\LogHelper::addInfo('Stopping all cr...')
#1 /usr/share/nextdom/src/Managers/BackupManager.php(93): NextDom\Helpers\NextDomHelper::stopSystem(true)
#2 /usr/share/nextdom/install/backup.php(56): NextDom\Managers\BackupManager::createBackup()
#3 {main}
thrown in /usr/share/nextdom/src/Helpers/LogHelper.php on line 90

![image](https://user-images.githubusercontent.com/40739563/69659606-dc874e00-107e-11ea-8040-53a266df0d84.png)

**Comment by slobberbone** [comment]
Fixé
