### ISSUE TITLE
Doublons dans la page de santé NextDom

### ISSUE THREAD

**Issue by iWils** [NextDom/nextdom-core#1560]
**Décrivez le bug**
Dans la page de santé de NextDom, j'ai remarqué que les champs:
- VERSION OS
- VERSION PHP
sont en doublons.

**Comment reproduire ?**
Étapes pour reproduire le problème :
1. Aller dans 'Diagnostics'
2. Cliquez sur 'Santé'

**Screenshots**
![image](https://user-images.githubusercontent.com/56263502/69748556-ed9c9180-1148-11ea-8d3c-55f072d6706b.png)

**Information matérielles**
 - OS : Debian 9.11
 - Navigateur : Chrome, Firefox
 - Version NextDom : 0.6.0 CR0 ~0.6.0 RC2
 - Branche NextDom : develop
 - Installé via : Git clone

**Comment by vinceg77** [comment]
+1 iWils. Chez moi idem (meme version)

**Comment by Sylvaner** [comment]
Merci, ça a été corrigé lors du refactoring de cette page :)
