### ISSUE TITLE
impossible de mettre une image de fond sur un fresh install

### ISSUE THREAD

**Issue by Esso1-jeedom** [NextDom/nextdom-core#1565]
impossible de mettre une image 
car ile rep /custom n'existe pas.

pour résoudre créer le rep
mkdir /var/lib/nextdom/data/custom/
sudo chmod 775 -R /var/lib/nextdom/data/custom/
sudo chown -R www-data:www-data /var/lib/nextdom/data/custom/

![image](https://user-images.githubusercontent.com/40739563/69911069-0c837800-1416-11ea-802d-c6fe092acd12.png)

nota lors de la remonté d'un backup , le rep est créer donc plus de pb
meme avec une migration

**Comment by cyrilphoenix71** [comment]
@slobberbone tu ajoute ça a ton postinst refacto ?
