### ISSUE TITLE
impossible d'afficher une image JPG en fond de design

### ISSUE THREAD

**Issue by Esso1-jeedom** [NextDom/nextdom-core#1566]
aprés une migration d'un backup jeedom

on peut telecharger une image de fond sur le design. 
par contre il n'affiche plus que des images au format PNG
les images au format jpg, elle sont  remplacées par un lien cassé.

faire la manip , fresh install et remonter un backup jeedom .  
essayer de changer l'image de fond . 
par une image PNG
puis une image en JPG 

nota sur mon backup nextdom, je n'ai pas ce pb

**Comment by dcjona** [comment]
J'ai constaté le même soucis de mon côté

**Comment by Esso1-jeedom** [comment]
bon j'ai trouvé la merde... en fait aprés une migration jeedom/nextdom . le format JPG est inconnu, il ne peut pas l'afficher, il connait bien jpeg/ png. 
pour le constater, renommer l'image .JPG en JPEG, et l'incorporer . 
l'image s'affichera, elle a juste été renommé donc aucun changement d'encodage d'image. 
cela arrive aprés une migration jeedomau dessus de 3.2.11 .

**Comment by cyrilphoenix71** [comment]
@slobberbone un lien avec la ligne 26 de nextdom-.common ?
