### ISSUE TITLE
Version APT suite à restore de backup

### ISSUE THREAD

**Issue by Esso1-jeedom** [NextDom/nextdom-core#1567]
installation d'une fresh install en 0.6.0

la versions de maj donne bien 0.6.0 aprés un verif,
le lien du change log est ok et pointe bien sur le bon lien.
aprés une restoration de backup
![image](https://user-images.githubusercontent.com/40739563/69911550-42782a80-141d-11ea-8992-3d74b35ce1d7.png)
meme aprés une verif
et le lien du changelog cette fois est erronné
https://github.com/NextDom/nextdom-core/blob/master/CHANGELOG..md

il y a 2 points a la fin.

nota lors d'une restauration de backup  on ne doit pas remettre a jour les infos de version et de changelog .

**Comment by Aior** [comment]
Reproduis (même bug ?) sur une 0.6.0 fresh sur laquelle un backup en 0.5.1 a été restauré.

![2019-12-02_09h53_48](https://user-images.githubusercontent.com/4631692/69960050-d115a600-1508-11ea-8490-b071be39e13a.png)
Malgré application du bouton "Vérifier"

--
Après l'install fresh 0.6.0, la version de la tuile indique 0.6.0.
Après restauration d'un backup réalisé en 0.5.1, la tuile indique 0.5.1.
Le bouton "Vérifier" ne change rien.

**Comment by ralmn** [comment]
J'ai le même probleme en 0.6.0 depuis le dépot apt.

Il semble que ça viennent de https://github.com/NextDom/nextdom-core/blob/31937637541b3ec0e4ae467455d65b314039754b/src/Model/Entity/Update.php#L328-L338
L'url étant :  https://raw.githubusercontent.com/nextdom/core/master/core/config/version renvoie `404: Not Found`
