### ISSUE TITLE
[BUG][V0.6] probleme d'affichage fenetre popup

### ISSUE THREAD

**Issue by therealcorwin** [NextDom/nextdom-core#1571]
Lors de la navigation sur le market, par exemple, si nous cliquons sur un plugin pour avoir sa fiche descriptive, de temps en temps sa fenêtre s'affiche mal sur le navigateur. La partie haute de celle-ci s'affiche hors du cadre du navigateur. Cela a pour conséquence de bloquer la navigation car nous ne pouvons pas fermer cette popup.  

Étapes pour reproduire le problème :
1. Aller sur le market
2. Cliquez sur n'importe  quel plugin jusqu'a l'apparition du bug

**Screenshots**
![BUG_V6_POPUP](https://user-images.githubusercontent.com/5471363/69971109-b3a00680-151f-11ea-8cbd-3483e9b9234c.png)

**Information matérielles**
 - OS : BUSTER
 - Navigateur : Vivaldi FF BRAVE (dernière version 02/12)
 - Version NextDom : 0.60
 - Branche NextDom : MASTER
 - Installé via : DEB

**Comment by fensoft** [comment]
pour info, on peux fermer la fenêtre avec echap. ça apparait plus vite chez moi quand l'inspecteur de code firefox est ouvert et ça disparait en jouant avec le zoom (control+molette)

**Comment by Gis70** [comment]
soldé en #1649

**Comment by therealcorwin** [comment]
Vu avec @cyrilphoenix71 : application du resize en hauteur pour la fenetre de description du plugin. Cela permettra d'avoir une redimessionnement dynamique de l'affichage en cas de modification de la taille du navigateur.
