### ISSUE TITLE
Erreur "ReferenceError: queryParams is not defined"

### ISSUE THREAD

**Issue by fensoft** [NextDom/nextdom-core#1576]
**Décrivez le bug**
Certains boutons de commande ne s'affichent plus en version develop (ok en version 0.6.0)

**Comment reproduire ?**
Étapes pour reproduire le problème :
1. Creer un virtuel vide
2. Cliquez sur "ajouter une commande"
3. Regarder la console JS sous firefox

**Comment by fensoft** [comment]
PS: ça le fait sur tout les plugins, jmqtt dans mon cas

**Comment by Sylvaner** [comment]
Corrigé
Merci
