### ISSUE TITLE
Mapping des templates de scenario

### ISSUE THREAD

**Issue by vinceg77** [NextDom/nextdom-core#1582]
Lorsque l'on importe un template de scenario, il faut mapper les commandes du templates avec celles présentes sur son installation. 
Pour autant il arrive que le template de scénario soit utilisé seulement pour transférer des scenarios, d'un Nextdom à un autre, de Jeedom à Nextdom... Dans ce cas, bien souvent les commandes sont en fait exactement les memes que celles incluses dans le template. Mais meme si c'est le cas, on ne peut pas finaliser l'import sans avoir bêtement recopié les commandes  :

![image](https://user-images.githubusercontent.com/51484329/70378545-da947900-1921-11ea-9824-72619addf1e7.png)

**Décrivez ce que vous souhaitez**
Serait il possible, que lorsque le champs "Paramètres / Variables / Commandes du template pour l'application au scénario actuel " n'est past rempli, ce soit la commande incluse dans le template qui soit directement appliquée (dans la mesure où elles existent bien sur) ??

**Comment by cyrilphoenix71** [comment]
j'ai une idée pour ca je regarde demain
