### ISSUE TITLE
Problème import dossier avec image sur migration jeedom => nextdom

### ISSUE THREAD

**Issue by Gis70** [NextDom/nextdom-core#16]
![image](https://user-images.githubusercontent.com/16589132/53920652-1edeaa00-406e-11e9-9c05-187c76d7fb60.png)

Ca m'a fait le coup lors du passage 3.3.x à la beta aussi.

**Comment by slobberbone** [comment]
Ce fichier ne se trouve plus dans le plugin ?

**Comment by Gis70** [comment]
Je n'ai plus doc/images/..... je pense que c'est de la vieille arborescence qui n'est pas recopiée, j'avais déjà eu ce problème lors du passage en jeedom beta

**Comment by Gis70** [comment]
J'ai réinstallé le plugin est c'est OK je clos
