### ISSUE TITLE
jeedom.private.getParamsAJAX manquant pour les plugins

### ISSUE THREAD

**Issue by fensoft** [NextDom/nextdom-core#1604]
**Décrivez le bug**
https://github.com/jeedom/core/blob/2c42ce8ba9400d3efea05035a366993c73aacc11/core/js/private.class.js#L78 il y a une 10aines de mes plugins (au pif: alexaapi) qui utilise cette fonction

J'ai voulu mettre jeedom.private.getParamsAJAX=nextdom.private.getAjaxParams dans ./assets/js/core/jeedom.class.js mais visiblement le code ne fonctionne pas. En copiant/collant tout le code de jeedom, ça refonctionne.

**Comment reproduire ?**
Étapes pour reproduire le problème :
1. Aller dans le plugin alexaapi, dans les paramètres du plugin
2. Cliquez sur le bouton vert "generer le cookie"
3. Regarder la console JS

**Comment by Gis70** [comment]
Soldé par PR #1621, quand ça sera mergé dans develop cà sera bon.

**Comment by fensoft** [comment]
à réouvrir car ça n'as pas encore été testé spécifiquement
