### ISSUE TITLE
Impossible de télécharger une sauvegarde

### ISSUE THREAD

**Issue by perarem** [NextDom/nextdom-core#1611]
**Décrivez le bug**
Impossible de télécharger une sauvegarde

**Comment reproduire ?**
Étapes pour reproduire le problème :
1. Aller dans sauvegarde puis onglet Locales
2. Cliquez sur Télécharger la sélection

**Message d'erreur**
Argument 1 passed to NextDom\Helpers\Utils::checkPath() must be of the type string, null given, called in /var/www/nextdomdev/src/Api/downloadFile.php on line 47

**Information matérielles**
 - OS : Debian 9.11
 - Navigateur : Edge / Firefox
 - Version NextDom : 0.6.0
 - Branche NextDom : develop fresh install
 - Installé via : git clone

**Comment by Gis70** [comment]
Idem pour moi

**Comment by Sylvaner** [comment]
C'est corrigé :)
Merci
