### ISSUE TITLE
bug nom de votre Nextdom

### ISSUE THREAD

**Issue by cyrilphoenix71** [NextDom/nextdom-core#164]
Dans l'onglet général si on met un nom a notre nextdom, on sauvegarde.
Si on va dans l'onglet cache, le bandeau d'info n'affiche pas le nom apres les :

**Comment by Sylvaner** [comment]
$pageData['TITLE'] = ucfirst($page) . ' - ' . $configs['product_name'];

Ca affiche toujours NextDom

**Comment by cyrilphoenix71** [comment]
@Sylvaner ce que tu me donne je peux l'utiliser dans un html.twig ?

**Comment by DanoneKiD** [comment]
C'est surtout dans la page objet que ça choque je trouve. Je vais voir si je trouve un moyen
![image](https://user-images.githubusercontent.com/522809/47008491-bd5b8480-d13a-11e8-9a3a-6d84d41e7fbd.png)

**Comment by DanoneKiD** [comment]
Corrigé #318
