### ISSUE TITLE
Securisation MAJ via IHM

### ISSUE THREAD

**Issue by therealcorwin** [NextDom/nextdom-core#1653]
Sécurisation de la mise à jour de Nextdom via l'ihm. 

Suite à de tres nombreux echec lors de mise à jour de ND via l'ihm avec une installation en .deb que faut il faire : 

- Abandonner l'option de maj depuis l'ihm lors d'une installation en .deb

- Investiguer et savoir pkoi cela plante

- Obi wan Kenobi

**Comment by therealcorwin** [comment]
Testé et validé.

Question : Doit on bloquer le bouton "suivant" tant que la compléxité du mdp est pas au vert ? (Mon avis oui, on devrait) 

@cyrilphoenix71 @slobberbone

**Comment by slobberbone** [comment]
il faut comprendre et faire en sorte que ça fonctionne.
