### ISSUE TITLE
[V0.6.8] Gen_asset.sh node: command not found

### ISSUE THREAD

**Issue by therealcorwin** [NextDom/nextdom-core#1688]
`root@Nextdom:/var/www/html/scripts# ./gen_assets.sh 
To start automatic generation, add the --watch option
 => Copy vendors
=> Copy icons
=> Copy images
=> Copy html
**./gen_assets.sh: line 30: node: command not found**

root@Nextdom:/var/www/html/scripts# ls -ltr
total 104

-rwxrwxr-x 1 www-data www-data 13399 Feb  2 14:54 gen_assets.sh`

**Comment by cyrilphoenix71** [comment]
@slobberbone ?

**Comment by slobberbone** [comment]
A priori l'update de nodejs peut poser soucis et dans le nouveau paquet nodejs, la commande node n'existe plus.
il faudrait installer nodejs-legacy ou utiliser nodejs comme commande (si elle a le mm comportement que node)
https://askubuntu.com/questions/235655/node-js-conflicts-sbin-node-vs-usr-bin-node/320271#320271

**Comment by slobberbone** [comment]
Sinon, plus simplement, gen_assets.sh n'installe rien, donc faites un gen_install_composer_npm.sh avant

**Comment by Sylvaner** [comment]
Alors si la version installé est un debian de prod, c'est normal que les outils de développement ne soit pas packagés pour alléger le paquet.
