### ISSUE TITLE
reinstallation erreur raspbian

### ISSUE THREAD

**Issue by macros83** [NextDom/nextdom-core#1691]
Bonjour, 
après un problème fonctionnel, j'ai voulu faire une restauration qui a amené une rreur, j'ai essayé de réinstaller depuis le début, sans succès, pourriez-vous m'aider SVP ?
environnement : raspbian streched
nettoyage et reinstall : 
sudo apt remove --purge  nextdom
sudo apt remove --purge apache2* mysql* php*
sudo apt autoremove
sudo rm /var/www -R
sudo rm /etc/php -R
sudo rm /etc/apache2 -R
sudo rm /var/tmp/*.* -R
sudo apt update
sudo apt list --upgradable
sudo apt-get -y upgrade
sudo apt -y install nextdom
erreur  ---- fichier postinst introuvable
liste de réinstall jointe.
[ins-nextdom.txt](https://github.com/NextDom/nextdom-core/files/4154825/ins-nextdom.txt)

**Comment by Esso1-jeedom** [comment]
le pb et que tu es resté sur le depot dev
ce n'est pas bon ..
remet toi sur le dépôt normal, la 0.6.8 est dessus

echo "deb  http://debian.nextdom.org/debian  nextdom main" >/etc/apt/sources.list.d/nextdom.list
apt update
apt -y install nextdom

**Comment by macros83** [comment]
merci bcp, j'essaye demain soir.

**Comment by macros83** [comment]
Merci encore, c'est réinstallé, restoré et ça fonctionne parfaitement !
merci, merci!

**Comment by Esso1-jeedom** [comment]
c de la faute , tu as du voir le liens que je donnais pour le depot dev pour recuperer la versions qu'on a  actuellement su le depot master ...
la faut attendre qu'on péte nos install , et qu'on corrige , pour qu'on vous la laisse sur le depot dev
