### ISSUE TITLE
step0_createDirectories: not found

### ISSUE THREAD

**Issue by edgd1er** [NextDom/nextdom-core#1696]
**Décrivez le bug**
Une description claire et concise du problème avec si possible une capture d'écran ou un log...
step0_createDirectories

**Comment reproduire ?**
Étapes pour reproduire le problème :
lancer une install docker
attendre l'execution du install_docker.sh

La fonction step0_createDirectories n'existe pas, celui qui a commité cette modificatin peut il aussi commiter son renommage de fonction ? [Fix Squash](https://github.com/NextDom/nextdom-core/commit/9f673c8f002921bf8908a076a807b7f7d67609ba)

**Information matérielles**
PC + docker

**Labels**
Ajouter à droite de cette issue le label Component_XXX ciblant le composant lié à cette issue...

**Comment by slobberbone** [comment]
Désolé ;)
