### ISSUE TITLE
Problème interaction

### ISSUE THREAD

**Issue by Hellden** [NextDom/nextdom-core#1699]
Bonjour,

Après l'update de Nextdom, j'ai rencontré l'erreur suivante :

`[MySQL] Error code : 42S22 (1054). Unknown column 'score' in 'having clause'  : SELECT `interactDef_id`, `query`, `actions`, `id` FROM `interactQuery`                  GROUP BY id                 HAVING score > 1`

Cela se produit quand je lance une interaction. J'ai essayé de rajouter la colomn **score**, cela corrige le problème quelques temps mais après le problème revient.

J'ai vérifié dans la table interactQuery la coloumn **score** est bien présente. Je sèche un peu.

Merci d'avance.

**Comment by Sylvaner** [comment]
Bonjour,

J'ai trouvé le bug, nous allons corriger.
Sur quelle version cela se produit-il ?

**Comment by Hellden** [comment]
Bonjour,

Sur la version 0.6.8

Merci :)

**Comment by Hellden** [comment]
Merci bien, le problème est corrigé :)

**Comment by cyrilphoenix71** [comment]
L'issue sera close avec la PR

**Comment by Sylvaner** [comment]
Merci super
