### ISSUE TITLE
Impossible d'activer le mode mobile

### ISSUE THREAD

**Issue by ColonelMoutarde** [NextDom/nextdom-core#170]
/index.php?v=m&p=home la page se charge sans afficher la version mobile

**Comment by byackee** [comment]
fonctionne bien chez moi

**Comment by ColonelMoutarde** [comment]
J'ai toujours le bug avec le passage à la version mobile
Quand je clique sur le bouton version mobile, j'ai les flèches de chargement qui apparaissent. J'ai laissé tourner la vm toute la nuit et elles sont toujours là
il faut que je rafraichisse la page pour que la bascule soit effective.

**Comment by ColonelMoutarde** [comment]
Je test avec firefox

**Comment by ColonelMoutarde** [comment]
Même comportement avec firefox

**Comment by slobberbone** [comment]
https://github.com/Sylvaner/nextdom-core/pull/212

**Comment by ColonelMoutarde** [comment]
le bug est toujours là
