### ISSUE TITLE
Ajout étape FirstUse

### ISSUE THREAD

**Issue by cyrilphoenix71** [NextDom/nextdom-core#173]
Je propose d'ajouter 2 étape au FirstUse : 

- Demander de saisir un nom a votre NextDom : sinon le champ est vide dans Admin/General et du coup on a plusieurs texte incomplet et donc incompréhensible

- Demander de choisir language : ca peut etre utile pour eviter de fouiller pour chercher la langue quand on ne comprend pas le francais

**Comment by byackee** [comment]
Je ne pene pas que cela soit nécéssaire, on va plutot mettre une valeur par defaut
