### ISSUE TITLE
erreur sur macro

### ISSUE THREAD

**Issue by Esso1-jeedom** [NextDom/nextdom-core#175]
une macro simple
aller au design
![erreur](https://user-images.githubusercontent.com/40739563/46214019-5bc5a880-c33a-11e8-91e8-406b172caa88.JPG)

**Comment by Sylvaner** [comment]
Réglé avec le fork normalement, plus qu'à le valider

**Comment by Esso1-jeedom** [comment]
ok je valide c bon
