### ISSUE TITLE
restart en boucle si <5% free sur /

### ISSUE THREAD

**Issue by fensoft** [NextDom/nextdom-core#1750]
**Décrivez le bug**
watchdog.php restart nextdom en boucle si <5% de libre (en particuliers tout les démons)

**Comment by Gis70** [comment]
Quel est l'intérêt de restart si on parle de la capacité du HDD ? cela a du sens pr la RAM mais pour le HDD je vois pas en quoi le restart va changer qqch

**Comment by Gis70** [comment]
je test avec 1% d'espace disque de libre. On verra le résultat.

**Comment by Gis70** [comment]
Pas de reboot de Nextdom ou des démons sur Nextdom v0.8 (develop) 
![image](https://user-images.githubusercontent.com/16589132/94838577-19963c80-0416-11eb-9db4-6cf7c1f59840.png)

.De plus, dans le watchdog sauf erreur de ma part on fait juste du vidage de tmp ou log
