### ISSUE TITLE
UI Scénario KO si bloc code

### ISSUE THREAD

**Issue by Gis70** [NextDom/nextdom-core#1758]
En 0.7 et 0.8 si un bloc code est présent dans un scénario, alors tout autre bloc ne sera pas affiché après un refresh de la page.

Exemple :

Je créer 2 blocs codes :  
![image](https://user-images.githubusercontent.com/16589132/94375478-33810800-0114-11eb-9aae-6c36ab7970fc.png)

Je save et refresh : 

![image](https://user-images.githubusercontent.com/16589132/94375482-3da30680-0114-11eb-811e-01c248ac6104.png)

Le code du 2ème sera bien exécuté mais il n'est plus affiché

**Comment by Censseo** [comment]
Il s'agit plus précisément d'un bloc code ajouté lorsqu'un autre bloc code est sélectionné
