### ISSUE TITLE
Progress bars CPU/MEM/SWAP/RAM

### ISSUE THREAD

**Issue by cyrilphoenix71** [NextDom/nextdom-core#208]
Les progress bars de la page admin ne sont pas dynamique, aujourd'hui ce sont des valeur bidons.
Il manque le code JS ou autres pour recuperer les valeurs réelles

**Comment by ColonelMoutarde** [comment]
voici la méthode js  : navigator.hardwareConcurrency

**Comment by byackee** [comment]
@colonelMoutard, pour moi ta fonction récupére les informations du navigateur et donc de la machine client.

Je clôture on enlève cette fonctionnalité car pas une priorité

**Comment by ColonelMoutarde** [comment]
effectivement, je suis un boulet

**Comment by ColonelMoutarde** [comment]
https://github.com/phpsysinfo/phpsysinfo à voir ci c'est bien, je n'ai jamais testé
