### ISSUE TITLE
Nextdom comptabilisé comme un Jeedom sur le market Jeedom

### ISSUE THREAD

**Issue by Ikes72000** [NextDom/nextdom-core#214]
Nextdom est comptabilisé comme un Jeedom sur le market Jeedom. Du coup, dans l'assistant Nextdom, si vous avez déjà 2 Jeedom, vous ne pouvez pas utiliser le market.

**Comment by byackee** [comment]
Je ne suis pas tout a fait d'accord car nextdom ne pourra jamais être reconnu par le market jeedom comme un nextdom (c'est géré du coté market).

Jeedom a banni le nom nextdom ca m'etonnerais qu'ils nous donne un acces libre au market ;)

Il faut allez dans le compte market et supprimer des "jeedom" pour réactiver l'acces. Si on a plusieurs VM pour test le market considère que l'on a plusieurs jeedom. Il faut donc dans ce cas en supprimer
![image](https://user-images.githubusercontent.com/4707496/46399692-c428d700-c6f8-11e8-9845-fdd05e4d32ef.png)

**Comment by ColonelMoutarde** [comment]
pour moi, ce n'est pas un bug

**Comment by Sylvaner** [comment]
Comme je l'ai dis, c'est normal :) Sinon faut prendre le support pour le market

**Comment by byackee** [comment]
On clôture
