### ISSUE TITLE
Améliorer la lisibilité des alertes

### ISSUE THREAD

**Issue by Ikes72000** [NextDom/nextdom-core#223]
![capture du 2018-10-03 22-50-53](https://user-images.githubusercontent.com/12248505/46439053-cf631d80-c75f-11e8-96ac-106a4b6de0bb.png)

Je trouve pas très lisible les alertes, à voir si possibilité d'améliorer ça.

**Comment by byackee** [comment]
![image](https://user-images.githubusercontent.com/4707496/46541440-5200ef80-c8bc-11e8-8121-3f8d8e3cc262.png)
c'est bizarre je trouve ca bien moi

**Comment by cyrilphoenix71** [comment]
Idem chez moi tout est ok, on close ?
