### ISSUE TITLE
création des icones manquantes pour les plugins

### ISSUE THREAD

**Issue by ColonelMoutarde** [NextDom/nextdom-core#232]
Pour l’alternative market.

**Comment by cyrilphoenix71** [comment]
Faudrait me les lister car normalement beaucoup ont déjà été faites donc c peut être juste le plugin qui n'as pas été mis à jour. 
D'ailleurs faudrait aussi se remettre sur ce gros chantier des plugins

**Comment by cyrilphoenix71** [comment]
Qui peut fournir la liste ?

**Comment by byackee** [comment]
issue a faire sur les plugins, rien a voir avec le core
