### ISSUE TITLE
rafraichissement

### ISSUE THREAD

**Issue by Esso1-jeedom** [NextDom/nextdom-core#236]
en ayant pris en compte le Bugg....
création de plugins 

Nota 1 plugin Widgets/ fenetre ...  avec 2 icones. - fonctionne parfaitement, Etat 0 etat 1

Nota 2 plugin Widget / temperature  numerique avec 3 etat  .
ne fonctionne pas en Equipement , par contre ce rafraichie bien  en commande . 
l'ecriture des commande et noir . contrairement a l'equipement.

on vois bien sur l'image l'icone fenetre  qui c ouvert , par contre la valeur temperature terasse , ne ce mets pas a jour, contrairement a la commande . 
![bug widget22222222222](https://user-images.githubusercontent.com/40739563/46552087-df9f0800-c8d9-11e8-897b-6c564e09110c.JPG)

 ...
Le rafraichissement fonctionne pour tout ce qui est etat , pas pour le numerique
donc Xiaomi detection / OK
Lumiere Zwave /OK
valeur temperature Xiaomi ou RFLINK / NOK
valeur recuperer ESP easy / OK

**Comment by ColonelMoutarde** [comment]
où en est ce bug ?

**Comment by cyrilphoenix71** [comment]
Ou en est ce bug ? :) @esso1-jeedom

**Comment by Esso1-jeedom** [comment]
le soucis etait le rafraichissement des valeurs temperature et l'affichage de l'historique. 
- le pb vient du parametrage de l'historique
en modifiant les valeur a 3 mois, et le type de lissage , RAS tout refonctionne
![capture- temp](https://user-images.githubusercontent.com/40739563/47700351-6ebbe900-dc16-11e8-8a43-2986fa88769a.JPG)
