### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by Sylvaner** [NextDom/nextdom-core#237]
Générer les icones pour la version mobile (et autres)
<link href="icon-152x152.png" sizes="152x152" rel="apple-touch-icon">

<link href="icon-144x144.png" sizes="144x144" rel="apple-touch-icon">

<link href="icon-120x120.png" sizes="120x120" rel="apple-touch-icon">

<link href="icon-114x114.png" sizes="114x114" rel="apple-touch-icon">

<link href="icon-76x76.png" sizes="76x76" rel="apple-touch-icon">

<link href="icon-72x72.png" sizes="72x72" rel="apple-touch-icon">

<link href="icon-57x57.png" sizes="57x57" rel="apple-touch-icon">

<link href="startup-image-1536x2008.png" media="(device-width: 768px) and (device-height: 1024px) and (orientation: portrait) and (-webkit-device-pixel-ratio: 2)" rel="apple-touch-startup-image">

<link href="startup-image-1496x2048.png" media="(device-width: 768px) and (device-height: 1024px) and (orientation: landscape) and (-webkit-device-pixel-ratio: 2)" rel="apple-touch-startup-image">

<link href="startup-image-768x1004.png" media="(device-width: 768px) and (device-height: 1024px) and (orientation: portrait) and (-webkit-device-pixel-ratio: 1)" rel="apple-touch-startup-image">

<link href="startup-image-748x1024.png" media="(device-width: 768px) and (device-height: 1024px) and (orientation: landscape) and (-webkit-device-pixel-ratio: 1)" rel="apple-touch-startup-image">

<link href="startup-image-640x1096.png" media="(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2)" rel="apple-touch-startup-image">

<link href="startup-image-640x920.png" media="(device-width: 320px) and (device-height: 480px) and (-webkit-device-pixel-ratio: 2)" rel="apple-touch-startup-image">

<link href="startup-image-320x460.png" media="(device-width: 320px) and (device-height: 480px) and (-webkit-device-pixel-ratio: 1)" rel="apple-touch-startup-image">

**Comment by Sylvaner** [comment]
icon-152x152.png

icon-144x144.png

icon-120x120.png

icon-114x114.png

icon-76x76.png

icon-72x72.png

icon-57x57.png

startup-image-1536x2008.png

startup-image-1496x2048.png

startup-image-768x1004.png

startup-image-748x1024.png

startup-image-640x1096.png

startup-image-640x920.png

startup-image-320x460.png

**Comment by cyrilphoenix71** [comment]
Fait dans PR (+ suppression anciennes icones)
