### ISSUE TITLE
Paramétrage du Market Nextdom dans NextDom

### ISSUE THREAD

**Issue by Astral0** [NextDom/nextdom-core#24]
Je n'arrive pas à accéder au paramétrage du "NextDom Market" (celui qui apparait directement dans une installation de NextDom à coté du Market de Jeedom.

En regardant de plus près, un menu paramètre apparait en haut à droite de l'écran du Market, alors que dans le Market NextDom il n'y a pas ce menu.

Market NextDom : 
![image](https://user-images.githubusercontent.com/39194968/42125647-31260058-7c7b-11e8-8781-cdc34898a51a.png)

Alternative Market for Jeedom : 
![image](https://user-images.githubusercontent.com/39194968/42125653-3600574a-7c7b-11e8-8ce9-d59c6519a810.png)

C'est le menu de configaration des sources que je cherche : 
![image](https://user-images.githubusercontent.com/39194968/42125670-6587397a-7c7b-11e8-8213-d51c764d4655.png)

**Comment by Sylvaner** [comment]
Quelles sources à rajouter ?

**Comment by Sylvaner** [comment]
Il est accessible dans la configuration du market qui se trouve dans l'onglet Mise à jour de la configuration générale.

**Comment by ColonelMoutarde** [comment]
Le bug est il toujours d'actualité. Il me semble que non

**Comment by ColonelMoutarde** [comment]
Je confirme qu'il est corrigé
