### ISSUE TITLE
"Afficher tout" n'affiche pas tout

### ISSUE THREAD

**Issue by Astral0** [NextDom/nextdom-core#241]
Quand on clique sur Afficher Tout, ça n'affiche que les objets par défaut (ceux qu'on a quand on clique sur l’icône Nextdom).

![image](https://user-images.githubusercontent.com/39194968/46575823-4cd79980-c9bd-11e8-9566-0513964c9dfd.png)

![image](https://user-images.githubusercontent.com/39194968/46575832-84dedc80-c9bd-11e8-8128-591e7c828ae6.png)

J'ai que "Cave" (qui contient RIG) mais j'ai pas tout.

**Comment by ColonelMoutarde** [comment]
Où en est-on de ce bug ?

**Comment by cyrilphoenix71** [comment]
Ce n'est pas vraiment un bug mais un problème de sémantique, afficher tout à pour action d'afficher le parent principal donc si des objet ne sont pas fillot de ce parent principal ils ne sont pas affichés 
C'est pour ça que je propose de plutôt avoir un affichage hiérarchisé de ce menu et alors afficher tout serait inutile

**Comment by Astral0** [comment]
Je comprends, mais du coup je propose de renommer l'entrée de menu en "Afficher l'objet parent" ou quelque chose comme ça.

**Comment by Sylvaner** [comment]
Faut juste trouver plus court pour que ça rentre dans la boite :)

**Comment by cyrilphoenix71** [comment]
Objet Parent ? 
Vue qu'on la le menu Objets

**Comment by cyrilphoenix71** [comment]
C résolu non ?

**Comment by Sylvaner** [comment]
Le texte a été changé, au pire on pourra l'améliorer plus tard :)
