### ISSUE TITLE
Plugin wifi smartplug : problème de rendu graphique du widget

### ISSUE THREAD

**Issue by Astral0** [NextDom/nextdom-core#242]
Ce plugin ne fonctionne pas correctement sous Nextdom (problème de rendu).

Sous Nextdom : 
![image](https://user-images.githubusercontent.com/39194968/46575843-c1aad380-c9bd-11e8-9c04-75f2bad35db9.png)

Sous Jeedom : 
![image](https://user-images.githubusercontent.com/39194968/46575851-d4bda380-c9bd-11e8-87d9-08f37ba06eb2.png)

C'est pas directement le Core de Nextdom mais il me semble que l'auteur du plugin fait partie de la team..

**Comment by byackee** [comment]
Tu as quoi dans la console dev?

**Comment by ColonelMoutarde** [comment]
on en est où ?
