### ISSUE TITLE
Message d'erreur dans les logs concernant l'accès au Market Nextdom

### ISSUE THREAD

**Issue by Astral0** [NextDom/nextdom-core#243]
Erreur curl sur : https://www.nextdom.com/market/core/api/api.php. Détail :Unknown SSL protocol error in connection to www.nextdom.com:443 

Pourtant, j'y accède bien. Bizarre !

**Comment by ColonelMoutarde** [comment]
si tu regarde bien il y a une redirection vers : http://nextdom-comingsoon.businesscatalyst.com/index.html/market/core/api/api.php
c'est qui businesscatalyst.com ?

**Comment by ColonelMoutarde** [comment]
apparemment, le domaine appartiens à adobe !

**Comment by slobberbone** [comment]
euh oui ce domaine n'a rien à voir avec nous ... nextdom.com ca appartient à une boite immobilière

**Comment by Astral0** [comment]
`root@nextdom:/var/www/html# grep -r "www.nextdom.com/market/core/api/api.php" *
DB_backup.sql:INSERT INTO `message` VALUES (43,'2018-08-16 00:00:03','scenario::0K6X1vy7DFFbkWeVZVIKBIWOLbqKVADn','scenario','Une commande du scénario : [Cave][RIG][Check] est introuvable',''),(44,'2018-08-18 18:02:17','nextdom::XS6kyuV96SctyPYylt49Xk0DIdJSygQt','nextdom','Erreur curl sur : https://www.nextdom.com/market/core/api/api.php. Détail :Unknown SSL protocol error in connection to www.nextdom.com:443 ',''),(46,'2018-08-25 22:29:58','mail::mpE5Ntef98aQmWiwjQ3w4RUHh3Udhg43','mail','Erreur exécution de la commande [Aucun][Courriel][Mail AA] : SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting',''),(49,'2018-08-30 18:43:53','mail::qJLCVt7PN7YCQE9MsOJw4S85pO638EcJ','mail','Erreur exécution de la commande [Aucun][Courriel][Mail AA] : SMTP Error: The following recipients failed: xxxxx.xxxxx@gmail.com: : Recipient address rejected: You have exceeded the limit of 200 messages per hour and per account. Please, re-try later.\r\n',''),(159,'2018-10-06 22:35:13','camera::8e9sZU12K9rLTcdJ4XcU8aauQgRj1MQG','camera','Attention : installation des dépendances lancée',''),(160,'2018-10-06 22:35:20','pushbullet::GbDtImUOL82nmMNPZLaLbZT156aOl0Pr','pushbullet','Erreur sur la fonction deamon_start du plugin : Return value of nextdom::retrievePidThread() must be of the type string, null returned',''),(161,'2018-10-06 22:40:09','openenocean::yDyN1OtRiXwQ0WCmiQTd6y5TpMpimHPh','openenocean','Attention : installation des dépendances lancée',''),(162,'2018-10-06 22:40:49','unableStartDeamon','rfxcom','Impossible de lancer le démon RFXcom, vérifiez le log rfxcmd',''),(163,'2018-10-06 22:45:37','openzwave::PU3KxWBV6kI3tRrfwpW2iQsVErAFgu84','openzwave','Attention : installation des dépendances lancée',''),(164,'2018-10-06 22:50:14','monitoring2::Xw1lVdZLbIXGYfBuD4vNR4USg4n5siL4','monitoring2','Attention : installation des dépendances lancée',''),(165,'2018-10-06 22:55:04','networks::eni5dT7snGFIHPmxKJTehfSX6Q6ZcRZB','networks','Attention : installation des dépendances lancée',''),(166,'2018-10-06 22:56:12','unableStartDeamon','openzwave','Impossible de lancer le démon openzwave, relancer le démon en debug et vérifiez la log',''),(169,'2018-10-07 00:33:03','cron::pvMTsRa9qPBfFvaICjv21q0S3fxlJUck','cron','[Erreur] Classe ou fonction non trouvée nextdom::updateMarket()',''),(170,'2018-10-08 22:00:23','newUpdate','update','De nouvelles mises à jour sont disponibles : nextdom,rfxcom,xiaomihome','');
root@nextdom:/var/www/html#
`

**Comment by Astral0** [comment]
root@nextdom:/var/www/html# grep -rl "www.nextdom.com" *
core/i18n/it_IT.json
core/i18n/en_US.json
core/i18n/pt_PT.json
core/i18n/es_ES.json
core/i18n/fr_FR.json
core/i18n/ja_JP.json
core/i18n/tr.json
core/i18n/de_DE.json
core/i18n/ru_RU.json
core/i18n/id_ID.json
DB_backup.sql
translations/id_ID.yml
translations/ja_JP.yml
translations/de_DE.yml
translations/it_IT.yml
translations/ru_RU.yml
translations/en_US.yml
translations/es_ES.yml
translations/pt_PT.yml
translations/fr_FR.yml
translations/tr.yml
var/cache/i18n/catalogue.fr_FR.NXhscRe.php

Il y a des remplacements jeedom vers nextdom un peu brutaux :)

**Comment by Astral0** [comment]
Bon en fait on peut fermer cette issue : je me suis aperçu que l'erreur était en fait dans les logs de mon jeedom. Et c'est arrivé dans Nextdom via la migration.
