### ISSUE TITLE
Error 500 dans les pages de configuration de différents plugins

### ISSUE THREAD

**Issue by Ikes72000** [NextDom/nextdom-core#25]
Suite à l'installation de différents Plugin (multiloc, héliotrope), j'ai une erreur 500 dans les pages de configuration de ces plugins, avec les erreurs suivantes dans le log php.

`[Sat Jun 30 13:05:17.481998 2018] [:error] [pid 6361] [client ::1:41470] PHP Fatal error: Uncaught Exception: Requ\xc3\xaate Ajax inconnue in /var/www/html/core/ajax/ajax-router.php:34
Stack trace:

#0 {main}

thrown in /var/www/html/core/ajax/ajax-router.php on line 34, referer: http://localhost/index.php?v=d&m=Multiloc&p=Multiloc
[Sat Jun 30 13:05:37.940536 2018] [:error] [pid 790] [client ::1:41478] PHP Fatal error: Uncaught Exception: Requ\xc3\xaate Ajax inconnue in /var/www/html/core/ajax/ajax-router.php:34
Stack trace:

#0 {main}

thrown in /var/www/html/core/ajax/ajax-router.php on line 34, referer: http://localhost/index.php?v=d&m=Multiloc&p=Multiloc`

**Comment by Sylvaner** [comment]
Corriger (htaccess)
