### ISSUE TITLE
Hauteur box

### ISSUE THREAD

**Issue by cyrilphoenix71** [NextDom/nextdom-core#259]
Dans les pages tools/note et tools/logs et tools/rapport la hauteur de la page (box) est fixée a 950 ou 1002px par quelquechose en dynamique dans un style="" et dans le html il n'y a rien de tout ca.

Or ainsi on voit mal le bouton retour et de plus dans tous les cas la page sait s'adapter automatiquement a la bonne hauteur.

Il est aussi ajouter un padding inutile

**Comment by Sylvaner** [comment]
`<div class="col-md-3 col-sm-4" id="div_displayLogList" style="padding-top: 5px;height: 692px;overflow: hidden auto;">`

**Comment by cyrilphoenix71** [comment]
Je comprend pas tu as ça dans le html ?

**Comment by Sylvaner** [comment]
oui, mais il faut pas regarder la source, il faut regarder le code avec les tools (google chrome developer tools par exemple)

**Comment by cyrilphoenix71** [comment]
Ça me dit pas d'où ça vient, sous atom je trouve pas qui ajoute ça dans le div
