### ISSUE TITLE
Deplier sous menu dashboard, vues, design etc

### ISSUE THREAD

**Issue by cyrilphoenix71** [NextDom/nextdom-core#261]
Pour ameliorer l'ergonomie il faudrait si menu de gauche replié que les sous menus dashboard, vues, design etc se deplient en automatique sur hover.

**Comment by Sylvaner** [comment]
Ca va être pratique sur téléphone portable :smile:

**Comment by cyrilphoenix71** [comment]
Ça changera rien non ? Sur téléphone tu déplie tu clic

**Comment by byackee** [comment]
Ça ajoute du js ou nécessite de modifier adminlte donc non
