### ISSUE TITLE
Mettre tous le skins adminlte au même standard

### ISSUE THREAD

**Issue by byackee** [NextDom/nextdom-core#282]

**Comment by Sylvaner** [comment]
c'est à dire ?

**Comment by cyrilphoenix71** [comment]
Le skin-nextdom est à jour, le skin-red aussi. 
Les autres non
Faut prendre la base de skin-nextdom et changer normalement juste les variables color au début

**Comment by byackee** [comment]
Nous allons passé sur une gestion de la couleur des themes par colorpicker
