### ISSUE TITLE
mauvais rendu de la scrollbar verticale

### ISSUE THREAD

**Issue by byackee** [NextDom/nextdom-core#286]
scrollbar trop grosse (elle apparait sur des écran de taille moyenne)
![image](https://user-images.githubusercontent.com/4707496/46736207-b6df8f80-cc98-11e8-8f01-48d955dceb45.png)

**Comment by cyrilphoenix71** [comment]
Faux mettre thumb width à 80px
Pour la hauteur je n'ai pas trouvé
