### ISSUE TITLE
boutons trop gros

### ISSUE THREAD

**Issue by byackee** [NextDom/nextdom-core#288]
réduire la taille de tous les boutons, les btn sont trop gros pour l'insterface nextdom:
- btn --> btn-sm
- btn-sm --> btn-xs
![image](https://user-images.githubusercontent.com/4707496/46736894-6f5a0300-cc9a-11e8-99a9-36706d12a8e2.png)

**Comment by cyrilphoenix71** [comment]
Avec ma pr tu peux clore non ?

**Comment by byackee** [comment]
Je clôture, c'est que mon avis
