### ISSUE TITLE
Modernisation du theme bootstrap

### ISSUE THREAD

**Issue by ColonelMoutarde** [NextDom/nextdom-core#29]
Je vous propose de moderniser l'interface avec l'utilisation de ceci.
https://cdn.rawgit.com/FezVrasta/bootstrap-material-design/gh-pages-v3/index.html

**Comment by ouquoi** [comment]
Yes bonne  idée !
Ca doit être bootstrap  3 c'est ca ? L effort est trop lourd pour passé a bootstrap 4 ?

**Comment by ColonelMoutarde** [comment]
Oui, le passage à BS4 est compliqué pour le moment. Avec cette lib, on conserve toutes les classes déjà présentes dans les vues.

**Comment by ouquoi** [comment]
Ok . Clair. Donc encore oui ca sera un élément différenciant.

**Comment by byackee** [comment]
j'ai fait un test avec cette adaptation et c'est pas gagné non plus :s

**Comment by slobberbone** [comment]
Autre piste : https://bootswatch.com/3/
Avec ce code là : https://github.com/slobberbone/Bootstrap-switch

**Comment by byackee** [comment]
La modification du CSS de nextdom permet l'utilisation des thèmes bootstrap 3 de base. Il suffit juste des les implémenter dans le core de nextdom

**Comment by byackee** [comment]
Les thèmes bootstrap sont à 95% compatible et la création du nouveau design prend la main

**Comment by byackee** [comment]
Je clôture dans quelques jours

**Comment by byackee** [comment]
plus de theme en tant que tel, on est sur la base de AdminLTE

Je cloture
