### ISSUE TITLE
Sauvegarder marche t-il ?

### ISSUE THREAD

**Issue by Astral0** [NextDom/nextdom-core#294]
Nouvelle installation, je clique sur créer un nouvel objet, j'arrive sur la page ci-dessous : 

![image](https://user-images.githubusercontent.com/39194968/46762526-94209b80-ccd7-11e8-84d9-9bb014e65490.png)

Je clique sur Sauvegarder en bas à droite.

Puis je vais dans le menu (Plugins / Gestion) et là il me dit que la page n'est pas enregistrée.

**Comment by byackee** [comment]
la sauvegarde se fait bien mais le chargement de la page provoque des changement de valeur dans les inputs. La fonction '$('#div_pageContainer').delegate('.objectAttr', 'change', function () {' est appelée 89 fois rien qu'au chargement de la page
Apres sauvegarde la page se recharge et notifie une nouvelle fois des 89 changements de valeurs donc si on quitte, Nextdom nous previent qu'on a modifié des valeurs sans sauvegarder

![image](https://user-images.githubusercontent.com/4707496/46950282-84f96f00-d084-11e8-918a-0292bf28f3df.png)

**Comment by Sylvaner** [comment]
Depuis le passage avec les modals, le problème n'est pas réglé ?

**Comment by slobberbone** [comment]
c'est quoi le "passages avec les modals" ?

**Comment by cyrilphoenix71** [comment]
Dans migration par exemple, le log s'affiche en modal plutôt que dans un cadre à côté

**Comment by cyrilphoenix71** [comment]
Du coup cest réglé ? @astral0

**Comment by Sylvaner** [comment]
J'ai testé c'est corrigé
