### ISSUE TITLE
Image des themes

### ISSUE THREAD

**Issue by cyrilphoenix71** [NextDom/nextdom-core#31]
De ce que j'avais pu voir dans la gestion des themes jeedom, il y avait des images dans les dossier de chaque theme.
Peut-on a la place gerer une variable themeSombre (true/false) et dans la gestion global choisir les image en fonction de cette variable ?
Dans jeedom, leur theme ont des dossier avec dedans des images qui remplace celle du theme de base
or pour les logo c nul.
Avec une variable on pourrait en autmatique choisir les logo fait pour fonc clair ou fond sombre

**Comment by byackee** [comment]
Il n'y a plus de themes, je cloture
