### ISSUE TITLE
Bug mode rescue

### ISSUE THREAD

**Issue by Sylvaner** [NextDom/nextdom-core#315]
Le menu apparait vide à gauche et en fenêtre réduite le menu du haut n'apparait pas
![capture d ecran 2018-10-16 a 08 10 51](https://user-images.githubusercontent.com/957104/46995936-1a474280-d11b-11e8-8577-18860b1fd24d.png)
![capture d ecran 2018-10-16 a 08 11 43](https://user-images.githubusercontent.com/957104/46995950-259a6e00-d11b-11e8-84cf-e8dc41ddbda0.png)

**Comment by cyrilphoenix71** [comment]
Mais c'est quoi ces screens ???? Logo, menu top :(

**Comment by byackee** [comment]
On s'en fou @cyrilphoenix71 !! c'est pas le probleme
