### ISSUE TITLE
Sélecteur couleur design

### ISSUE THREAD

**Issue by DanoneKiD** [NextDom/nextdom-core#319]
Le sélecteur de couleur dans la configuration d'un design ne fonctionne pas.
![image](https://user-images.githubusercontent.com/522809/47011983-7aea7580-d143-11e8-9380-8f93750a375b.png)

**Comment by byackee** [comment]
Je pense qu'il faut remettre le selecteur de base .

**Comment by DanoneKiD** [comment]
Pourquoi ?

**Comment by cyrilphoenix71** [comment]
Ya pas plutôt un pb de gen_assets ?

**Comment by DanoneKiD** [comment]
Ce rendu html est directement dans le **planHeader.configure.php** grrrr.
Apparemment le **utils.js** n'est pas appelé, la fonction    `$('.colorpick').colorpicker();` n'est pas appelée.

**Comment by byackee** [comment]
Du coup colorpicker c'est la merde à gérer entre les modals les trucs généré par du JavaScript et je ne sais quoi.

Je pense qu'il faudrait le virer

**Comment by Sylvaner** [comment]
Corrigé normalement

**Comment by byackee** [comment]
Vérifier, chez moi tout est ok
