### ISSUE TITLE
Message d'erreur durant la migration

### ISSUE THREAD

**Issue by Sylvaner** [NextDom/nextdom-core#323]
Petit message d'erreur, sans doute un slash qui manque quelque part
![capture d ecran 2018-10-16 a 18 23 58](https://user-images.githubusercontent.com/957104/47031693-b0598800-d170-11e8-8fe4-a45bd66201eb.png)

**Comment by byackee** [comment]
Le message cannot create directory? Sérieux ?

Ça dit juste que le répertoire est déjà créé

**Comment by Sylvaner** [comment]
Oui oui je vais régler ça vite fait, je voulais juste pas oublier
