### ISSUE TITLE
petits 404 sur derniere develop

### ISSUE THREAD

**Issue by byackee** [NextDom/nextdom-core#330]
![image](https://user-images.githubusercontent.com/4707496/47114642-af058980-d25c-11e8-9889-776694b55688.png)

**Comment by byackee** [comment]
sur plugin geotrav
![image](https://user-images.githubusercontent.com/4707496/47115865-2ee12300-d260-11e8-8b72-5be417e8bf77.png)

en réinstallant le plugin plus de pb

**Comment by Sylvaner** [comment]
Y a le nouveau gen_assets qui y a touché, mais pourrais-tu mettre le chemin complet de l'erreur ?

**Comment by Sylvaner** [comment]
C'est commit : https://github.com/Sylvaner/nextdom-core/commit/2ece3d9eb4928a761e95ba70126a97c7afedd0dd

**Comment by byackee** [comment]
Tout est ok
