### ISSUE TITLE
Check update core alors que update core non coché

### ISSUE THREAD

**Issue by byackee** [NextDom/nextdom-core#331]
core :0 mais check tout de meme, estce une erreur ?

```
[START UPDATE]
****Update from 3.3.3 (2018-10-17 22:37:10)****
Parameters : {"preUpdate":"0","backup::before":"0","plugins":"1","core":"0","force":"0","update::reapply":""}
Send begin of update event...
OK
Check update...--2018-10-17 22:37:10--  https://raw.githubusercontent.com/nextdom/core/beta/core/config/version
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.120.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.120.133|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-10-17 22:37:10 ERROR 404: Not Found.
OK
```

**Comment by Sylvaner** [comment]
Oui afin d'éviter les mises à jour avec jeedom, j'ai renvoyé vers le futur dépot public de nextdom, donc forcément non-trouvé

**Comment by byackee** [comment]
Oui ok mais le pb que je soulève c'est que j'ai demandé a ne pas mettre a jour le core mais c'est tout de même vérifier. Tu vois dans les paramètres le core est a 0.
Après si c'est qu'une vérif c'est pas grave

**Comment by Sylvaner** [comment]
Alors il ne met pas à jour le core, il va vérifier les sauvegardes en fait

**Comment by cyrilphoenix71** [comment]
Sauvegarde de quoi ?
