### ISSUE TITLE
pb avec racourci ctrl+s sur le panneau de gestion des plugins 

### ISSUE THREAD

**Issue by byackee** [NextDom/nextdom-core#337]
Voir si c'est un pb nextdom ou du plugin

![image](https://user-images.githubusercontent.com/4707496/47155427-fb94a780-d2e4-11e8-94c1-5de53d94a0c9.png)

**Comment by Sylvaner** [comment]
Même chose chez jeedom, je passe en amélioration du coup

**Comment by cyrilphoenix71** [comment]
plugin ou core ?

**Comment by Esso1-jeedom** [comment]
y a pas a sauvegarder a ce niveau donc on ne devrait meme pas avoir le droit de faire un CTRL+S

**Comment by ColonelMoutarde** [comment]
Cette erreur n’apparaitrai plus si il y avait une interface réclamant l'implémentation de la méthode save() . Si cette interface n'est pas implémentée, le core ne devrai même pas proposer de lance save()

**Comment by cyrilphoenix71** [comment]
Pr mergée
