### ISSUE TITLE
supprimé tout le code lié au cloud backup jeedom

### ISSUE THREAD

**Issue by byackee** [NextDom/nextdom-core#343]
![image](https://user-images.githubusercontent.com/4707496/47161494-71ebd680-d2f2-11e8-9a2f-06362fa7875f.png)

**Comment by byackee** [comment]
![image](https://user-images.githubusercontent.com/4707496/47161593-a495cf00-d2f2-11e8-9786-e1cb65828530.png)

**Comment by cyrilphoenix71** [comment]
Issue dupliqué non ?
