### ISSUE TITLE
Optimisation de la migration

### ISSUE THREAD

**Issue by Sylvaner** [NextDom/nextdom-core#349]
Pourrait-on désactiver le service cron pendant la migration ? ça pourrait éviter certaines erreurs à la migration.

**Comment by byackee** [comment]
Pour moi les crons et scénarios sont déjà désactivés et réactivé a la fin de la procédure

**Comment by byackee** [comment]
nextdom::stop()
nextdom::start()
![image](https://user-images.githubusercontent.com/4707496/47210794-31449980-d394-11e8-83c7-097ae4430ee1.png)
