### ISSUE TITLE
Backup Samba Syslog

### ISSUE THREAD

**Issue by DanoneKiD** [NextDom/nextdom-core#369]
Une fois le backup samba configuré impossible de lister les sav.
![image](https://user-images.githubusercontent.com/522809/47225753-23f0d480-d3bf-11e8-8143-ba1e609b4f68.png)

**Comment by ColonelMoutarde** [comment]
j'y connais rien en samba...

**Comment by slobberbone** [comment]
je regarde

**Comment by Sylvaner** [comment]
Le message en lui même n'est pas un problème mais ajoute une erreur du coup
