### ISSUE TITLE
Taille Box Mise à Jour

### ISSUE THREAD

**Issue by DanoneKiD** [NextDom/nextdom-core#374]
Les box des plugins n'ont pas la même hauteur
![image](https://user-images.githubusercontent.com/522809/47233363-c5355600-d3d2-11e8-894a-5ab97fc05bd9.png)

**Comment by slobberbone** [comment]
@DanoneKiD je ne re produis pas ... ect-ce toujours d'actualité ?

**Comment by cyrilphoenix71** [comment]
Je pense que oui en fait ça va dépendre de la taille du nom du plugin et de ta résolution d'écran 
Faudrait forcer une taillé mini sur 2lignes

**Comment by byackee** [comment]
Je vais faire un text-overflow-ellipsis

**Comment by cyrilphoenix71** [comment]
@byackee c'est a cloturer non ?

**Comment by DanoneKiD** [comment]
OK
