### ISSUE TITLE
pb d'affichage

### ISSUE THREAD

**Issue by byackee** [NextDom/nextdom-core#375]
un peu comme des modal apres chargement la box connexion remonte et une partie est tronquée
![image](https://user-images.githubusercontent.com/4707496/47240457-a80b8200-d3e8-11e8-82ed-0faaddf59589.png)

**Comment by slobberbone** [comment]
tu peux préciser comment tu obtiens ce soucis stp ?

**Comment by Sylvaner** [comment]
Pas de problème de mon côté

**Comment by Sylvaner** [comment]
Tu bluffes Martoni
