### ISSUE TITLE
Clic sur preview d'une skin ne le selctionne pas

### ISSUE THREAD

**Issue by cyrilphoenix71** [NextDom/nextdom-core#392]

**Comment by byackee** [comment]
Le changement a la volée ne fonctionne plus depuis la modification du changement des thèmes
Le changement ne se fait plus partie JavaScript mais au chargement de la page .
Ça évite pleins de bugs

Il faut simplement rafraîchir la page.

**Comment by cyrilphoenix71** [comment]
Je ne parlais pas de ca :)
Tu peux choisir le theme via le radio button mais pas en cliquant sur la preview dessus c'est perturbant

**Comment by byackee** [comment]
Ça n'est plus d'actualité avec le colorpicker
