### ISSUE TITLE
Bad display on refresh page plugins

### ISSUE THREAD

**Issue by slobberbone** [NextDom/nextdom-core#397]
To reproduce :+1: Change a log level on a plugin, then refresh (F5)
![change log then f5](https://user-images.githubusercontent.com/3833875/47282913-3d716680-d5e1-11e8-9523-6161564f63d1.png)

**Comment by cyrilphoenix71** [comment]
ET de toute facon cette page est a reprendre pour mettre la gestion en fab

**Comment by byackee** [comment]
Cette page n'est plus d'actualité

Nouvelle page:
![image](https://user-images.githubusercontent.com/4707496/47296781-9f4ac400-d613-11e8-966c-ee2614fd36bb.png)
