### ISSUE TITLE
The title of modals is splitted

### ISSUE THREAD

**Issue by slobberbone** [NextDom/nextdom-core#398]
In KNX plugin but probably not only, the title bar of modals are hidden by
![head s modal cut](https://user-images.githubusercontent.com/3833875/47283014-b5d82780-d5e1-11e8-9ec2-f84f2486db63.png)
 the main bar :

**Comment by cyrilphoenix71** [comment]
Il y a deja une issue sur ce bug je crois @byackee

**Comment by byackee** [comment]
même chose que https://github.com/Sylvaner/nextdom-core/issues/375

**Comment by Sylvaner** [comment]
Comme pour l'autre : Tu bluffes Martoni

**Comment by byackee** [comment]
Ca se produit chez moi lorsque le navigateur est en mode fenetre (petite taille).
- Tu ouvre un modal qui est plus grand que le fenetre du navigateur
- Tu agrandi ta fenetre navigateur
- Si tu ne rafraichit pas ta page et que tu ouvre a nouveau un modal, il se positionne mal

A mon avis il caclul la position en fonction de la taille de la fenetre, et lors d'un redimensionnement cette taille n'est pas remis a jour

**Comment by byackee** [comment]
code dans utils.js

```
height: ((jQuery(window).height() - 100) < 700) ? jQuery(window).height() - 100 : 700,
width: ((jQuery(window).width() - 100) < 900) ? (jQuery(window).width() - 100) : 900,
```

**Comment by byackee** [comment]
Zindex de 9999 sur modal
