### ISSUE TITLE
Affichage heure non mise à jour (Desktop)

### ISSUE THREAD

**Issue by nemocaledonie** [NextDom/nextdom-core#4]
Bonjour à tous,
Après avoir mis la dernière version de NextDom (0.1.1), l'heure en haut droite (Desktop) ne s'affiche plus (00.00 1 janvier 1970, soit l'heure UNIX). Sous la version 0.0.6 ça s'affichait normalement.
Dans l'onglet "Santé" l'heure est OK, mais j'ai toujours "Mise à jour" en rouge (et une erreur si l'on lance la mise à jour).
Par ailleurs le plugin ESP-Easy ne fonctionne pas dans cette version (le démon ne se lance pas). (peut-être dois-je ouvrir un autre ticket ...) mais JEEDOUINO marche maintenant  :-).
Bon dimanche.

**Comment by slobberbone** [comment]
@nemocaledonie nous avons corrigé ce point merci.
