### ISSUE TITLE
Lists are not displayed as expecting

### ISSUE THREAD

**Issue by slobberbone** [NextDom/nextdom-core#400]
The trouble appear with ARC plugin, but it probably because of NextDom css classes.
![list bad displayed](https://user-images.githubusercontent.com/3833875/47283112-254e1700-d5e2-11e8-9dcf-e5635021066c.png)

**Comment by cyrilphoenix71** [comment]
Globalement je pense qu'il faudrait que ce soit le core qui gere cette page en prenant les infos du plugin, pour que ce soit maintenable et standardisé

**Comment by cyrilphoenix71** [comment]
@byackee une petite mise a jour du plugin pour virer les br et mettre poil de css comme utilisation box ?

**Comment by byackee** [comment]
![image](https://user-images.githubusercontent.com/4707496/52466191-cd7fef80-2b81-11e9-962d-a4134e31e5e0.png)

je cloture
