### ISSUE TITLE
Image Avatar par défaut

### ISSUE THREAD

**Issue by DanoneKiD** [NextDom/nextdom-core#420]
Lors de la migration l'image n'est plus trouvée
`/public/img/profils/avatar_00.jpg`
Le fichier *.jpg n'existe plus il doir être en *.png
![image](https://user-images.githubusercontent.com/522809/47386552-321b5980-d70d-11e8-96f5-e6029efdd72c.png)

**Comment by cyrilphoenix71** [comment]
sur installe neuve ? car si la reponse est non je pense qu'on peut clore l'issue

**Comment by DanoneKiD** [comment]
Sur migration d'un sav

**Comment by byackee** [comment]
@DanoneKiD toujours d'actualité?
