### ISSUE TITLE
Regrouper les personnalisations

### ISSUE THREAD

**Issue by byackee** [NextDom/nextdom-core#433]
Aujourd'hui il existe des personnalisations de core (thème et tuiles) et des personnalisations de profils (thèmes graphiques, mobile, etc...)

Il faut les regrouper dans la page custom

**Comment by cyrilphoenix71** [comment]
Mais cela sous-entend que les custom qui etait dans profil deviennent globale et non plus attachée a un user ?
Ou alors on fait un tab dedié ?

**Comment by byackee** [comment]
je pensais plutot que toutes les personalisation devienne lié a l'user mais regroupé dans la page custom

**Comment by cyrilphoenix71** [comment]
Alors dans ce cas c parfait :)
Mais comment gere tu la dépendance au user ?

**Comment by cyrilphoenix71** [comment]
Dans ce cas pk pas regrouper profil et custom et y avoir accès par menu admin ou clic avatar ?? :)

**Comment by Gis70** [comment]
ca c'est fait sur https://github.com/NextDom/nextdom-core/issues/478
