### ISSUE TITLE
Dans theme proposer choix logo

### ISSUE THREAD

**Issue by cyrilphoenix71** [NextDom/nextdom-core#438]
Comme page profil, faire un choix possible de logo

**Comment by byackee** [comment]
je suis pas trop d'accord, il faut laisser la marque Nextdom.

**Comment by cyrilphoenix71** [comment]
Par défaut tu l'aura déjà ;)
Ensuite tu laisse le choix de changer de logo NextDom (tout noir, tout blanc, tout bleu, mix1, mix2 etc) j'ai eu cette idée car le logo actuel si tu choisis couleur thème gris foncé bah tu cache la moitié du logo 
Et de 2 tu offre la possibilité au gens de personnaliser leur domotique :)
