### ISSUE TITLE
Firefox

### ISSUE THREAD

**Issue by Esso1-jeedom** [NextDom/nextdom-core#46]
erreur sur la connexion firefox. pb login.

 aucun soucis sur chrome

**Comment by byackee** [comment]
Je ne rencontre pas ce pb avec firefox, peux tu retenter avec une nouvelle installation ?

**Comment by Esso1-jeedom** [comment]
j'ai pourtant tjrs le pb avec une nouvelle install. le mot de passe marche mais je vois un message d'erreur du MDP en rouge, nextdom s'ouvre quand meme, parfois si je refais ca passe pas du 1er coup et le second ou le 3eme essai ca marche . si besoins je ferais une vidéo. sous chrome aucun soucis ca roule sans pb , sans message d'erreur- voir la video que je t'ai laisser sur le tchat

**Comment by Sylvaner** [comment]
Peux-tu réessayer, il y avait un problème de double envoie d'une requête ajax ?

**Comment by Esso1-jeedom** [comment]
il faut que je réinstall  nextdom ?   pour faire l'essai

**Comment by Sylvaner** [comment]
Je vais essayer
