### ISSUE TITLE
Raffraichessement UI du plugin Wifi Smartplug

### ISSUE THREAD

**Issue by Astral0** [NextDom/nextdom-core#463]
Voici la tuile du plugin Wifi Smartplug : 

![image](https://user-images.githubusercontent.com/39194968/47577605-9b86ac80-d947-11e8-9bc7-e453d9a399f5.png)

Quand on clique sur la prise électrique, cela arrête la prise et l’icône devient gris foncé, ou cela l'allume et elle redevient blanche. Ça c'est sous Jeedom :) Sous Nextdom, l’icône ne change pas, par contre l'action est bien lancée. Pour que l’icône change, il faut rafraichir la page.

A noter que je suis persuadé que ce bug est récent (il y a quelques jours, l’icône changeait bien).

**Comment by Sylvaner** [comment]
Bug du plugin corrigé
