### ISSUE TITLE
pb creation 1er vue

### ISSUE THREAD

**Issue by Esso1-jeedom** [NextDom/nextdom-core#48]
il n'est pas possible de créer une vue pour la 1er fois . pas de message création .

**Comment by ColonelMoutarde** [comment]
Peux+tu préciser le problème ?

**Comment by Esso1-jeedom** [comment]
ben tu n'as aucune création possible.  lors de la mise en place de la 1er vue, tu as sous jeedom un message, cliquer ici pour créer la 1er vue. ici rien ne ce passe. cela a aussi été remarqué pour le reste ( plan /plan 3D) aucune création possible. 
surement une broutille ...

**Comment by byackee** [comment]
Je vois d'où ça vient, je ferais une maj prochainement

**Comment by byackee** [comment]
fait j'ai ajouté un lien "afficher tout" pour chaque menu
