### ISSUE TITLE
Npm pour les dépendances

### ISSUE THREAD

**Issue by Sylvaner** [NextDom/nextdom-core#489]
Doit-on utiliser NPM pour les dépendances liées au Javascript ?

Composer fournit très peu de dépendances hors PHP.
C'est pourquoi il faut utiliser un autre gestionnaire de packet si on veut virer le répertoire 3rdparty lié au Javascript
L'idée est également est de mettre l'ensemble des dépendances dans vendor/node_modules et pas à la racine du projet afin de limiter les sous-répertoires.

[![](https://api.gh-polls.com/poll/01CV1QVB2VGE60GX7FKGTDWYZK/Oui%20pour%20npm%20dans%20ces%20conditions)](https://api.gh-polls.com/poll/01CV1QVB2VGE60GX7FKGTDWYZK/Oui%20pour%20npm%20dans%20ces%20conditions/vote)
[![](https://api.gh-polls.com/poll/01CV1QVB2VGE60GX7FKGTDWYZK/Non%2C%203rdparty%20c'est%20cool)](https://api.gh-polls.com/poll/01CV1QVB2VGE60GX7FKGTDWYZK/Non%2C%203rdparty%20c'est%20cool/vote)

**Comment by slobberbone** [comment]
Si c'est lié au javascript pourquoi ne pas utiliser bower en lieu et place de npm ?
Il me semble que c'est plus front-end et optimisé pour. Je vois également un autre argument c'est que npm gère ces modules au mm endroit  pour tout, n'y a-t-il pas un risque avec des plugin utilisant nodejs qui sont succeptible d'installer des dépendances et compromettre les version de NextDom ?

**Comment by ColonelMoutarde** [comment]
npm sera nécessaire de toute façon car sass est arrêté avec ruby pour être transféré vers node. Quelle partie de 3dParty veux tu transferer ?

**Comment by Astral0** [comment]
Pour ce qui est du paquet Debian, aucun gestionnaire autre que debian ne sera accepté de toute façon. La règle Debian c'est : un paquet installé un jour doit avoir le même comportement si installé un autre jour, sauf dépendances Debian qui bouge. Donc exit l'installation dynamique de paquet par PIP, NPM, Composer ou autre, ca n'est pas compatible. 
Donc concernant le paquet, l'installation sera faite à la génération du paquet et tous les fichiers seront empactés dans le .deb.
La logique : si une dépendance a besoin d'être mise à jour, on met à jour le paquet deb.

**Comment by slobberbone** [comment]
J'entends bien @Astral0 , mais les plugins pour le moment, font ce qu'ils veulent ...

**Comment by Astral0** [comment]
oui mais moi je dis qu'on coupe pas à casser quelques branches : Nextdom c'est un Core sécurisé avec des plugins certifiés. je pense qu'on vise pas à accepter tous les plugins merdiques de la communauté Jeedom.
Et si Nextdom prend alors on arrivera à imposer quelques bonnes pratiques de développement pour les plugins.

**Comment by Sylvaner** [comment]
Ca ne change rien à l'histoire du package, c'est toujours faisable en l'état.

Une explication plus complète
Composer sert principalement aux dépendances/librairies du backend (php)
Il va mettre toutes ses dépendances dans le répertoire vendor
Npm sert principalement aux dépendances/librairies du frontend (js)
Il va mettre toutes ses dépendances dans le répertoire node_modules

Le but de l'utilisation de ces gestionnaires de dépendances est de supprimer le répertoire 3rdparty et d'avoir une gestion propre des dépendances (et éviter les copier coller hasardeux).

Mais le soucis, c'est que 2 répertoires seraient utilisés, ce qui ne serait pas super étant donné qu'on essaie de faire le ménage.
D'où l'idée de mettre les dépendances de npm dans le répertoire vendor (-> vendor/node_modules) et ainsi avoir 1 seul répertoire au lieu 3rdparty, vendor

**Comment by slobberbone** [comment]
En gros, on utiliserait ceci : https://github.com/eloquent/composer-npm-bridge ? @Sylvaner

**Comment by Astral0** [comment]
Avoir un seul répertoire me semble mieux.
Est-ce que ces dépendances évoluent souvent ? Quel risque prend-on à les intégrer au paquet .deb ?
Et que si une dépendance doit être mise à jour, un nouveau paquet doive être construit.

**Comment by Sylvaner** [comment]
Elles vont évoluer au début quand on va les intégrer, ensuite non, le composer plutot.

**Comment by edgd1er** [comment]
L'idée est elle de commencer avec des repertoires vendor et vendir/node_modules vides et d'y installer les bibliothèques requises via composer et son plugin npm bridge ?

Questions complémentaires: 
* Est que la gestion des librairies chargés par les plugin change ? ( centralisation des libs ou séparation des libs nextdom et plugins comme actuellement )
* Comment/est il possible d'assurer la compatibilité des libs en cas de montée de versions avec les plugin existants ?
