### ISSUE TITLE
Le changement du mot "jeedom" vers "nextdom" est un peu trop violent

### ISSUE THREAD

**Issue by Astral0** [NextDom/nextdom-core#49]
Si je regarde le fichier :
docs/fr_FR/changelog.md

Sous 2.4 on trouve :

-   Suppression du fail2ban (car facilement contournable en envoyant une
    fausse adresse ip), cela permet d’accélérer NextDom

Le mot NextDom a du remplacer le mot Jeedom suite à une opération de remplacement brutal (un gros sed ?).
Pour éviter les problèmes avec Jeedom SAS, il faut conserver ici le terme Jeedom car ces parties de changelog concernen Jeedom (v2.4) et non Nextdom.

On peut les conserver mais il faut laisser Jeedom.

D'ailleurs, je préconise qu'on reparte sur un changelog Nextdom et qu'on n'écrive plus dans celui de Jeedom.

**Comment by Sylvaner** [comment]
Ou virer les docs ?

**Comment by Astral0** [comment]
Possible aussi. On n'a aucune obligation d'embarquer les docs quand on redistribue un logiciel libre.

**Comment by Sylvaner** [comment]
On peut pas créer un petit sondage sous github vite fait ?

**Comment by Astral0** [comment]
mouarf :)

**Comment by byackee** [comment]
suppression des docs et on en parle plus
