### ISSUE TITLE
Auto generated NextDom documentation

### ISSUE THREAD

**Issue by slobberbone** [NextDom/nextdom-core#491]
The goal : have an documentation to help developer to develop/fix NextDom

Several solutions exists : 

- PHPDox : http://phpdox.de
- APIGen : https://github.com/ApiGen/ApiGen

**Comment by Sylvaner** [comment]
J'utilise Doxygen d'habitude, mais phpdox à l'air plus sexy.

**Comment by slobberbone** [comment]
J'ai intégrer des analyseur de code etc, bon faudra surement revoir la config de certains outils mais le gros y est.

**Comment by slobberbone** [comment]
Dossier docs créé mais pas archivé. Un fichier index.xhtml est dispo à la racine de docs. Il suffit de lancer scripts/gen_docs.sh

**Comment by slobberbone** [comment]
![doc1](https://user-images.githubusercontent.com/3833875/47734021-cf284600-dc69-11e8-881b-25b2a27ed89d.png)
![doc2](https://user-images.githubusercontent.com/3833875/47734028-d18aa000-dc69-11e8-962a-1c1ce892dc53.png)

**Comment by slobberbone** [comment]
Il semble qu'on ait un probleme de taille concernant phpMetrics ayant une fonction dupliquée avec NextDom mais le problème peut arriver avec n'importe quelle dépendances.
Pourquoi ne pas utiliser : https://github.com/bamarni/composer-bin-plugin afin de séparer les dépendances utiles pour la génération de doc (et surement aussi d'autres pour d'autres outils)
qui ne seront pas utilisés dans le context NextDom ?

**Comment by cyrilphoenix71** [comment]
On close ?
