### ISSUE TITLE
Tuile qui reste "rouge" (timeout) même quand elles recoivent des valeurs

### ISSUE THREAD

**Issue by Astral0** [NextDom/nextdom-core#492]
Après une réinstallation, j'ai effectué une restauration.
Une nuit après, la moitié des capteurs sont toujours en mode "timeout" (tuile rouge). En revanche, quand on passe le curseur sur la tuile, il dit bien que la valeur a été récupérée récemment... mais la valeur n'est pas actualisée dans la tuile.

Si on fait : 
php /var/www/html/script/clean_cache.php

cela vide le cache (toutes les valeurs passent à 0) mais elles se réactualisent bien au bout de quelques minutes.

**Comment by cyrilphoenix71** [comment]
Donc PR avec clean cache en fin de migration ?

**Comment by byackee** [comment]
Fait comprendre pourquoi 😁

**Comment by cyrilphoenix71** [comment]
Que fait-on ?

**Comment by Sylvaner** [comment]
Est-ce que le fichier cache est bien déplacé ? Car on l'a mit dans var

**Comment by Astral0** [comment]
Le problème est global et n'est pas lié à la migration.
En effet, j'ai mis un timeout à 60 min dans Alarmes, qui fait que la tuile passe rouge si on pas de valeur reçue depius plus d'une heure. Or, avec les capteurs Xiaomi, il arrive très souvent que les capteurs n'envoie plus signe de vie pendant plus d'une heure, notamment les capteurs d'ouverture (par contre si on ouvre la fenetre ou la porte, le capteur envoie immédiatement l'info, donc c'est nickel).

Bref, des capteurs "rouges" qui reçoivent une valeur (température, ouverture de porte, ...) ont bien leur valeur modifiée mais la tuile reste rouge.

**Comment by cyrilphoenix71** [comment]
@Astral0 tjs d'actualité ?

**Comment by Gis70** [comment]
ok sur e8d6b0770e60d9bd3fbb375f4b8f65f132e8a86f
