### ISSUE TITLE
Raffraichissement widget Virtuel

### ISSUE THREAD

**Issue by Astral0** [NextDom/nextdom-core#493]
J'ai un virtuel qui me sert à remonter des informations : 

![image](https://user-images.githubusercontent.com/39194968/47723385-b3667500-dc54-11e8-9c0a-9c00fd24a7ce.png)

Lorsque j'ajoute des lignes d'info, les cases Afficher et Historiser sont cochées mais ces lignes ne s'affichent pas : 

![image](https://user-images.githubusercontent.com/39194968/47723451-d85ae800-dc54-11e8-9c8f-78752b996f45.png)

Résultat (même après un F5 pour rafraichir la page) : 

![image](https://user-images.githubusercontent.com/39194968/47723468-df81f600-dc54-11e8-9c03-a19c890168c4.png)

**Comment by Astral0** [comment]
Tiens, autre bug : lorsque la page "Commandes" est ouverte sur un onglet et que la rouvre depuis un autre onglet, toutes les lignes (avec status "affiché") sont dupliquées : 

![image](https://user-images.githubusercontent.com/39194968/47723643-38ea2500-dc55-11e8-97d6-48055db15575.png)

**Comment by Astral0** [comment]
Alors du nouveau, en fait les infos sont bien affichées mais elles sont masquées par la taille de la tuile : 

![image](https://user-images.githubusercontent.com/39194968/47723909-d2b1d200-dc55-11e8-875e-b8f9993c1cac.png)

Pourtant, on ne peut pas dire que cette tuile manque de place !

**Comment by Astral0** [comment]
Bon, en résumé y a deux bugs : 
- les informations ne se répartissent pas dans la tuile et la tuile ne s’agrandit pas automatiquement
- quand on ouvre deux fois la page "Commande", les commandes sont doublonnées

**Comment by cyrilphoenix71** [comment]
le pt 1 c deja le cas avec jeetruc, ca vient des tuiles qui sont de la daube

**Comment by Esso1-jeedom** [comment]
j'ai des pb avec mes virtuelle créer avec images , alors qu'avec les icones cela fonctionne .

**Comment by cyrilphoenix71** [comment]
on est est ou de cette issue ? pb de base reglé non ?

**Comment by Astral0** [comment]
Il reste les deux bugs :
1/ tuile ne se redimensionne pas toute seule
2/ les commandes se dupliquent toutes seules quand on ouvre plusieurs fois la page.

**Comment by Sylvaner** [comment]
https://github.com/Sylvaner/nextdom-core/pull/630
