### ISSUE TITLE
Market : liste différente entre un Jeedom et un Nextdom

### ISSUE THREAD

**Issue by Astral0** [NextDom/nextdom-core#508]
Quand je clique sur Market dans un Jeedom, j'ai ca : 

![image](https://user-images.githubusercontent.com/39194968/47848823-cfdaec80-ddcf-11e8-9034-de8ff6e92550.png)

et depuis Nextdom j'ai ca : 

![image](https://user-images.githubusercontent.com/39194968/47848844-dec19f00-ddcf-11e8-99a8-111038d8b198.png)

Normalement on devrait avoir la même chose, non ?

**Comment by cyrilphoenix71** [comment]
sous ton screen nextdom tu as les nouveautés par catgorie 
ton screen jeedom les nouveautés de tous types

**Comment by cyrilphoenix71** [comment]
Peut-on confirmer par comparaison de code ?

**Comment by byackee** [comment]
devrait etre reglé maintenant, c'était la fonction bootstrap-rating qui merdait. 

A confirmer

**Comment by Sylvaner** [comment]
Non, aucune idée du pourquoi du comment, il y a a une catégorie par défaut, je ne trouve pas pourquoi.

**Comment by cyrilphoenix71** [comment]
@Astral0 ca doit etre fixé dans la branche UI

**Comment by Gis70** [comment]
de base on n'arrive pas sur top et nouveauté, il faut sélectionner une autre catégorie puis revenir sur top et nouveauté.
