### ISSUE TITLE
Fichier  nextdom-core/scripts/phpdoc.sh

### ISSUE THREAD

**Issue by Astral0** [NextDom/nextdom-core#510]
Ce fichier fait un mkdir /usr/nextdom

C'est bizarre comme stratégie (et comme chemin).
Le paquet Debian fait un répertoire /usr/share/nextdom.

**Comment by slobberbone** [comment]
ca sent le copier/coller foireux ...

**Comment by slobberbone** [comment]
@Sylvaner est-ce toi qui a fais ce script et si oui, à quoi sert-il ?
