### ISSUE TITLE
Fenêtre de log (plugin xiaomi mais peut être d'autres) impossible à fermer

### ISSUE THREAD

**Issue by Astral0** [NextDom/nextdom-core#523]
La fenêtre est trop haute et on n'a pas accès à la croix.
Comme elle n'est pas déplaçable, on ne peut pas la fermer.

![image](https://user-images.githubusercontent.com/39194968/47951126-b6b37680-df5c-11e8-84fb-5853f712b3b9.png)

**Comment by cyrilphoenix71** [comment]
résolu non ?
