### ISSUE TITLE
Stratégie de dimensionnement des tuiles

### ISSUE THREAD

**Issue by Astral0** [NextDom/nextdom-core#526]
Sur la v0.0.2 : 

![image](https://user-images.githubusercontent.com/39194968/47951861-11ea6680-df67-11e8-8ad1-58a09132b877.png)

Sur la branche de @byackee (mais date surement d'avant) : 

![image](https://user-images.githubusercontent.com/39194968/47951871-36ded980-df67-11e8-9e9a-863713710aa2.png)

La stratégie pour le détecteur de fumée est pas top.

**Comment by cyrilphoenix71** [comment]
duplqiuée : https://github.com/Sylvaner/nextdom-core/issues/490
