### ISSUE TITLE
FAB filtre qui filtre mal

### ISSUE THREAD

**Issue by Astral0** [NextDom/nextdom-core#527]
J'ai une prise TP-Link (plugin wifi smartplug) qui est taguée en "Energie" : 

![image](https://user-images.githubusercontent.com/39194968/47952157-5aa41e80-df6b-11e8-8f97-8fe681e23f70.png)

Quand j'utilise le FAB pour filtrer les objets "Energie" la prise n'apparait pas

En revanche, la prise CoolCAM en Zwave est bien apparente, elle :)

**Comment by cyrilphoenix71** [comment]
Ta prise est dans cuisine non ?

**Comment by Astral0** [comment]
Oui l'image correspond pas :)

donc voici la cuisine avant filtre : 

![image](https://user-images.githubusercontent.com/39194968/48011965-3ab65b80-e121-11e8-8822-2d8b2b1e6a22.png)

et après filtre via le FAB : 

![image](https://user-images.githubusercontent.com/39194968/48011987-43a72d00-e121-11e8-8be7-7ae4e8473fbe.png)

Y a bien un problème de filtre mais uniquement de ce module car la prise Zwave et le virtuel est bien filtré.

**Comment by cyrilphoenix71** [comment]
Lié au plugin je pense

**Comment by Sylvaner** [comment]
*toussoute* Plugin :)

**Comment by byackee** [comment]
on cloture car rien a voir avec le core ?

**Comment by Astral0** [comment]
Toujours le problème en 0.0.3.

**Comment by Astral0** [comment]
Pas lié au Core ? Sauf que ca marche sur Jeedom : 

![image](https://user-images.githubusercontent.com/39194968/48773289-39f7fa80-ecc7-11e8-93dd-ca8d7b0857c7.png)

je rouvre..

**Comment by byackee** [comment]
Bon je confirme c'est pas lié au plugin ... j'ai regardé le code c'est ok.

A approfondir

**Comment by Astral0** [comment]
Pb tjr présent en 0.0.6.
