### ISSUE TITLE
Mise à jour : lien renvoyant vers une page vide

### ISSUE THREAD

**Issue by Astral0** [NextDom/nextdom-core#54]
Quand on clique sur Mise à jour, il y a une phrase en haut du pavé de mise à jour rouge :
_Avant toute mise à jour, merci de consulter la note de version du core de NextDom ici_

Le lien ici renvoie vers la page https://nextdom.github.io/core/fr_FR/noteVersion
mais cette page est vide.

**Comment by ColonelMoutarde** [comment]
fait
