### ISSUE TITLE
phpBar insupprimable

### ISSUE THREAD

**Issue by cyrilphoenix71** [NextDom/nextdom-core#553]
![image](https://user-images.githubusercontent.com/18350629/48068490-3ea2b600-e1d3-11e8-8b4d-7ea37063179d.png)
![image](https://user-images.githubusercontent.com/18350629/48068605-832e5180-e1d3-11e8-8b68-d790f02d3e14.png)

**Comment by Sylvaner** [comment]
Tu bluffes

**Comment by byackee** [comment]
pas le pb chez moi ....

**Comment by cyrilphoenix71** [comment]
je vous jure que non
