### ISSUE TITLE
Message dashboard tout neuf

### ISSUE THREAD

**Issue by cyrilphoenix71** [NextDom/nextdom-core#57]
A la premiere entrée sur le dashboard, un message nous previent qu'aucun object racine n'existe et nous propose 2 liens jeedom dont 1 avec les pack...
> Re formuler le texte et pointer vers un wiki nextdom (knwoledge base)

**Comment by byackee** [comment]
Fait, en attendant d'avoir notre propre doc, j'ai mis un lien vers la création d'objets
