### ISSUE TITLE
Padding page équipement d'un plugin

### ISSUE THREAD

**Issue by DanoneKiD** [NextDom/nextdom-core#577]
Problème de paddin sur les plugins.
La barre permettant d'accéder aux équipements du plugin masque le bouton sauvegarder (partiellement) mais surtout le bouton de **suppression** d'une commande.
![image](https://user-images.githubusercontent.com/522809/48129908-3b6b0100-e28b-11e8-9c40-eb007809b6a7.png)

**Comment by cyrilphoenix71** [comment]
cette issue va etre difficile a gerer car propre aux plugins non ?

**Comment by Sylvaner** [comment]
je regarderai
