### ISSUE TITLE
Gestion update Core Nextdom pour beta publique

### ISSUE THREAD

**Issue by cyrilphoenix71** [NextDom/nextdom-core#578]
Fonctionnel mais a tester 

Pour la beta publique 0.1, il serait bien d'avoir le systeme de mise a jour du core fonctionnel
- Methode1 branche stable
- Methode2 branche develop
- Detection auto d'un changement sur 1 des branche
![image](https://user-images.githubusercontent.com/18350629/48132022-63aa2e00-e292-11e8-92a8-fdb00aa2d377.png)

- Bug changelog
![image](https://user-images.githubusercontent.com/18350629/48132032-6c9aff80-e292-11e8-9e5c-192304d1bd5e.png)

**Comment by Astral0** [comment]
Pour la méthode 1, il faut régler https://github.com/NextDom/nextdom-core/issues/566

**Comment by byackee** [comment]
On clos? la maj du core se fait pour un user lambda. Pour un dev il sait comment faire

**Comment by slobberbone** [comment]
Fixed in 0.3.0

**Comment by cyrilphoenix71** [comment]
on clos ?
