### ISSUE TITLE
Log scénario vide

### ISSUE THREAD

**Issue by DanoneKiD** [NextDom/nextdom-core#591]
L'affichage des log s'un scénario est vide à l'affichage.
Par contre il est OK quand on le télécharge
![image](https://user-images.githubusercontent.com/522809/48183016-a5d47d80-e32d-11e8-8c1a-e0fab66c84bc.png)

**Comment by Sylvaner** [comment]
Tu ne dois pas avoir la dernière version suite au changement de l'emplacement des logs.
Peux-tu essayer de lancer la commande 
```
bash scripts/update_log_path.sh
```
?

**Comment by cyrilphoenix71** [comment]
ca fonctionne je clos
