### ISSUE TITLE
Bouton "welcome page"

### ISSUE THREAD

**Issue by ColonelMoutarde** [NextDom/nextdom-core#597]
Le bouton welcom page ne fonctionne que après avoir rafraichi la page:
url : /index.php?v=d&p=administration

**Comment by cyrilphoenix71** [comment]
moi ca fonctionne

**Comment by ColonelMoutarde** [comment]
tu est obligé de rafraichir pour que ça fonctionne

**Comment by ColonelMoutarde** [comment]
si tu passe par le menu non

**Comment by DanoneKiD** [comment]
Corrigé dans la https://github.com/Sylvaner/nextdom-core/pull/595
