### ISSUE TITLE
Refonte des css

### ISSUE THREAD

**Issue by ColonelMoutarde** [NextDom/nextdom-core#6]
Les css sont généralement inscrite directement dans le html. 
Il faut:

- trouver une façon de l'extraire entièrement pour le réécrire dans un fichier .css 
- Transformer ce css en sass (facile) et l'éclater correctement pour que chaque type de zone css soit dans un fichier .sass
- refondre le system de loading des css (personnellement, je ne suis pas certain que ce soit nécessaire de les faire charger par PHP)

**Comment by byackee** [comment]
La transformation en sass est ok, la migration des styles vers sass se fait au fil des l'eau.
Pour le chargement des css c'est géré avec twig

**Comment by ColonelMoutarde** [comment]
fait
