### ISSUE TITLE
Configuration plugin n'ouvre pas la bonne modal

### ISSUE THREAD

**Issue by byackee** [NextDom/nextdom-core#61]
Lorsque l'on clique sur configuration du plugin on tombe sur la liste des plugin et market et non sur la config du plugin
![image](https://user-images.githubusercontent.com/4707496/45146465-34f4d600-b1c3-11e8-9f2f-e71e4b5b9aa9.png)

![image](https://user-images.githubusercontent.com/4707496/45146496-4807a600-b1c3-11e8-81bb-b782abeea0b0.png)

**Comment by Sylvaner** [comment]
Corrigé
