### ISSUE TITLE
pb design 

### ISSUE THREAD

**Issue by Esso1-jeedom** [NextDom/nextdom-core#63]
aprés une migration  : 
sur la versions de base 

**var planHeader = jQuery.parseJSON("[{\"id\":\"3\",\"name\":\"PAGE2\"},{\"id\":\"5\",\"name\":\"page3\"},{\"id\":\"7\",\"name\":\"page6\"},{\"id\":\"8\",\"name\":\"page7\"},{\"id\":\"9\",\"name\":\"page8\"},{\"id\":\"10\",\"name\":\"page11\"},{\"id\":\"11\",\"name\":\"11\"},{\"id\":\"12\",\"name\":\"nouveau \"},{\"id\":\"14\",\"name\":\"camera\"},{\"id\":\"15\",\"name\":\"cam2\"},{\"id\":\"16\",\"name\":\"bassin2\"},{\"id\":\"17\",\"name\":\"ELEC\"}]");**  

cela semble en plus bloquer le menu de gauche . pas d'accés au sous menu 
![sans titre 2](https://user-images.githubusercontent.com/40739563/45149058-feba5500-b1c8-11e8-90ef-082a3985718a.jpg)

sur la version de syvlain  asset . il n'y a plus le message d'erreur mais cela ne fonctionne pas . 
![capture](https://user-images.githubusercontent.com/40739563/45148893-979ca080-b1c8-11e8-9804-cb2f33a5ed96.JPG)

**Comment by Sylvaner** [comment]
Corrigé
