### ISSUE TITLE
bugg scénario

### ISSUE THREAD

**Issue by Esso1-jeedom** [NextDom/nextdom-core#636]
![capture scenario](https://user-images.githubusercontent.com/40739563/48356960-bcfdcd00-e697-11e8-9852-9cf2d9ce1f22.JPG)
![bugg scenario2](https://user-images.githubusercontent.com/40739563/48356963-bec79080-e697-11e8-9fa1-912a2bacd4a0.JPG)

le bouton pour selectionner les commande ne fonctionne pas .

**Comment by Sylvaner** [comment]
C'est bon

**Comment by Esso1-jeedom** [comment]
c ok pour moi
