### ISSUE TITLE
pb nouveau élement sur le dashboard

### ISSUE THREAD

**Issue by Esso1-jeedom** [NextDom/nextdom-core#64]
aprés une migration. 
recuperation d'un elements ESPeasy nouveau . 
l'inclusion est ok .
![dash 1](https://user-images.githubusercontent.com/40739563/45151279-28c24600-b1ce-11e8-97ad-d52a772ed19f.JPG)

mais il ne remonte pas sur le dashboard maison
![dash2](https://user-images.githubusercontent.com/40739563/45151307-3972bc00-b1ce-11e8-826b-670d7995548e.JPG)

**Comment by byackee** [comment]
juste pour être sur, tu as choisi l'objet bureau et tu regarde l'objet maison;

Pour moi ça ne peux pas focntionner :)

**Comment by Esso1-jeedom** [comment]
je suis un boulet .. donc y a pas de pb ... ca fonctionne
