### ISSUE TITLE
Dashboard ne se rafraichit pas

### ISSUE THREAD

**Issue by byackee** [NextDom/nextdom-core#65]
les widgets ne change pas d'état et ne se mettent pas a our lors d'un changement de valeur

**Comment by Esso1-jeedom** [comment]
cela semble fonctionné normalement .  testé sous dashboard, et sous design

**Comment by byackee** [comment]
Cela se produit avec des images issues du plugin widget. Lorsque les widget sont équipés des icones du core ca fonctionne.
A priori sur jeedom 3.3.3 meme probleme

On attend pour le moment

**Comment by byackee** [comment]
A priori ca viendrait du code propre au widget:
'jeedom.cmd'

Il faudrait trouver une solution pour interfacer cette commande
![image](https://user-images.githubusercontent.com/4707496/45800588-a6e41980-bcb1-11e8-86a6-9d5e30d8f96e.png)

**Comment by Sylvaner** [comment]
normalement elle est interfacé 

https://github.com/Sylvaner/nextdom-core/blob/develop/core/js/jeedom.class.js

**Comment by Esso1-jeedom** [comment]
pour moi c bon ... a voir avec byackee
