### ISSUE TITLE
bouton log sur les plugins qui ne s'affichent pas

### ISSUE THREAD

**Issue by Esso1-jeedom** [NextDom/nextdom-core#652]
sur pas mal de plugins , on ne vois pas les 3 boutons des plugins
dependance demon et log du plugins.
ou bien les bouton disparaissent .
exemple plugins xiaomi
plugin rflink 

![captureplug 2](https://user-images.githubusercontent.com/40739563/48471647-aa4cda80-e7f4-11e8-9959-b3981db505ce.JPG)
![capture plug](https://user-images.githubusercontent.com/40739563/48471650-aa4cda80-e7f4-11e8-8cd5-9a776c2e297c.JPG)

**Comment by byackee** [comment]
plus d'actualité sur v0.1.2
