### ISSUE TITLE
clic sur globalSummary affiche aucun objet

### ISSUE THREAD

**Issue by cyrilphoenix71** [NextDom/nextdom-core#663]
![image](https://user-images.githubusercontent.com/18350629/48514203-19aae480-e85e-11e8-806b-cc4e0f2c5ec3.png)

**Comment by DanoneKiD** [comment]
Chez moi ça marche.
Si j'ai des lumières allumées et que je clique sur l'icone "ampoule" j'arrive bien sur le dashboard filtré avec mes lumières.

**Comment by byackee** [comment]
ca fonctionne aussi pour moi
