### ISSUE TITLE
sh: 1: cannot create /var/log/nextdom/migration: Directory nonexistent

### ISSUE THREAD

**Issue by edgd1er** [NextDom/nextdom-core#689]
https://github.com/Sylvaner/nextdom-core/blob/6b50b46cf7a149d3291f50840fba2edebdd8cbbf/install/migrate_jeedom_to_nextdom.php#L78

Est il possible d'ajouter le recursive pour créer les repertoires intermédiaires manquants (nextdom dans mon cas).
sh: 1: cannot create /var/log/nextdom/migration: Directory nonexistent

**Comment by slobberbone** [comment]
Fixed in https://github.com/NextDom/nextdom-core/issues/960
