### ISSUE TITLE
Icones résumé mobile

### ISSUE THREAD

**Issue by DanoneKiD** [NextDom/nextdom-core#694]
Il manque certains icônes dans le résumé en mode mobile. Les classes `nextdom- *` qui ne doivent pas être dans le css mobile.
![image](https://user-images.githubusercontent.com/522809/48698501-8a982680-ebe7-11e8-968c-c97715bc0be3.png)

**Comment by cyrilphoenix71** [comment]
Avec la future suppression de ce mode mobile on supprime ?
