### ISSUE TITLE
transparence des equipement widget sur design

### ISSUE THREAD

**Issue by Esso1-jeedom** [NextDom/nextdom-core#70]
la transparence ne fonctionne pas . 
![capture](https://user-images.githubusercontent.com/40739563/45231552-9b195000-b2cc-11e8-8228-c08777a56bfb.JPG)

**Comment by Esso1-jeedom** [comment]
nota aussi les widgets ne fonctionne pas .

**Comment by byackee** [comment]
le pb vient du nouveau template nextdom pour les widgets. avec le template jeedom ça fonctionne.

Je vais les séparer et gérer les widgets différement entre le dashboard et le design

**Comment by byackee** [comment]
Je suspend la pesonnalisation des widgets pour le moment, on retrouve donc le meme comportement que jeedom
