### ISSUE TITLE
pb scénario 

### ISSUE THREAD

**Issue by Esso1-jeedom** [NextDom/nextdom-core#71]
le dernier scénario n'est pas exécuté en cron . 

si je créer un scénario nommé 1 . il ne ce lance pas.
si j'en crée un  N°2   c le N° 1 qui du coups fonctionne
si je créer un N° 3 c le N°1 et le N°2 qui fonctionne
si je supprime le 1 et le 3 .. le 2 ne marche plus .

**Comment by Sylvaner** [comment]
![capture d ecran 2018-09-26 a 07 42 25](https://user-images.githubusercontent.com/957104/46059502-c8d11680-c15f-11e8-9eed-a5d150e35532.png)
![capture d ecran 2018-09-26 a 07 42 30](https://user-images.githubusercontent.com/957104/46059505-ccfd3400-c15f-11e8-83fa-bffb215d49fe.png)
![capture d ecran 2018-09-26 a 07 43 08](https://user-images.githubusercontent.com/957104/46059515-d5ee0580-c15f-11e8-801d-83cfffea09d4.png)

Je n'ai pas le soucis dès le premier scénario

**Comment by Esso1-jeedom** [comment]
une sauvegarde ou une création ? j'ai tjrs le meme pb , branche develop sur RPI 3B

**Comment by Esso1-jeedom** [comment]
tjrs le pb
a mon avis je dois pas etre le seul ... si tu as besoins je peux te laisser accés a nextdom .. faudra pas jouer avec les  lumiere lol ..

![capture-cron](https://user-images.githubusercontent.com/40739563/46063502-4bac9e00-c16d-11e8-88e1-b270694553fc.JPG)

**Comment by Sylvaner** [comment]
Si t'as un envirronement de test, je veux bien un backup avec les 3 scénarios qui merdent

**Comment by Esso1-jeedom** [comment]
en fait y a pas de scénario qui merde , c'est tjrs le dernier créer .
en création je te fais un backup nextdom . avec le bug
