### ISSUE TITLE
configurations des alertes dans log_admin

### ISSUE THREAD

**Issue by cyrilphoenix71** [NextDom/nextdom-core#713]
la fonction jeedom 
![image](https://user-images.githubusercontent.com/18350629/48810054-7eb37e00-ed27-11e8-88cb-fb8c5fb2a509.png)

est devenue
![image](https://user-images.githubusercontent.com/18350629/48810047-765b4300-ed27-11e8-8774-8b49390af2ce.png)

Mais aucune alerte n'est ajouter à la page log_admin

il semble deja manquer :
![image](https://user-images.githubusercontent.com/18350629/48810094-b8848480-ed27-11e8-8315-8a8f8c5c1c08.png)
que l'on retrouve aussi peut etre pour rien dans update_admin :
![image](https://user-images.githubusercontent.com/18350629/48810114-d7831680-ed27-11e8-86ff-ce08c23f7a2c.png)

ENFIN cette partie alertes n'a pas vraiment ca place ici non ? > eqLogic.html.twig ?

**Comment by Sylvaner** [comment]
Il manque la déclaration global de NEXTDOM_CONFIG

**Comment by Sylvaner** [comment]
A corriger après la PR de Colonel

**Comment by ColonelMoutarde** [comment]
pr validé
