### ISSUE TITLE
Checkbox plugins

### ISSUE THREAD

**Issue by DanoneKiD** [NextDom/nextdom-core#721]
Le css sur les checkbox a impacté les plugins le `top: 7px;` pose problème

![image](https://user-images.githubusercontent.com/522809/48902048-a7d32c00-ee57-11e8-923c-83dda81374fc.png)

**Comment by cyrilphoenix71** [comment]
Issue #749?

**Comment by cyrilphoenix71** [comment]
@DanoneKiD tjs présent ?

**Comment by Gis70** [comment]
Pas revu ce pb sur la dernière dev

**Comment by DanoneKiD** [comment]
Tjs KO pour moi 
![image](https://user-images.githubusercontent.com/522809/54719333-e3a7a500-4b5c-11e9-98da-fbb83cdbfd7c.png)

**Comment by Gis70** [comment]
OK validé
