### ISSUE TITLE
erreur SQL apres migration

### ISSUE THREAD

**Issue by byackee** [NextDom/nextdom-core#73]
![image](https://user-images.githubusercontent.com/4707496/45585461-e7741980-b8e4-11e8-884d-a4caf8dbbcc2.png)

**Comment by edgd1er** [comment]
une relance php todo.php permet de corriger le pb. je suppose a implementer dans le process de migration.

**Comment by byackee** [comment]
meme avec une fresh install, j'ai la meme erreur

**Comment by byackee** [comment]
corrigé
