### ISSUE TITLE
menu configuration commande 

### ISSUE THREAD

**Issue by Esso1-jeedom** [NextDom/nextdom-core#744]
il n'est plus possible de parametrer les commandes.
voir l'image du bugg.

![capture](https://user-images.githubusercontent.com/40739563/49272499-0b6de280-f472-11e8-8d39-abd44e016c8b.JPG)

**Comment by cyrilphoenix71** [comment]
Modif comnencée dans la branche feature/issue744_cmdModale
- revue complete de la page
- bugs divers

Il reste comme bug le IF de la ligne 649, 661, 673, 685
Et le IF ligne 721
