### ISSUE TITLE
Version non fonctionnelle suite à migration de 0.0.2 vers la dernière develop

### ISSUE THREAD

**Issue by Astral0** [NextDom/nextdom-core#754]
Suite à l'installation de la dernière develop + migration depuis Nextdom 0.0.2, plusieurs bugs bloquants sont apparus.

Message d'erreur : 

![image](https://user-images.githubusercontent.com/39194968/49337783-17e06f80-f619-11e8-9d27-ac4d3a354dc6.png)

Plugin Xiaomi refuse de démarrer : 

![image](https://user-images.githubusercontent.com/39194968/49337792-45c5b400-f619-11e8-9725-9a3a13575634.png)

Log "cron" : 

![image](https://user-images.githubusercontent.com/39194968/49337808-73aaf880-f619-11e8-9ac4-26d3dcd9d9c5.png)

Log "cron_execution" : 

![image](https://user-images.githubusercontent.com/39194968/49337831-f59b2180-f619-11e8-8ba8-5d031058d31a.png)

Plugin AlternativeMarket non trouvé : 

![image](https://user-images.githubusercontent.com/39194968/49337812-90473080-f619-11e8-849e-2430b070d602.png)

Actuellement, plus rien ne fonctionne.

**Comment by byackee** [comment]
@Astral0 Le plugin Altermarket n'est pas importé lors de la migration (repertoire). Par contre Il faut virer les entrées dans la BDD pour le pas avoir les erreurs.

**Comment by Astral0** [comment]
Tu peux donner les commande SQL ? (et il faudra les intégrer au processus de migration ?)

**Comment by Sylvaner** [comment]
```
DELETE FROM `update` WHERE name = 'AlternativeMarketForJeedom';
```

**Comment by Astral0** [comment]
Je ferme car je n'ai plus eu de pb avec les dernières develop.
