### ISSUE TITLE
Pb avec plugin Pushbullet

### ISSUE THREAD

**Issue by Astral0** [NextDom/nextdom-core#755]
Dans les logs on a ca : 

![image](https://user-images.githubusercontent.com/39194968/49337819-be2c7500-f619-11e8-8363-5df4bf175b5c.png)

**Comment by ColonelMoutarde** [comment]
shell_exec

(PHP 4, PHP 5, PHP 7)

shell_exec — Exécute une commande via le Shell et retourne le résultat sous forme de chaîne. le shell dans ce cas ne retourne pas de valeur, c'est pour ça.
