### ISSUE TITLE
Bug plugin Xiaomi ne détecte pas une 2ieme gateway

### ISSUE THREAD

**Issue by Astral0** [NextDom/nextdom-core#764]
Ajouter une 2ieme gateway se passe comme ajouter la première : on va dans l'apps MiHome, on ajoute la gateway, on passe en mode "developpeur" pour activer l'accès depuis le réseau local, et un token apparait à l'écran.
Dans Jeedom / Nextdom, il faut que le plugin xiaomihome soit installé et fonctionnel mais il n'y a rien à faire pour "ajouter" une gateway. Celle ci apparait toute seule dans la liste des objets sous "Mes Aqara". C'est ce qu'il se passe sous Jeedom : elle apparait bien au bout de quelques minutes.

Sous Nextdom (testé avec 0.0.4 et develop), même après une nuit, la gateway n'apparait pas.
Le plugin est celui qui est sur https://github.com/Astral0/plugin_xiaomihome
(dans Jeedom comme dans Nextdom - à noter que sous Nextdom, ce plugin arrive via une migration et non une installation par le paquet .deb nextdom-plugin-xiaomihome ou par le github).

Dans les logs du plugins xiaomi, on voit des échanges en provenance de la passerelle : 

`root@stretch-nextdom-dev:/var/log/nextdom# tail -30 xiaomihome |grep 192.168.50.23 [2018-12-04 08:11:41][DEBUG] : {u'short_id': u'0', u'cmd': u'heartbeat', u'token': u'0q8QrZT5C94ifzfl', u'sid': u '7811dcdec359', u'model': u'gateway', u'data': u'{"ip":"192.168.50.23"}'} [2018-12-04 08:11:41][DEBUG] : Send to jeedom : {u'devices': {u'aquara_7811dcdec359': {'short_id': u'0', 'cmd': u 'heartbeat', 'source': '192.168.50.23', 'token': u'0q8QrZT5C94ifzfl', 'sid': u'7811dcdec359', 'model': u'gateway' , 'data': {u'ip': u'192.168.50.23'}}}} [2018-12-04 08:11:51][DEBUG] : {u'short_id': u'0', u'cmd': u'heartbeat', u'token': u'9ePaH2RDiz49CSdk', u'sid': u '7811dcdec359', u'model': u'gateway', u'data': u'{"ip":"192.168.50.23"}'} [2018-12-04 08:11:51][DEBUG] : Send to jeedom : {u'devices': {u'aquara_7811dcdec359': {'short_id': u'0', 'cmd': u 'heartbeat', 'source': '192.168.50.23', 'token': u'9ePaH2RDiz49CSdk', 'sid': u'7811dcdec359', 'model': u'gateway' , 'data': {u'ip': u'192.168.50.23'}}}} 
root@stretch-nextdom-dev:/var/log/nextdom#`

(l'ip de la 2ième gateway est bien 192.168.50.23).

Le répertoire tmp : 

```
root@stretch-nextdom-dev:~# ls -altr /tmp/nextdom
total 648
-rwxrwxrwx   1 www-data www-data     19 déc.   3 13:54 started
drwxrwxrwx   2 www-data www-data     40 déc.   3 13:54 camera
drwxrwxrwx   2 www-data www-data     40 déc.   3 13:54 openenocean
drwxrwxrwx   3 www-data www-data     60 déc.   3 13:54 ftpd
drwxrwxrwx   2 www-data www-data     40 déc.   3 13:54 rfxcom
drwxrwxrwx   2 www-data www-data     40 déc.   3 13:56 openzwave
drwxrwxrwx   2 www-data www-data     60 déc.   3 21:38 broadlink
drwxrwxrwx   2 www-data www-data     40 déc.   3 21:46 monitoring2
drwxrwxrwx   2 www-data www-data     60 déc.   3 21:49 xiaomihome
drwxrwxrwx   3 www-data www-data     60 déc.   3 22:00 github
drwxrwxrwx  13 www-data www-data    320 déc.   3 23:05 .
drwxrwxrwx 207 www-data www-data   4140 déc.   4 00:02 cache
drwxrwxrwx   2 www-data www-data     40 déc.   4 08:10 networks
-rwxrwxrwx   1 www-data www-data      5 déc.   4 08:13 jeeCron.pid
-rw-rw-rw-   1 www-data www-data      0 déc.   4 08:13 event_cache_lock
drwxrwxrwx  10 www-data www-data 651264 déc.   4 08:13 ..
root@stretch-nextdom-dev:~# 
```

**Comment by Astral0** [comment]
Une piste : https://www.jeedom.com/forum/viewtopic.php?f=182&t=23382&start=5360#p674605

**Comment by Astral0** [comment]
Je confirme ce moyen de contournement : dans le serveur DHCP, j'ai mis l'ip de la gateway à .223 (au lieu de .23) et elle est apparue automatiquement partout !

**Comment by cyrilphoenix71** [comment]
@astral on fait quoi ?

**Comment by slobberbone** [comment]
Bug du firmeware Xiaomi
