### ISSUE TITLE
Install: Etape 4: plugin populaires vides

### ISSUE THREAD

**Issue by edgd1er** [NextDom/nextdom-core#77]
suite a une install docker, dans l'étape 4 du welcome, il est indiqué

Agrémentez votre NextDom !
Par l'installation de plugins dont voici les plus utilisés :

mais rien n'est listé.
c'est secondaire, mais pourquoi l'indiquer si ce n'est pas disponible.

**Comment by byackee** [comment]
Oui c'est un bon point, on souhaite le faire mais c'est pas encore disponible
