### ISSUE TITLE
Background modal config plugin

### ISSUE THREAD

**Issue by DanoneKiD** [NextDom/nextdom-core#795]
Il faudrait changer la couleur du fond.
Blanc sur Blanc...
![image](https://user-images.githubusercontent.com/522809/49944910-ddfe4b80-feeb-11e8-86de-ce8d21a80220.png)

**Comment by cyrilphoenix71** [comment]
Faudrait surtout passer les modales en Bootstrap

**Comment by byackee** [comment]
fait
![image](https://user-images.githubusercontent.com/4707496/52472005-9239ec80-2b92-11e9-843c-5e476b40d869.png)
