### ISSUE TITLE
Plugin Xiaomi : les équipements "disparaissent" de manière aléatoire

### ISSUE THREAD

**Issue by Astral0** [NextDom/nextdom-core#799]
Sur la capture ci-dessous : à gauche = v0.0.2, milieu =v0.0.6, à droite = develop.
Jamais de problème en 0.0.2
Même version du plugin Xiaomi
Même config (capteur, etc.) car provient dans les 3 cas d'une migration.
Je considère donc que le problème vient de chez nous.

![image](https://user-images.githubusercontent.com/39194968/50056816-5a9a5f80-0162-11e9-9981-ef85c6913e44.png)

**Comment by Astral0** [comment]
J'ajoute que les équipements restent bien visibles et actifs dans le dashboard.

**Comment by cyrilphoenix71** [comment]
tjs présent ? @Astral0

**Comment by Gis70** [comment]
tout va bien chez moi sur la branche dev 
![image](https://user-images.githubusercontent.com/16589132/54163908-e1f22900-445a-11e9-8268-4c634b9064ad.png)
