### ISSUE TITLE
Pb sur changement de thème (customisation)

### ISSUE THREAD

**Issue by noodom** [NextDom/nextdom-core#8]
J'avais sélectionné le mode Dark suite à mon install.

Je retourne dans le menu de customisation : le mode White est sélectionné.
Lorsque je sélectionne le mode Dark ou Mix, la sélection revient automatiquement sur white.

Sinon, je n'ai pas trouvé de logique sur la prise en compte du changement de mode :
- La plupart du temps, le changement de mode n'est pas possible
- J'ai réussi ("aléatoirement" et très rarement) à modifier le thème (parfois même sans sauvegarder, prise en compte immédiate au clic)

NextDom v0.1.2

**Comment by slobberbone** [comment]
Ce bug est corrigé pour la prochaine version
