### ISSUE TITLE
pb menu interaction

### ISSUE THREAD

**Issue by Esso1-jeedom** [NextDom/nextdom-core#80]
le menu interaction n'est pas accéssible.
1er pb comme pour les scénario une page blanche.
aprés n F5
![bugg interaction](https://user-images.githubusercontent.com/40739563/45595838-20c68b00-b9b2-11e8-9b96-f3bcbd92680c.JPG)

**Comment by byackee** [comment]
fix with PR: https://github.com/Sylvaner/nextdom-core/pull/91
