### ISSUE TITLE
Résumé global non mis  a jour dans le header

### ISSUE THREAD

**Issue by cyrilphoenix71** [NextDom/nextdom-core#808]
Voici un screenshot qui montre que apres allumage des lamps le résumé n'est plus a jour :
![image](https://user-images.githubusercontent.com/18350629/50448749-376e6d80-0923-11e9-9c50-b210a8c7151d.png)

**Comment by Gis70** [comment]
@cyrilphoenix71 pour moi c'est fixé ça marche sur la develop, je clos.
