### ISSUE TITLE
probleme installation plugins nextdom

### ISSUE THREAD

**Issue by Esso1-jeedom** [NextDom/nextdom-core#81]
lors de l'installation de plugins un 1er message s'affiche 
erreur les dépôts github sont désactivés
![bug plug 2](https://user-images.githubusercontent.com/40739563/45595953-8f0c4d00-b9b4-11e8-8ad6-1e5091de169a.JPG)

l'installation du plugins. 
![bug plug 3](https://user-images.githubusercontent.com/40739563/45595963-b7944700-b9b4-11e8-8365-bfaecaee977d.JPG)

le plugins est introuvable  mème en passant par le bouton de configuration
![bugg plug 1](https://user-images.githubusercontent.com/40739563/45595967-ce3a9e00-b9b4-11e8-8314-be362a20f10e.JPG)

**Comment by byackee** [comment]
Pour test va dans le menu administration puis mise a jour
Tu as un onglet Nextdom market. Tu coché les sources drafts et stable

**Comment by Esso1-jeedom** [comment]
c'etait deja coché

**Comment by Sylvaner** [comment]
Normalement c'est réglé avec les différentes corrections du week end

**Comment by Esso1-jeedom** [comment]
oui c bon, il faut penser a activer github, et activer le market nextdon . et c bon
