### ISSUE TITLE
renvoi vers la page de connexion en cas d'expiration de la durée de vie de la session

### ISSUE THREAD

**Issue by perarem** [NextDom/nextdom-core#828]
Lors de l'expiration d'une session, plutôt que d'afficher un ou plusieurs message(s) d'erreur (Token d'accès invalide), ne pourrait-on pas renvoyer directement vers la page de connexion ?

**Comment by cyrilphoenix71** [comment]
Ne fonctionne pas chez je r'ouvre l'issue

**Comment by perarem** [comment]
En fait, il faut faire un F5 pour avoir la page de connexion lors d'une session expirée

**Comment by cyrilphoenix71** [comment]
bah justement la PR qui a été validée pour cette issue corrigeait ca, mais chez moi ca ne fonctionne pas donc j'ai réouvert

**Comment by perarem** [comment]
Bon, pour ma part, je n'ai plus de problème sur les dernières develop.

**Comment by byackee** [comment]
on cloture ?

**Comment by Gis70** [comment]
Comment on test ? time out de combien de temps ?

**Comment by perarem** [comment]
@Gis70 tu définis la durée de vie de la session dans "administration & réglages" => "Général"
![Screen Shot 03-14-19 at 12 23 AM](https://user-images.githubusercontent.com/10147784/54321033-92913180-45ef-11e9-84b1-8d35a9b3c55d.PNG)
Puis tu ouvres une session sans cocher la case "Se souvenir de moi" et normalement au bout de x heure(s) la moindre action te renvoi sur la mire de connexion

**Comment by Gis70** [comment]
OK pr moi validé
