### ISSUE TITLE
Modal historique ne s'ouvre pas

### ISSUE THREAD

**Issue by byackee** [NextDom/nextdom-core#836]
Lors d'un clique sur une commande de type info dans un widget la modal historique ne s'ouvre pas.

Porobleme de javascript ?

**Comment by slobberbone** [comment]
![probleme historique](https://user-images.githubusercontent.com/3833875/51486278-95666780-1da0-11e9-822b-d271e5bbf772.png)
Tu as bien le même comportement @byackee ?

**Comment by Sylvaner** [comment]
Alors après recherche rien n'a été touché sur cette partie.

Le fichier générant cet affichage est celui-ci : https://github.com/Sylvaner/nextdom-core/blob/develop/core/template/dashboard/cmd.info.numeric.default.html

Le label avec l'unité sont définis ici : https://github.com/Sylvaner/nextdom-core/blob/develop/core/template/dashboard/cmd.info.numeric.default.html#L93

L'évènement lié à l'affichage de l'historique est ici : https://github.com/Sylvaner/nextdom-core/blob/develop/core/template/dashboard/cmd.info.numeric.default.html#L16

Ce que l'on peut remarquer, c'est que le code n'a pas été modifié et que le label n'a pas spécifiquement d'évènement défini.

Donc si il y a eu un changement, c'est lié à la librairie highcharts qui a en effet évoluée, mais Jeedom aussi a effectué ce changement.
Peut être peut-on ajouter un évènement sur le label, mais la documentation n'indique rien pour faire ça : https://api.highcharts.com/highcharts/plotOptions.series.dataLabels
