### ISSUE TITLE
Modal administration (general, migration, logs, ...) cache le bouton sauvegarder

### ISSUE THREAD

**Issue by edgd1er** [NextDom/nextdom-core#84]
il faut fermer la modal ouverte pour retrouver le bouton et sauver les modifications.

![capture du 2018-09-16 21-12-14](https://user-images.githubusercontent.com/3601462/45599971-69536800-b9f5-11e8-81a4-a267d6599778.png)

opera ( latest) sur ubuntu , nextdom sous docker pull de 19h environ (16/09/2018)

**Comment by Sylvaner** [comment]
@byackee a tout séparé, mais que penses-tu (@byackee) de mettre 2 boutons (en haut et en bas) ?

**Comment by byackee** [comment]
Chaque page a son propre bouton sauvegarder maintenant.

Mettre 2 boutons va surcharger l'interface a mon avis
