### ISSUE TITLE
Difference de chargement page : JS ?

### ISSUE THREAD

**Issue by cyrilphoenix71** [NextDom/nextdom-core#844]
La procedure de chargement d'une page semble differente entre :
- ouverture via clic sur lien
- F5

Un bon exemple est de tester la PR : https://github.com/NextDom/plugin-Meross/pull/3
Ouvrir la page du plugin : c'est tout buggé, F5 c'est OK

**Comment by Sylvaner** [comment]
Ce n'est pas un bug, c'est le fonctionnement normal :)

**Comment by cyrilphoenix71** [comment]
Non ya vraiment une difference de resultat, ca ne devrait pas
