### ISSUE TITLE
apres la sauvegarde d'une page, un F5 provoque de nouveau la sauvegarde OU la notification sauvegarde

### ISSUE THREAD

**Issue by cyrilphoenix71** [NextDom/nextdom-core#849]
Car à la fin de la sauvegarde on laisse dans l'adresse de la page un un "savesuccessfull"

Ce bug est valade pour d'autre action du meme style : quand un =quelquechose est ajouté à l'adresse.
il faudrait "nettoyer" l'adresse suite à la l'affichage de la notif

**Comment by byackee** [comment]
c'est sur toutes les pages ou que a certains endroits ?

**Comment by cyrilphoenix71** [comment]
le probleme ne viendrais pas de ce genre de code @byackee ?
![image](https://user-images.githubusercontent.com/18350629/52703493-bb85be80-2f7e-11e9-948a-d0fcfd7dbd46.png)
