### ISSUE TITLE
Zone grisée incomplète derrière modale

### ISSUE THREAD

**Issue by slobberbone** [NextDom/nextdom-core#855]
Si l'on affiche la console lors de l'import, les logs sont affichés dans une popup/modale, la zone grisée prend la place de l'écran et non de la totalité de la page.

**Comment by slobberbone** [comment]
![zone popup incomplete](https://user-images.githubusercontent.com/3833875/51596646-c5754e00-1ef9-11e9-989a-3983d20d7977.png)

**Comment by cyrilphoenix71** [comment]
tjs présent ? @slobberbone

**Comment by slobberbone** [comment]
Oui

**Comment by slobberbone** [comment]
Testé et validé

**Comment by Astral0** [comment]
ok
