### ISSUE TITLE
Missing symfony/yaml for Release 0.1.0

### ISSUE THREAD

**Issue by edgd1er** [NextDom/nextdom-core#864]
Avec le tag 0.1.0, lors d'une installation depuis un conteneur vide, la première page indique que le composant "Symfony Yaml component" est manquant:

An exception has been thrown during the rendering of a template ("Loading translations from the YAML format requires the Symfony Yaml component.").

J'ai pu avec la premier page comme attendue via un  "composer require symfony/yaml".

Il semblerait que depuis la dernière release, ce composant devienne obligatoire.

Quelqu'un peut il confirmer ce point ?

**Comment by Sylvaner** [comment]
Oui normalement il est installé depuis un moment ce composant

**Comment by edgd1er** [comment]
C est ce que je me suis dit, mais  je ne le vois pas dans le composer.json, que ce soit en develop ou avec le tag 0.1.0

**Comment by ColonelMoutarde** [comment]
Il est une dépendance de symfony/translation il faut qu'un composer install soit effectué avant que tu lance la première page

**Comment by edgd1er** [comment]
oui, il y a bien un composer install qui est fait. Je regarderai ça de nouveau lorsque je recevrais mon nouveau pc. le mien a ko. carte mère hs (non remplaçable car modèle trop ancien)

**Comment by edgd1er** [comment]
Pb confirmé via la commande dans le conteneur:
la dependance n'est pas installée si on n'installe pas les dépendances dev.

```
root@dbbb8573474f:/var/www/html# composer update -o --no-dev
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Updating dependencies
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.
Generating optimized autoload files
root@dbbb8573474f:/var/www/html# composer require symfony/yaml -o --update-no-dev
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Using version ^3.4 for symfony/yaml
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies
Package operations: 1 install, 0 updates, 0 removals
  - Installing symfony/yaml (v3.4.21): Downloading (100%)         
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.
Writing lock file
Generating optimized autoload files
```

Fix:
	composer update -o --no-dev
	composer require symfony/yaml -o --update-no-dev
