### ISSUE TITLE
Sauvegarder les fichiers de config

### ISSUE THREAD

**Issue by Astral0** [NextDom/nextdom-core#873]
Si on déplace des fichiers de conf dans /etc/nextdom, il faut les sauvegarder / restaurer.
Attention, /etc/nextdom contient des paramètres qui sont amenés par les paquets nextdom-mysql et nextdom-common, donc il ne faut pas tout sauvegarder /etc/nextdom, mais uniquement les paramètres générés par nextdom.

**Comment by slobberbone** [comment]
Config : /var/lib/nextdom/config
mais également /usr/share/nextdom/data ...

**Comment by slobberbone** [comment]
Fait pour la 0.3.0
