### ISSUE TITLE
Chargement du menu au début et non à la fin du chargement d'une page

### ISSUE THREAD

**Issue by Astral0** [NextDom/nextdom-core#882]
Serait-il possible que le menu soit chargé au début du chargement d'une page et pas à la fin ?
En effet, quand on accède puis internet, le chargement d'une page peut être particulièrement lent et on doit attendre qu'elle soit finie pour accéder aux sous-menus (ceux qui doivent être dépliés, comme tout ce qu'on trouve sous "Procole domotique") :  

![image](https://user-images.githubusercontent.com/39194968/52272456-26b00f00-2947-11e9-8949-d473ed2e69f9.png)

**Comment by slobberbone** [comment]
@cyrilphoenix71 tu l'as pas fais ça avec ton coup de karcher recent ?

**Comment by cyrilphoenix71** [comment]
non car le probleme est ailleurs, c'est le div_loading qui est par dessus

**Comment by cyrilphoenix71** [comment]
Résolue avec le pace loading
