### ISSUE TITLE
Affichage du menu tronqué

### ISSUE THREAD

**Issue by perarem** [NextDom/nextdom-core#896]
Affichage du menu tronqué : 
ici, la dernière ligne du menu :
![screen shot 02-10-19 at 12 47 am](https://user-images.githubusercontent.com/10147784/52527776-5dcb4b00-2cce-11e9-926d-04b7de50557f.PNG)

ici, il manque 3 lignes : 
![screen shot 02-10-19 at 12 52 am](https://user-images.githubusercontent.com/10147784/52527778-63c12c00-2cce-11e9-8f2d-7eb7072bb997.PNG)

**Comment by byackee** [comment]
Salut @perarem, Normalement le menu est scrollable, peux tu essayer stp?

**Comment by perarem** [comment]
@byackee j'ai pris les screens en limite basse du scroll ;-)
On y voit d'ailleurs que le curseur bas " V " de la barre de scroll n'apparait pas.
