### ISSUE TITLE
Sur la derniere dev 0.1.2 (base jeedom 3.3.10) apres restore notre core est estampillier 3.3.3

### ISSUE THREAD

**Issue by cyrilphoenix71** [NextDom/nextdom-core#913]
![image](https://user-images.githubusercontent.com/18350629/52782099-847ede00-304e-11e9-97be-86343a85ca2e.png)

**Comment by Astral0** [comment]
3.3.3 correspond il à la valeur du nextdom dont provient la sauvegarde ?

**Comment by Sylvaner** [comment]
oui

**Comment by cyrilphoenix71** [comment]
bug disparu sur dev actuelle
