### ISSUE TITLE
Ajouter un vidage cache ou CTRL+F5 après un restore 

### ISSUE THREAD

**Issue by cyrilphoenix71** [NextDom/nextdom-core#914]
Car après restore le thème dynamique ne fonctionne pas

**Comment by slobberbone** [comment]
Comme expliqué, le rapport au thème n'est qu'un effet supplémentaire de la non déconnexion de la session après un restore.

**Comment by cyrilphoenix71** [comment]
non car le theme n'est pas associé a l'utilisateur, il le sera bientot, le je parle bien d'un vidage cache

**Comment by Astral0** [comment]
Sans parler du thème, je pense que vider le cache doit être fait après un restore. En effet, sinon on a tous les capteurs qui reprennent leur valeur de l'état précédent sauvegardé. Or, quand on utilise une sauvegarde pour l'installer sur une nouvelle machine (par ex. sur une machine de tests/dev), on peut se retrouver avec des capteurs qui ne fonctionneront plus (par ex des Zwave alors que la machine de dev n'a pas de clé Zwave) mais le capteur est toujours dans un état "normal" avec la valeur sauvegardée, et l'utilisateur ne se rend pas compte qu'en fait il ne fonctionne pas.

A la limite, on pourrait avoir une case à cocher qui serait : "conserver l'état des capteurs après restauration" ou quelque chose comme ca.

**Comment by cyrilphoenix71** [comment]
@Astral0 c pas a cause de cette erreur aussi ?
![image](https://user-images.githubusercontent.com/18350629/53337169-f8e43780-3900-11e9-9a2e-11c6b9f3f426.png)
