### ISSUE TITLE
Supprimer le /public/css/theme.html au postinstall

### ISSUE THREAD

**Issue by cyrilphoenix71** [NextDom/nextdom-core#915]
Car sur un post install on peut se retrouver avec une firstuse en mode dark, si theme choisit avant le postinst etait le dark

**Comment by Astral0** [comment]
Je ne comprends pas : c'est quoi ce fichier theme.html ?
Est ce qu'il est généré après l'installation ?

**Comment by cyrilphoenix71** [comment]
@Astral0 theme.css pardon, c'est celui qui regenerer à la sauvegarde ou au changement de theme

**Comment by Sylvaner** [comment]
Un theme.css doit exister sinon la page plantera (les couleurs n'existeront pas).
Mais quel est le problème que le firstuse soit noir ou blanc ?
Surtout qu'on est pas censé faire des postinstall régulièrement

**Comment by cyrilphoenix71** [comment]
@Sylvaner je dis juste qu'au postinstall on devrait repartir d'un theme standard soit le white

**Comment by Sylvaner** [comment]
Ah un post install, tu est sur un thème standard.

Faut bien penser que tu n'est pas censé faire un postinstall après, et que si c'est le cas, est-ce vraiment intéressant ?

**Comment by Astral0** [comment]
Sauf que si c'est un fichier généré, il doit se trouver ailleurs que dans public/css/

**Comment by slobberbone** [comment]
@cyrilphoenix71 ca en est où celui là ?

**Comment by cyrilphoenix71** [comment]
on clos
