### ISSUE TITLE
Problème lors du redimensionnement d'une modale

### ISSUE THREAD

**Issue by slobberbone** [NextDom/nextdom-core#924]
Se rendre sur la page des mises à jour, cliquer sur le bouton "Mise à jour sélective" et redimensionner la modale : 

![pblm resize modale](https://user-images.githubusercontent.com/3833875/53050014-9fab7c80-3498-11e9-9fd9-0a6e0989e614.png)

**Comment by slobberbone** [comment]
Corrigé pour cette modale, mais il y a un problème globalement pour l'ensemble des modales qui peuvent se redimensionner (ex import backup ... j'ouvrirai un ticket pour ça)

Testé et validé

**Comment by Sylvaner** [comment]
OK
