### ISSUE TITLE
Fonctionnalité étendue de la PR Multi objets pères sur le Dashboard 

### ISSUE THREAD

**Issue by perarem** [NextDom/nextdom-core#930]
Dans la même idée que la PR Multi objets pères sur le Dashboard #929 , je verrais bien une barre secondaire avec les objets enfants de l'objet père sélectionné, se serait pratique lorsque l'on a pas mal d'enfants attachés à un père. 
Ou alors avoir la possibilité de réduire les zones objets enfants en cliquant sur leur nom sur le Dashboard, ou les 2...

**Comment by perarem** [comment]
OK avec le dernier fix

**Comment by Sylvaner** [comment]
OK

**Comment by slobberbone** [comment]
c pas super sexy mais ca fait le taff
Testé et validé
