### ISSUE TITLE
La mise en page "Alertes" des équipements a sauté.

### ISSUE THREAD

**Issue by perarem** [NextDom/nextdom-core#931]
Plus de couleur, taille et mauvaise position des champs Danger, Warning et Ok
![screen shot 02-23-19 at 11 50 pm](https://user-images.githubusercontent.com/10147784/53292721-1dd48f80-37c7-11e9-8dee-8653ead48383.PNG)

**Comment by perarem** [comment]
OK avec le Fix

**Comment by Sylvaner** [comment]
Ok mais va falloir revoir les col sans les row

**Comment by slobberbone** [comment]
Validé et testé
