### ISSUE TITLE
La sauvegarde et la suppression d'une note ne fonction plus -> erreur SQL

### ISSUE THREAD

**Issue by cyrilphoenix71** [NextDom/nextdom-core#932]
La sauvegarde et la suppression d'une note ne fonction plus
![image](https://user-images.githubusercontent.com/18350629/53330462-d34e3280-38ee-11e9-9a10-311837ca3a66.png)

**Comment by slobberbone** [comment]
Il manque la commande getTableName, du coup la fonction de save/remove ne fonctionne plus.

**Comment by Sylvaner** [comment]
Ok

**Comment by slobberbone** [comment]
Validé et testé

**Comment by Astral0** [comment]
ok

**Comment by Gis70** [comment]
ok
