### ISSUE TITLE
Une installation de 0 échoue

### ISSUE THREAD

**Issue by slobberbone** [NextDom/nextdom-core#934]
Lors d'un postinst : 
` >>> Copy icons
 >>> Copy themes
 >>> Copy images
 >>> Generate CSS
 >>> Generate JS
cat: vendor/node_modules/bootstrap/dist/js/bootstrap.min.js: No such file or directory
 >>> Cleaning Twig Cache
 OK
step_nextdom_prerequisites_verification ...  OK
step_nextdom_apache_php ...  OK
step_nextdom_configuration ... rm: cannot remove '/var/www/html/core/config': Is a directory`

**Comment by slobberbone** [comment]
testé et validé

**Comment by Gis70** [comment]
+1 je viens de partir d'un debian 9 tout neuf

**Comment by Sylvaner** [comment]
ok

**Comment by Sylvaner** [comment]
``
