### ISSUE TITLE
Bug modale configuration équipements

### ISSUE THREAD

**Issue by cyrilphoenix71** [NextDom/nextdom-core#935]
- gestion disposition tableau
- divers bug graphiques

**Comment by slobberbone** [comment]
Euh @cyrilphoenix71 on ne sait pas trop ce qu'il faut tester. Il faut mettre plus d'info, des captures d'écrans etc ...

**Comment by Sylvaner** [comment]
Ok

**Comment by Gis70** [comment]
Je ne sais pas quoi tester et comme j'ai des pb de modale déjà...

**Comment by cyrilphoenix71** [comment]
@slobberbone @Gis70 
To test :
- aller dans le dash 
- cliquer sur le titre d'un equipement pour aller dans sa page config
- cliquer sur configuration avancée (de l'equipement pas des commandes)
- tester tout ce qui est dans la modale qui s'ouvre (info, reglages etc)
- s'attarder sur l'onglet disposition et surtout la disposition tableau
- revenir à chaque fois sur le dash pour valider les changemnt
- tester avec plusieurs type d'equipement

**Comment by Sylvaner** [comment]
Validé

**Comment by Astral0** [comment]
ok

**Comment by slobberbone** [comment]
validé
