### ISSUE TITLE
Aucune information de l'utilisateur courant sur la page profil

### ISSUE THREAD

**Issue by slobberbone** [NextDom/nextdom-core#940]
Sur la page profil, si on affiche avec la sidebar réduite, aucune information sur l'utilisateur actuelle n'est affichée ... Lorsuq'on active la double authentification, ou autre, ce serait intéressant d'avoir un moyen de valider visuellement l'utilisateur avec lequel on est connecté et qu'on est en train de modifier.

**Comment by slobberbone** [comment]
@cyrilphoenix71  a pousser dans la bonne branche stp !

**Comment by cyrilphoenix71** [comment]
A remplacer dans la page admin/profils

`<li class="header pull-left"><i class="fas fa-briefcase spacing-right"></i>{{ 'Profil de ' }}{{ profilsUser.getLogin() }}</li>`

**Comment by Gis70** [comment]
OK validé
