### ISSUE TITLE
Bugs sur le dashboard

### ISSUE THREAD

**Issue by cyrilphoenix71** [NextDom/nextdom-core#941]
Nouvelle barre de navigation des parents :
- Manque cursor sur les bouton

Redimensionnement auto en mode edition :
- Fonctionne mal, on tombe pas sur un vrai multiple de grille + marge
- Seulement à la hausse

Boutons de redimensionnement auto :
- Couleur pas calée sur le thème
- Mal placés
- 1 classe par bouton alors qu'il pourraient être dans un div

Chargement de la page dash :
- Pendant le chargement de la page la largeur des objet change "pieces"

**Comment by perarem** [comment]
@cyrilphoenix71 Le bouton de redimensionnement est devenu invisible mais opérationnel…

![screen shot 03-02-19 at 10 29 am](https://user-images.githubusercontent.com/10147784/53680084-4f24f200-3cd6-11e9-8f3c-785324a66e8e.PNG)

**Comment by cyrilphoenix71** [comment]
@perarem tu peux reouvrir une issue car la c un nouveau bug lié au thème

**Comment by cyrilphoenix71** [comment]
@slobberbone 
To test :
- Aller dans le dashboard
- Passer en mode edition (le crayon en bas)
- Dans les differents objets (pieces), Utiliser les fonctions de redimensionnement dans le coin superieur droit de l'objet piece
- Modifier les options tuiles dans la page "profil" et re-tester les 3 etapes précedentes
> valeur conseillées : marge-externe=6 widget-size=70

Puis tester la navbar en haut du dashboard

**Comment by Astral0** [comment]
ok

**Comment by slobberbone** [comment]
@cyrilphoenix71 si je clique sur les boutons redimensionnement sur pas de grille puis l'autre puis je refait le premier, il n'a plus d'effet.

De plus le label est incompréhensible pour moi.

**Comment by slobberbone** [comment]
Bon je regarde mais les 2 nodes html qui font les boutons ont le mm ID ....

**Comment by slobberbone** [comment]
Testé et validé. Attention par contre sur des html element on a plusieurs fois le mm id. C'est à proscrire
