### ISSUE TITLE
Les filtres n'affichent pas les sous-enfants

### ISSUE THREAD

**Issue by Sylvaner** [NextDom/nextdom-core#943]
Voici ma hiérarchie : 
![capture d ecran 2019-03-01 a 10 52 42](https://user-images.githubusercontent.com/957104/53630413-4e298d00-3c10-11e9-977d-46c2117b16be.png)

Lorsque je clique sur "Maison", je n'ai pas que le premier niveau des enfants : 
![capture d ecran 2019-03-01 a 10 54 04](https://user-images.githubusercontent.com/957104/53630443-626d8a00-3c10-11e9-9b48-7245f1e7dbb4.png)

**Comment by Sylvaner** [comment]
OK

**Comment by slobberbone** [comment]
Testé et validé
