### ISSUE TITLE
Boutons Redémarrer et Eteindre inopérant sur page administration.

### ISSUE THREAD

**Issue by perarem** [NextDom/nextdom-core#947]
Sur la page Administration, les boutons Redémarrer et Eteindre sont inopérant sans un F5 préalable.

**Comment by Gis70** [comment]
Ca fonctionne en develop sur fresh install debian 9. je clos, je n'ai pas dû faire F5

**Comment by perarem** [comment]
Pas d'accord, toujours présent.

**Comment by Gis70** [comment]
Tu es en dévelop récente ?

**Comment by perarem** [comment]
Arghhh autant pour moi :-(
Je confirme c'est OK avec la dernière develop.
