### ISSUE TITLE
Plugin OpenVPN (Jeedom SAS)

### ISSUE THREAD

**Issue by perarem** [NextDom/nextdom-core#948]
Impossible de créer un équipement sur le plugin OpenVPN : 

![screen shot 03-04-19 at 01 59 pm](https://user-images.githubusercontent.com/10147784/53735122-44a95a80-3e86-11e9-817b-caa1a3b9ca33.PNG)

![screen shot 03-04-19 at 02 05 pm](https://user-images.githubusercontent.com/10147784/53735354-e4ff7f00-3e86-11e9-9b2e-e8c7a6621d4f.PNG)

`function printEqLogic(_eqLogic){
    $('#bt_uploadCaCrt').fileupload({
        replaceFileInput: false,
        url: 'plugins/openvpn/core/ajax/openvpn.ajax.php?action=uploadCaCrt&type=ca&id=' + _eqLogic.id+'&jeedom_token='+JEEDOM_AJAX_TOKEN,
        dataType: 'json',
        done: function (e, data) {
            if (data.result.state != 'ok') {
                $('#div_alert').showAlert({message: data.result.result, level: 'danger'});
                return;
            }else{
                $('#div_alert').showAlert({message: 'Fichier envoyé avec succès', level: 'success'});
            }
        }
    });
`

**Comment by slobberbone** [comment]
@Sylvaner une idée pour celui là ?

**Comment by Sylvaner** [comment]
Oui je vois bien :)

**Comment by perarem** [comment]
Hello,
C'est OK pour moi pour le plugin OpenVPN… pas de soucis pour les autres.
