### ISSUE TITLE
Disparition du bouton de redimensionnement en mode édition du dashboard

### ISSUE THREAD

**Issue by perarem** [NextDom/nextdom-core#951]
Sur la branche Fixes, dans le mode édition du Dashboard, le bouton de redimensionnement est devenu invisible mais opérationnel…
![screen shot 03-02-19 at 10 29 am](https://user-images.githubusercontent.com/10147784/53840710-1c5f5000-3f9b-11e9-81d4-7dfc7349f8c7.PNG)

**Comment by Gis70** [comment]
Ok en thèmes DARK 
![image](https://user-images.githubusercontent.com/16589132/54644105-d3c68d00-4a98-11e9-9021-8ffd29887f75.png)

En thème normal ça dit quoi sur branche develop ? @cyrilphoenix71 @slobberbone @Sylvaner

**Comment by Gis70** [comment]
OK en theme white branche develop je clos.
![image](https://user-images.githubusercontent.com/16589132/54706746-ed6edf80-4b3f-11e9-92aa-6c9dca00fa97.png)
