### ISSUE TITLE
Affichage en mode liste en plus du mode tuile sur Gest plugin et Mise a jour

### ISSUE THREAD

**Issue by slobberbone** [NextDom/nextdom-core#957]
<a href="https://github.com/cokecorp"><img src="https://avatars2.githubusercontent.com/u/9156515?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cokecorp](https://github.com/cokecorp)**
_Friday Dec 07, 2018 at 15:52 GMT_
_Originally opened as https://github.com/NextDom/nextdom-core/issues/2_

----

avoir si possible technique la possibilité de basculer d'un affichage liste a tuile
un peu comme dans santé / plugin

![image](https://user-images.githubusercontent.com/9156515/49657641-6db17f00-fa40-11e8-9a63-fef92b1de6e8.png)

**Comment by slobberbone** [comment]
<a href="https://github.com/byackee"><img src="https://avatars2.githubusercontent.com/u/4707496?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [byackee](https://github.com/byackee)**
_Friday Jan 25, 2019 at 16:45 GMT_

----

Salut,

Je vais voir pour intégrer ca apre la version 0.1

**Comment by slobberbone** [comment]
<a href="https://github.com/slobberbone"><img src="https://avatars3.githubusercontent.com/u/3833875?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [slobberbone](https://github.com/slobberbone)**
_Thursday Mar 07, 2019 at 08:21 GMT_

----

@byackee c'est reglé ?

**Comment by cyrilphoenix71** [comment]
non

**Comment by Gis70** [comment]
ok validé
