### ISSUE TITLE
Pb de mise à jour du statut du mode (plugin mode)

### ISSUE THREAD

**Issue by slobberbone** [NextDom/nextdom-core#959]
<a href="https://github.com/noodom"><img src="https://avatars2.githubusercontent.com/u/24904155?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [noodom](https://github.com/noodom)**
_Wednesday Feb 20, 2019 at 11:20 GMT_
_Originally opened as https://github.com/NextDom/nextdom-core/issues/6_

----

Bonjour,

Lorsque je modifie le mode depuis le plugin mode que ce soit en mode dashboard ou design, le statut courant n'est pas mis à jour. Il faut rafraîchir la page pour voir le bon statut en cours.

Plugin Mode : Version : 2018-05-09 06:18:18 (stable)
NextDom : v0.1.2

**Comment by Gis70** [comment]
ça fait ça avec d'autre device comme mon qubino pr le chauffage, les logos confort ou autre ne se rafraîchissent pas, il faut faire f5

**Comment by Gis70** [comment]
Mon mode à moi sur le dash change bien de widget au changement de mode en cliquant dessus. Alarme aussi. Pas le Qubino chauffage fil pilote.

**Comment by Gis70** [comment]
Ok en develop avec plugin mode à jour. Je clos
