### ISSUE TITLE
Après récupération d'un backup Jeedom, renommage dans un champ texte/html du Design (jeedom vers nextdom)

### ISSUE THREAD

**Issue by slobberbone** [NextDom/nextdom-core#960]
<a href="https://github.com/noodom"><img src="https://avatars2.githubusercontent.com/u/24904155?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [noodom](https://github.com/noodom)**
_Wednesday Feb 20, 2019 at 11:27 GMT_
_Originally opened as https://github.com/NextDom/nextdom-core/issues/7_

----

Suite à la récupération d'un backup d'une sauvegarde Jeedom vers une nouvelle installation NextDom,
J'ai constaté que le contenu des champs text/html du mode design sont modifiés (remplacement de jeedom par nextdom)

=> Ce qui pose un problème pour le code HTML/Javascript faisant référence à des images dont le com comprend jeedom (lien cassé)
=> Ca peut être plus gênant dans le cas de renommage au niveau de code javascript inclus dans le design (non testé)

Ca semble être seulement lors du chargement du backup car en insérant un texte/html, ça ne pose pas de problème.

A voir si corrigé après la version v0.1.2

(NextDom : v0.1.2)

**Comment by slobberbone** [comment]
<a href="https://github.com/GsCbo"><img src="https://avatars1.githubusercontent.com/u/44973640?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [GsCbo](https://github.com/GsCbo)**
_Wednesday Feb 27, 2019 at 14:50 GMT_

----

Perso j'ai fait l'install en 0.1.2 et ça m'a remplacé dans le plugin ovh et dans la partie réseau de l'administration

**Comment by slobberbone** [comment]
<a href="https://github.com/slobberbone"><img src="https://avatars3.githubusercontent.com/u/3833875?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [slobberbone](https://github.com/slobberbone)**
_Thursday Mar 07, 2019 at 08:20 GMT_

----

La prochaine version ne fera plus ce changement. @Sylvaner tu confirmes ?

**Comment by Gis70** [comment]
J'ai encore eu le pb fresh installation d'hier soir 1.3 branche dev

**Comment by Salvialf** [comment]
J'ai du subir le même bug:
Suite restauration sauvegarde de prod Jeedom sur environnement de test Nextdom:
Le terme 'jeedom' a été remplacé par 'nextdom' dans l'url de mon adresse DNS - visible sur le market dans 'Mes Jeedoms'.

**Comment by Gis70** [comment]
Voilà un soucis : 
![image](https://user-images.githubusercontent.com/16589132/56839089-450c1380-6881-11e9-9a94-d1bc7bba33b6.png)
à la place de nextdom jai jeedom dans mon sous domaine et il a été remplacé tout seul

**Comment by byackee** [comment]
Pour le moment lors de la migration nous remplacons tous les termes jeedom par nextdom. Il y a beaucoup de terme jeedom dans la base de données. Nous n'avons pas encore eu le temps de les trier.

**Comment by Gis70** [comment]
Quoi valider ? dans la partie réseaux jeedom est toujours remplacer par nextdom
