### ISSUE TITLE
Impossible de décocher "Ne pas mettre à jour" pour un plugin

### ISSUE THREAD

**Issue by slobberbone** [NextDom/nextdom-core#961]
<a href="https://github.com/noodom"><img src="https://avatars2.githubusercontent.com/u/24904155?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [noodom](https://github.com/noodom)**
_Friday Feb 22, 2019 at 13:46 GMT_
_Originally opened as https://github.com/NextDom/nextdom-core/issues/9_

----

Dans le menu de mise à jour des plugins, j'ai un plugin avec la checkbox "Ne pas mettre à jour" cochée.

Je n'arrive plus à la décocher : lorsque je clique dessus, elle est bien décochée mais impossible de sauvegarder cet état.

=> Conséquence : impossible de faire la mise à jour du plugin

(NextDom v0.1.2)

**Comment by Gis70** [comment]
Idem pour l'inverse, lorsque je coche Ne pas mettre à jour, cela ne sauvegarde pas l'état

**Comment by Gis70** [comment]
un lien ? Je n'arrive plus à laisser cocher activer les paramètres personnalisés d'un widget :
![image](https://user-images.githubusercontent.com/16589132/54643324-dd4ef580-4a96-11e9-8be7-30f1d99ee935.png)

**Comment by Gis70** [comment]
Ok validé
