### ISSUE TITLE
Core 0.1.2 : bug pas de surlignage lors de sélection de texte

### ISSUE THREAD

**Issue by slobberbone** [NextDom/nextdom-core#963]
<a href="https://github.com/Gis70"><img src="https://avatars1.githubusercontent.com/u/16589132?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Gis70](https://github.com/Gis70)**
_Wednesday Mar 06, 2019 at 23:06 GMT_
_Originally opened as https://github.com/NextDom/nextdom-core/issues/12_

----

Dans la personnalisation du code dans un widget, le surlignage ne fonctionne pas.

**Comment by Gis70** [comment]
Ca ne marche pas non plus dans bloc code d'un scénario

**Comment by Gis70** [comment]
OK dans un scénario mais toujours NOK dans la personnalisation d'un widget
