### ISSUE TITLE
Core 0.1.2 : bug suppression unitaire alertes

### ISSUE THREAD

**Issue by slobberbone** [NextDom/nextdom-core#965]
<a href="https://github.com/Gis70"><img src="https://avatars1.githubusercontent.com/u/16589132?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Gis70](https://github.com/Gis70)**
_Wednesday Mar 06, 2019 at 23:09 GMT_
_Originally opened as https://github.com/NextDom/nextdom-core/issues/14_

----

La suppression unitaire des alertes via la corbeille ne marche pas, vider complètement fonctionne.

**Comment by Gis70** [comment]
Événements aléatoire car ça a fonctionné ensuite. Je surveille.

**Comment by Gis70** [comment]
Ca ne marche pas je confirme quand on se retrouve en dehors de la page /index.php?v=d&p=dashboard

**Comment by Gis70** [comment]
fonctionnement aléatoire, un coup ça marche, un coup ça marche après plusieurs clic. (non ce n'est pas ma souri qui déconne, jai testé avec un autre)

**Comment by Gis70** [comment]
Ca à l'air OK cette fois :)
