### ISSUE TITLE
Plugin Suivi Conso ne fonctionne pas

### ISSUE THREAD

**Issue by slobberbone** [NextDom/nextdom-core#966]
<a href="https://github.com/Gis70"><img src="https://avatars1.githubusercontent.com/u/16589132?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Gis70](https://github.com/Gis70)**
_Wednesday Mar 06, 2019 at 23:13 GMT_
_Originally opened as https://github.com/NextDom/nextdom-core/issues/15_

----

Erreur au chargement du panel et pas de graph 
![image](https://user-images.githubusercontent.com/16589132/53920538-d1623d00-406d-11e9-8b2d-cdcae1447d46.png)

**Comment by slobberbone** [comment]
<a href="https://github.com/slobberbone"><img src="https://avatars3.githubusercontent.com/u/3833875?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [slobberbone](https://github.com/slobberbone)**
_Thursday Mar 07, 2019 at 08:17 GMT_

----

Es-tu sur que ce bug concerne Jeedom et non pas le plugin ?

**Comment by slobberbone** [comment]
<a href="https://github.com/Gis70"><img src="https://avatars1.githubusercontent.com/u/16589132?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Gis70](https://github.com/Gis70)**
_Thursday Mar 07, 2019 at 08:50 GMT_

----

Ca fonctionnait bien avant la migration :)

**Comment by Gis70** [comment]
J'ai du neuf 👍 
DataTables warning: table id=tableau_teleinfoDay - An error occurred while connecting to the database. The error reported by the server was: SQLSTATE[HY000] [1044] Access denied for user 'nextdomdev'@'localhost' to database 'jeedom'

**Comment by Gis70** [comment]
Dans le plugin il y a des appels de ajax::success(jeedom::toHumanReadable($txt));
il y a aussi des appels dans la DB : jeedom.LaTable

**Comment by Gis70** [comment]
Dans le PANEL on arrive sur SUIVI CONSO :

![image](https://user-images.githubusercontent.com/16589132/56306692-695e4680-6143-11e9-8c2c-d4d0986403ee.png)

Il manque les graphiques,  le type heure creuse ou plein et la puissance instantanée en cours et la puissance maxi de l'abonnement (en haut à droite dans les espèces de drapeaux vides)

On peut voir plus haut le 6 mars lors de mon passage pour la première fois à Nextdom que ça marchait à moitié, mais ensuite ça ne marchait plus du tout quand je suis passé en develop

**Comment by Gis70** [comment]
Voilà ce que j'obtiens en cliquant sur le message de debug : 
![image](https://user-images.githubusercontent.com/16589132/56306932-0ae59800-6144-11e9-941a-3b21733f54a1.png)

**Comment by slobberbone** [comment]
Toujours d'actualité @Gis70 ?

**Comment by Gis70** [comment]
Malheureusement oui...

Le mer. 3 juil. 2019 à 22:46, Slobberbone <notifications@github.com> a
écrit :
