### ISSUE TITLE
Bug plugin Volet impossible de lancer le demon à cause de setClass

### ISSUE THREAD

**Issue by slobberbone** [NextDom/nextdom-core#967]
<a href="https://github.com/Gis70"><img src="https://avatars1.githubusercontent.com/u/16589132?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Gis70](https://github.com/Gis70)**
_Thursday Mar 07, 2019 at 06:42 GMT_
_Originally opened as https://github.com/NextDom/nextdom-core/issues/17_

----

Erreur sur la fonction deamon_start du plugin : Call to undefined method listener::setClass()

J'ai essayé de le réinstaller mais rien n'y fait.

**Comment by slobberbone** [comment]
<a href="https://github.com/slobberbone"><img src="https://avatars3.githubusercontent.com/u/3833875?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [slobberbone](https://github.com/slobberbone)**
_Thursday Mar 07, 2019 at 08:15 GMT_

----

Ouais à priori le plugin volet c'est pas ça ... as-tu regarder le plugin Opening ?
Ce problème tu l'as aussi sous Jeedom ?

**Comment by slobberbone** [comment]
<a href="https://github.com/Gis70"><img src="https://avatars1.githubusercontent.com/u/16589132?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Gis70](https://github.com/Gis70)**
_Thursday Mar 07, 2019 at 08:53 GMT_

----

Je n'ai pas regardé coté nextdom. Non c'est à l'issue de la migration, pas de pb avant

**Comment by slobberbone** [comment]
<a href="https://github.com/Gis70"><img src="https://avatars1.githubusercontent.com/u/16589132?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Gis70](https://github.com/Gis70)**
_Thursday Mar 07, 2019 at 11:03 GMT_

----

idem avec plugin officiel alarme 
![image](https://user-images.githubusercontent.com/16589132/53952450-0784d880-40d1-11e9-967b-677191268a5b.png)

**Comment by Gis70** [comment]
Issue réglée par @sylvaner
