### ISSUE TITLE
lastChangeStateDuration ne marche pas comme il devrait

### ISSUE THREAD

**Issue by Gis70** [NextDom/nextdom-core#970]
j’ai crée un virtuel que je passe à 1 ou 0 via une URL. (toujours répéter)
Dans le testeur d’expression j’exécute : lastChangeStateDuration(#[Aucun][test][on]#,1)
Il apparaît que le temps est mis à jour seulement au 2ème renvoi à 1 de la valeur et pas sur le premier.

Pb quand on utilise ça avec un Nut pr faire de la présence sur les premières secondes :)

**Comment by cyrilphoenix71** [comment]
Tu aurais une idée du fix ?

**Comment by slobberbone** [comment]
@Gis70 tu peux valider ?

**Comment by slobberbone** [comment]
@Gis70 tu peux valider ?

**Comment by Gis70** [comment]
@slobberbone OK validé

**Comment by cyrilphoenix71** [comment]
@slobberbone on clos ? (l'emeteur de l'issue valide donc...)

**Comment by Gis70** [comment]
je me permets de clore :)
