### ISSUE TITLE
méthode manquante checkAndFixCron()

### ISSUE THREAD

**Issue by Gis70** [NextDom/nextdom-core#979]
Bonjour, 

J'ai fais la màj du plugin thermostat ajd et il apparait qu'il manque une fonction : 

cf : 
https://github.com/jeedom/core/search?q=checkAndFixCron&unscoped_q=checkAndFixCron

**Comment by slobberbone** [comment]
Commande ajoutée. Faut que je l'inclue proprement maintenant dans le code voir si c pertinent.

**Comment by slobberbone** [comment]
@Gis70 PR a alidé stp :)

**Comment by Gis70** [comment]
OK validé
