### ISSUE TITLE
Min Max value ne s'affiche pas plugin ESPEASY

### ISSUE THREAD

**Issue by Gis70** [NextDom/nextdom-core#983]
Les Min Max value ne sont pas éditables malgré que l'on coche les cases. De plus les valeurs par défaut max sont à 0 !

![image](https://user-images.githubusercontent.com/16589132/54238498-f1d04280-4518-11e9-8d77-a71977d5854f.png)

Si je modifie directement le Max Value dans la table dans la DB ça marche.

**Comment by Gis70** [comment]
VOilà dans la DB 
![image](https://user-images.githubusercontent.com/16589132/54261919-41d8f480-456d-11e9-850a-d9d864fb6614.png)

**Comment by Gis70** [comment]
Ca ne marche pas, ce matin je n'ai plus les minValue et MaxValue dans la table est ça reste à 0, ce n'est pas passé à 100 dansla table (par contre je visualise bien 100 dans valeurs)

![image](https://user-images.githubusercontent.com/16589132/54338807-3bad4b80-4633-11e9-8379-1f6ca7515603.png)

**Comment by Gis70** [comment]
OK validé

**Comment by Sylvaner** [comment]
Déjà dans la branche develop
