### ISSUE TITLE
Tableau d'un équipement non centré dans la tuile du dashboard

### ISSUE THREAD

**Issue by perarem** [NextDom/nextdom-core#985]
Le tableau d'un équipement n'est pas centré dans la tuile du Dashboard

**Comment reproduire ?**
Étapes pour reproduire le problème :
1. Editer un équipement
2. Cliquez sur le bouton 'Configuration avancée' puis sur l'onglet 'Disposition'
3. Sélectionner 'Tableau' dans le champ 'Disposition'
4. Définir les dimensions du tableau puis sauvegarder.
5. Dans 'Configuration détaillée' organiser votre tableau puis sauvegarder
6. Retourner dans le Dashboard pour visualiser.

**Screenshots**
![Screen Shot 03-14-19 at 12 33 AM](https://user-images.githubusercontent.com/10147784/54321425-64145600-45f1-11e9-8a11-1b24e3845654.PNG)

**Information matérielles**
 - OS : armbian 9.5 (Odroid C2)
 - Navigateur : tout
 - Version NextDom : 0.1.3
 - Branche NextDom : develop
 - Installé via : git clone

**Labels**
Ajouter à droite de cette issue le label Component_XXX ciblant le composant lié à cette issue...

**Comment by Gis70** [comment]
Pour ma part il ne s'affiche pas une fois l'édition terminée.
![image](https://user-images.githubusercontent.com/16589132/54718087-05ebf380-4b5a-11e9-9991-03bdb102b4bc.png)

En mode édition 👍 
![image](https://user-images.githubusercontent.com/16589132/54718112-13a17900-4b5a-11e9-848b-3dd4ed41a750.png)

**Comment by Gis70** [comment]
OK validé, pour faire le carré c'est un code CSS ? on peut l'avoir ?
