### ISSUE TITLE
Liste déroulante illisible dans fonction dans scénario thème Dark

### ISSUE THREAD

**Issue by Gis70** [NextDom/nextdom-core#987]
Le menu déroulant est illisible 

![image](https://user-images.githubusercontent.com/16589132/54391680-d34b8200-46a5-11e9-9732-f8a9f6d30b11.png)

**Comment by perarem** [comment]
Confirmé sur la branche develop du 12/03 pas sur la branche Fixes

**Comment by cyrilphoenix71** [comment]
pas sur la branche fixes, je clos
