### ISSUE TITLE
Le menu de filtrage des pièces en haut du dashboard bouffe la moitié de l'écran d'un smartphone

### ISSUE THREAD

**Issue by Astral0** [NextDom/nextdom-core#990]
Le menu de filtrage des pièces en haut du dashboard bouffe la moitié de l'écran d'un smartphone.
Il faudrait pouvoir le replier ou le faire disparaitre.

**Comment by cyrilphoenix71** [comment]
ok validé

**Comment by Gis70** [comment]
c'est lequel de menu, je vois pas trop ? une capture svp ?

**Comment by Gis70** [comment]
OK validé
