### ISSUE TITLE
Couleur écriture historique des commandes thème Dark illisible

### ISSUE THREAD

**Issue by Gis70** [NextDom/nextdom-core#991]
![image](https://user-images.githubusercontent.com/16589132/54479936-f7809d80-4822-11e9-8451-cdf0072154cf.png)

![image](https://user-images.githubusercontent.com/16589132/54479957-2eef4a00-4823-11e9-9d7c-1b93a474f4cf.png)

Les champs de recherche dans la configuration de l'historique des commandes est quasiment de la même couleur que le background

**Comment by cyrilphoenix71** [comment]
bug disparu dans branche fixes, je clos
